title: "olano.dev"
avatar: "/assets/img/inchequeable.png"

permalink: /:year-:month-:day-:title/

# set explicitly to (hopefully) prevent mixed content (assets served on without ssl)
url: "https://olano.dev"

excerpt_length: 50

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - org/
