---
title: 2025
date: 2025-12-31T12:30:00-03:00
layout: post
lang: es
tags: [meta]
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

No suelo hacer retrospectivas pero [[https://lobste.rs/s/npnchn/what_are_some_interesting_projects_you_ve][un post]] de lobste.rs me hizo revisar [[log][el log]] y darme cuenta de que este fue un año más cargado de lo que me acordaba. Empecé el dos de Enero haciendo la fila en la embajada yanqui para que me otorgaran una visa, que usé en septiembre para un viaje de trabajo con detour a Nueva York, saldando así una cuenta pendiente con mi yo trotamundos de la década anterior. En febrero y marzo tuve un discreto /lost weekend/, viviendo solo tras 10 años de convivencia, aunque sin separarme. Las tratativas para mi vuelta a Almagro se precipitaron por un breve episodio de salud ---de primera impresión grave pero en fin falsa alarma--- y subsecuente internación, que describí brevemente en mi [[foster-wallace][post sobre David Foster Wallace]]. Escribí también sobre [[ese-chicle][David Lynch]], [[2666][Roberto Bolaño]] y [[la-tierra-elegida][Juan Forn]], un repunte de mi producción en castellano que pretendo profundizar el año próximo. Fue en parte ese post sobre Lynch lo que reavivó mi interés por el cine; este año vi unas cuantas películas y volví a animarme a ir solo al cine---mis preferidas: la de Bob Dylan y /Una batalla tras otra/. Empecé muchos más libros de los que terminé y ninguno me fascinó. Jugué unos cuantos videojuegos, la mayoría olvidables, con la notable excepción de [[blue-prince][/Blue Prince/]], que todavía no puedo soltar. La revista Paged Out! [[https://pagedout.institute/download/PagedOut_007.pdf#page=29][publicó]] un resumen de [[a-pixel-parable][mi ficcionalización]] de los años de Mark Ferrari en Skywalker Ranch. Una semana después de mi internación presencié (televisivamente) la mayor exhibición de la historia del fútbol argentino ante Brasil. Como todos los años me ilusioné y me desencanté con las posibilidades de Boca Juniors y pasé una cantidad inmoral de horas escuchando a periodistas deportivos estirando el aire sin nada que decir. Por el lado técnico, leí y reseñé tres libros ---[[unit-testing-principles][/Unit Testing Principles/]], [[domain-driven-design-revisited][/Learning Domain-Driven Design/]] y [[balancing-coupling][/Balancing Coupling/]]---, hice algunos [[agents2][experimentos con IA]], armé un [[https://news.olano.dev/][portal de noticias]] para [[gleam-coming-from-erlang][probar Gleam]] y [[https://giralibros.com/][una app]] para cambiar libros con mis vecinos lectores, de la que estoy especialmente orgulloso. También estoy orgulloso de haber atravesado decorosamente otra sucesión de triunfos y frustraciones laborales, y me entusiasma saber que me espera un nuevo proyecto del otro lado del calendario.
