---
layout: post
title: "A few more things you can do on your website"
date: 2024-02-22T10:16:17-03:00
tags: [web, projects, ideas]
lang: en
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

A couple of days ago I enjoyed reading [[https://jamesg.blog/2024/02/19/personal-website-ideas/][James's list]] of things to do on your website and, as he suggests by the end, I thought of a few more to add to the list. These are things I've either already done here or thought about doing but decided not to, or plan to eventually do:

1. A *notes* section, to write short updates (as an alternative to Twitter/Mastodon).
2. A *reads* section, to list books you read or want to read, along with notes or even ratings (as an alternative to Goodreads).
3. The same as 2. but for other media, like movies or video games.
4. A list of bookmarks or even a linkblog. (I considered generating this out of my [[https://github.com/facundoolano/feedi][feed reader]] favorites).
5. A list of favorites or suggested starting points for your blog, to provide an alternative reading path from the default reverse chronological order. (I discussed this idea [[file:web-anthologists][before]]).
6. Dedicated RSS/Atom feeds for all of the above.
7. A dedicated RSS/Atom feed for each of your blog's tags.
8. A *[[file:../../resume][resume]]* section (as an alternative to LinkedIn).
9. A *download as epub* button for your entire blog archive, or subsets of it, to make it accessible to offline reading devices.
10. [[http://microformats.org/wiki/microformats2][Microformats]] support.
11. A *[[file:../../projects][projects]]* section.
12. An *ideas* subsection of your projects section, to describe projects you haven't tackled yet.
13. A *won't do* subsection of the ideas subsection, to describe projects you gave some thought to but decided not to pursue because life is short; writing some notes down sounds much more satisfying than just forgetting about it[fn:1].

** Notes

[fn:1] Note how this very list works as a sort of /won't do/ project list[fn:2].

[fn:2] Also note how, if you are not into tinkering with the layout, most website section ideas double as "things to write about in your blog"[fn:4].

[fn:4] This reminds me of the Borges hack: instead of executing an idea he had for a novel, he would write a summary of it as a short story, or an essay pretending someone else had already written it[fn:3].

[fn:3] Which, in turn, reminds me of its software equivalent: instead of implementing a project, write a blog post about it or a README file on an empty git repository, as if the project already existed.
