---
title: A Pixel Parable
date: 2024-09-22 17:52:07
layout: post
lang: en
tags: [videogames, software, fiction]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

#+begin_verse
/An imagined town is at least as real
as an actual town./
#+end_verse

#+begin_export html
<br/><br/><br/><br/>
#+end_export

"How would you like working on video games?"

Mark is holding his "Best of the Show" certificate on one hand and, on the other, the card this guy just handed to him:
#+begin_export html
<div class="center-block">
<p>Gary W.</p>

<p><small>Art Director</small></p>
<br/>
<p><small>LucasFilm Games</small></p>
</div>
#+end_export

LucasFilm as in George Lucas. As in /Star Wars/.

This is his second lucky break of the weekend. A friend recommended he show up to this sci-fi convention, she said that these things were good for networking. He wouldn't mind having one of his illustrations on a trading card, or a rule book, or, who knows? on the cover of one of those fantasy novels he used to read in high school.

So he shows up to the convention on Friday. Someone notices his work---these pencil landscapes that look hand-painted---, they invite him to join in the art show, he does, two days later he wins  first place. That's his first lucky break. The second is this guy, Gary, coming over to him, handing him a card, asking him to 'audition' for a video game job.

"Could you come over to the Ranch for an interview?", Gary insists.

Mark reads the card again, stops for a second to think what to say next. He needs a job, after all. Honesty has been working wonders for him so far, so he tells it straight: "I'd be happy to come over to do anything at all there but... I don't know the first thing about video games. I never even touched a computer."

"That's alright", Gary replies, "we've had better results teaching artists how to program than programmers how to art. I'm not worried about that part."

He drives back home that night, trying to make sense of what just happened. On his first weekend---on his first serious attempt as a professional illustrator---he's offered to interview for a job that he didn't even know existed five minutes before, but that he now thinks is undoubtedly his dream job---and one that he's terribly unqualified for.

Mark calls his parents to share the news. His father, he now learns, has just bought a personal computer. That's his third lucky break.

#+begin_export html
<br/><br/>
#+end_export

"What are you doing with this thing, anyway?" Mark is sitting in front of the computer, skimming the manual. The cover reads /Atari 520ST/.
"The school made a deal for us to get them at half price. They say we should get /computer-literate/ if we want to have a job in five years." The voice comes through the doorway, then his father, leaning on the frame. "I figured I could use it for writing, but they have a different brand at school, so I can't print my files there. And I'm not buying a printer, so I don't see the point. You can have it if you want."

"Let's see if I get the job, first." Mark continues reading the manual. "It says here there's a drawing program in there, 'NeoChrome'. Let's try that out." It takes them about 20 minutes to find the floppy disk and open the program---their first project since his father thought him how to change his oil over a decade ago. Then Mark switches to the NeoChrome manual. Another half hour later, Mark is dropping little green dots over a blue background.

For the next few evenings, Mark secludes himself in his old high school bedroom, getting familiar with this computer thing and its painting program. The little mouse feels like a potato, forcing his hand into a claw. Whenever he begins to feel that he's got the hang of it, that he can forget about the tool and focus on the task, whenever his eyes spark a connection between the image on the screen and the image on his brain, his hand jerks to grab a pencil, his phantom limb.

He teaches himself to draw a single picture, a little African hut that he repeats over and over until he memorizes the procedure, which he will repeat a few days later to survive his interview.

#+begin_export html
<br/><br/>
#+end_export

Mark walks out of the garage and meets Gary at the porch. Gary shows him around the Stable House, introducing him to everyone in the Games Group, and takes him to his desk. He'll be sitting next to Gary and across the hall from Ron and David, the two programmers they'll be working more closely with. Mark notices there are not one but two different computers on his desk. And neither looks like the AtariST he's been using.

"That's a Commodore 64", points Gary, "and that's a DOS PC. We've been transitioning from c64 to DOS. In fact, your first job will be helping us to port the backgrounds of our new game. You'll notice these are, uh, a bit... clunky, when it comes to graphics. Especially that one", he points at the PC.

Mark feels like throwing up.

"I know, it's a lot", Gary laughs. "Look, the only thing you need to know about this one is how to run the game. And for this one... You'll mostly just be using DPaint".

Nobody around here really knows what they are doing, Gary reassures him, not even the programmers. They are all just trying to figure out what it means to tell a story in this new medium, in this new genre. What a video game worthy of LucasFilm should be like. There are no experts at /that/. "An artist perspective is what we expect you to bring to the table. The tools, you'll figure out. They change all the time, anyway".

They spend the next hour fiddling together with Deluxe Paint II, the drawing program for the PC. It's more or less the same as NeoChrome, but with more sophisticated brushes, or so Gary says. Mark notes the colors are fewer and uglier than the ones he saw in the Atari. "Oh yeah. Those are the colors of your nightmares, starting tonight".

After lunch, Ron sits with Mark to play /Maniac Mansion/, his B-horror adventure game. He shows Mark how to move around, how to talk with other characters, how to solve puzzles to make progress. /Maniac Mansion/ is a sort of blueprint of the kind of work they are trying to do. There's a newer game they've been working on, David's game, /Zak MacKracken/, but /Maniac Mansion/ is a gentler introduction. It's best if Mark just spends a couple of days playing it, to get the idea. Marks imposter syndrome kicks in now and again, and he apologizes for his dumb questions. He's no gamer, not even an arcade player. That's perfect, says Ron: they want to build something that just about anyone can pick up and have fun with.

He leaves the office with sore eyes from the computer screen and a headache from all the names and images shoved into his brain. He's relieved that no one's around to see him pull his Honda out of the underground garage. He slows down as he drives by the Main House, where they had lunch that day, a new building made to look old---not any old but period-specific old. He confirms that it looks just like the one they put in the game. He circles by the artificial lake and passes the barn, the corral, the vineyard. This little valley surrounded by green hills feels as otherworldly as one of his fantasy landscapes. Or a shot from /Star Wars/.

#+begin_export html
<br/><br/>
#+end_export

His first assignment is to port /Zak MacKracken/'s Commodore64 backgrounds to the EGA. David hands him a description of each location in the game. They call them /rooms/ even though some are outdoors---outer space, even. Each one has a short description and a list of "hotspots", the things the player can interact with: objects, doors, that kind of thing. Mark has to make sure that those remain visible on his ported backgrounds. Other than the list of rooms, the only design document is a huge puzzle chart posted on the wall, a sort of storyboard for programmers. Mark can't make sense of it, or the game, for that matter. /Zak MacKracken/ is bigger and more ambitious than /Maniac Mansion/; the work is more interesting, but the game is undecipherable to Mark.

At first, he tries working from the original c64 bit maps, but that complicates things.
Both are 16 color systems, but /not the same/ 16 colors, so swapping them is pixel Whac-A-Mole. He turns to redrawing the backgrounds from scratch. He sketches on his notebook to try options, he plots the pixel grid in graph paper and draws on acetate sheets that he then tapes to the monitor. He will try anything before moving to the computer, where nothing flows, where everything is clumsy and rigid as Lego building, and it's hard to tell whether something will work or even fit until it's almost done.

Black, dark gray, light gray, white, dark blue, light blue, cyan, yellow, mustard brown, dark red, poppy red, peach, magenta, acid-hot pink, grass green, and acid-chartreuse. Always the same suffocating 16 colors for anything he needs to draw. He has to ponder carefully what colors to "spend", an early decision that constraints the rest of his choices: the scene composition, the mood, what's shown, what's hinted. There's no room for impulse or experimentation, everything needs to be planned in advance. Despite his Digital Background Artist title, his job doesn't seem to be concerned at all with art. He's like the poet employed as copywriter. The only creativity is in subverting the tools, working against and around them, eventually leaning on their limitations.

#+begin_export html
<br/><br/>
#+end_export

# TODO maybe comment what they are having, some gourmet meal. osso buco with risotto

"Coppola", says David.

"Coppola, of course", Gary concurs. "The Rolling Stones".

"Wait, all of them?"

"Hmm. Mick Jagger. And the drummer, I guess."

"I missed them. I did see Huey Lewis."

"Yep. We played softball with the band."

It's Mark's third week, and it's the first time he catches a glimpse of George Lucas. They usually only see him at the restaurant when he has visits. Gary and David are listing all the famous people they saw at lunch. Today it's Spielberg.

"You'll understand, of course", David turns to Mark, "that while it may seem as if they were right there across the room, we are not breathing the same air. We're worlds apart."

"Galaxies", Gary suggests.

"Galaxies apart, thank you. They are holograms, like that Leia message on the first one. We can see them but they don't see us."

"Under no circumstances should we be noticed by Lucas or one of his guests, or any film-related people."

"And especially not Lucas."

The owner doesn't care at all for video games. The existence of the games division is a sort of corporate accident, a spin-off of the Graphics Group prompted by a failed collaboration with Atari, a product of another age of the company. And the fact that they got to stay while the Graphics Group---now called Pixar---was sold to Steve Jobs, is another corporate accident. They're a rounding error, the last hackers standing, the only division totally unrelated to film making. A kind of intruders. So the idea is to make themselves invisible, not to remind George Lucas that they exist, that he still owns a little video game studio, that they are spending his money and---much worse---taking up his precious space.

"Our man Steve, on the other hand, is our biggest fan", David points his fork to Spielberg. "You'll be seeing a lot of him."

"This is like an amusement park to him. He's more into it than Lucas, I think."

"He'd probably live here if he wasn't busy, you know, making blockbusters."

"Did you know he used to call Ron for /Maniac Mansion/ hints?"

"So yeah, I bet he'll get involved in one of the games sooner than later."

"An Indy game, most likely."

"When the tech is good enough."

"And when they get back the license."

"Right, when we get the license."

That part Mark already knows, he learned it on his first week: LucasFilm Games doesn't have the rights to make LucasFilm games. No /Indiana Jones/, no /Star Wars/. Some toy company holds the license.
They are expected to come up with original ideas for their games, which is both a blessing and a curse:
they have the creative freedom but they must live up to the Lucas standards without the easy cash of his IP.

#+begin_export html
<br/><br/>
#+end_export

The mouse, the pixels, the 16-color palette, the hotspots: those are the constraints he has to work with.
One trick he discovered early on---a /hack/, programmers would say---was that, if he arranged pixels to form a checkerboard pattern, they would blend and bleed as he zoomed out on the computer screen. Much like the eyes finish the job as one steps back from an impressionist painting, the monitor melts the pixel mosaic into something richer than whatever the dull EGA palette was supposedly able to project. At first this is just an accidental observation, he doesn't make much of it. It's only when he starts working on a new batch of /Zak/ backgrounds that he finds himself coming back to those mixed pixels.

This section of the game takes place in Mars, a location Mark finds very provocative.
Here he owes no loyalty to the muddy c64 backgrounds. For a change, the acid EGA palette seems strangely fitting. He realizes he can "weaponize" the pixel blending artifact. And he needs not abide reality here, he's safely into fantasy territory. He can turn this one of his classic sci-fi landscapes.

He settles quickly on a composition, a rocky horizon inspired by the Grand Canyon, sitting on top of a desert of fiery sand and a pale orange sun slightly removed from the center of the screen. It's the palette that gives him more work. A few attempts to settle on a rough plan, then hours of trial-and-error to find the right color combinations and the right density of interleaved pixels for each figure, each boundary.
He wants the image to jump out of the screen; he wants the sky, and the sun, and the ground to bleed into each other distinctly---the sun to set the sky on fire and the earth to bed the ashes.

It's not the original c64 background, or the EGA palette, or the hotspot list what mandates his work. It's not what he pictured in his head. It's the pixel braid, each born out of the previous one, each birthing the next. Every pixel boils with possibility and serves no purpose other than to carry intent.

For the first time, he doesn't feel constrained by the material. He's so free that the work becomes free, the work now takes life and talks back. He tamed the material into rebelling and becoming something other than what he set out to produce, something better that what he could have imagined. It's then, when the work starts speaking for itself that he knows his onto something. It may not be art, not yet, but it's better than anything he did and anything he's seen on a computer screen. There's the spark. This is the direction, that's where he needs to go.

#+begin_export html
<br/><br/>
#+end_export


Ron sticks the floppy in his computer and loads the image. He waits for the fringes to cover the screen and gives it a couple more seconds before speaking up.

"What the hell, man?"

"I... wait, what?" says Mark.

"The pixels here look all... dithered. This won't compress." Ron speaks in his soothing monotone, which makes it all the more scary when the words imply he's not happy.

"Dithered?"

"What's up?” Gary joins them. "Wow, that's a neat background. Oh, wait, that won't compress. Yeah, you can't do that."

"Compress?"

"Those little patterns there, you can't do that, that will take too much space."

He's been doing this for months and still can't tell when it's right. It's like computers have a bunch of rules that everyone but him knows about. And the programmers, too, come with their own rules, they are another kind of machine that he needs to poke about until something works.

In these situations, Gary gets into the little technical details, not because he cares that Mark understands them but because he wants Mark to know they have important reasons to clip his wings: the image data is run through a compression algorithm so it takes up less storage in the disk. Instead of storing the colors pixel by pixel, they store how many times the current color needs to be repeated; the more same-color segments the image has, the fewer space it will take on disk. His little checkerboard technique---his color "dithering"---completely breaks the process, changing colors at every step, never repeating, making the compressed image take /even more/ space than the source. Dithered backgrounds would double or triple the required disk space, which would double the amount of disks required to ship the game, which would double production costs, which would double the game's price tag, which would surely get them all fired. "Try again with solid colors, please,” he concludes, and pats him on the back. "That was some landscape, though, huh?"


#+begin_export html
<br/><br/>
#+end_export

His bodily reaction to screen time is somehow connected with sleep deprivation. At first, pulling 6 or 8 straight hours in front of the computer seemed to burn him out, but after 10 or 12 he doesn't really care, he just keeps going until he passes out on the keyboard.

<everyone warned him there was going to be crunch time when they got closer to the release date
<Here's the thing about deadlines: everybody knows they won't make the first one or two deadlines, and that's fine, but also everyone accepts that they'll miss them in crunch mode, if anything to keep up appearences
mark defaulted to a belligerent attitude towards authority and thus was, in principle, against overtime and having to meet executive demands and meet deadlines
but, also, he didn't really mind the effort.
he never once lost sight that
he was getting paid to be an artist---even though he didn't felt these computer drawings were there yet---
he was paid handsomely, more than every other job he ever had (more than both of his parents combined)
he was having fun, he respected his teammates,
he was working at geek disneyland,
<most people would continue to show up every day even if they cut their pay checks

he was already used to working late, in the quite months they would take long lunches or hikes through the hills or they would toss a softball around in the field out back, so they ended up working late to make up for the time
most of the people on the team was in their early twenties so they didn't have anywhere better to be anyway

so as the project deadlines arrived, they just kept working late, only skipping the long breaks during the day.

weekends at the ranch, though, were off-limits. they would let him take his computer back home on fridays to work during the weekend

during this periods he got used to taking breaks from the works without getting away from the computer. he always kept one or two personal illustrations on the side, where he <got off> from all the restrictions that the game backgrounds imposed on him
he would use dithering, and colors otherwise reserved for sprite characters, and unconventional image dimensions

if they tell him that dithering is off-limits, then he'll put in as much dithering in his personal work as he can.
what's a good excuse to do this a lot? what type of background would call for a gradient of as many colors as one can think of? A sunset.
<TODO lookup details about this sunset in the interviews
<starry night?
# FIXME maybe too much stress in the martian background that should be here instead
# consider at least calling it back

this was... art. and now hi was annoyed that he couldn't put stuff like this in the game. he set it as a screensaver in his computer to send a passive-aggressive message, a kind of protest---against no one in particular, no one in his team, anyway. Ge was protesting Turing and Von Neumann and George Lucas and Ronald Reagan, for making it so damn hard to make art for a living.

takes a long lunch, when he gets back to his desk the divsion director and gilbert are discussing, why exactly doesn't dither compress? can't we do anything about this? art like this in our games would be a game changer, the differential people came expect from our films, now in the computer.

a few weeks later he was informed that dithering was now supported. he realizes the programmers too have their own set of constraints, their own challenging puzzles they need to resolve to get some creative output from these machines

the division head told him they would double down on dithering for the look and feel of the next game, that he would be lead artist for it. your <stock> just went up.

#+begin_export html
<br/><br/>
#+end_export

<"Imagine that you can get off the boat and wander around, learn more about the characters, and find a way onto those ships". This is how Ron described the concept for his pirate game.

<A new Ron adventure was only second in anticipation to the advent of the /Star Wars/ license. He wanted this one to be the ultimate realization of his design philosophy. Which was, more or less, the Group's official design philosophy.

<he even had a journal publish his "why adv suck"
<mostly not applies to art, except for the "rewards part" that stuck with him

< a /Pirates of the Caribbean/ disney ride spoof
<it was his way of doing fantasy-like setting, without touching fantasy, which he hated

#+begin_export html
<br/><br/>
#+end_export

The Main House is a ten-minute walk from the Stable House. Mark mentioned he would go over to the library and Purcell tagged along. Nobody passes on an excuse to visit the Main House.

"What are we researching?", he asks as they leave the porch.

"I want to look up some material for /Loom/. Some of that /Sleeping Beauty/ stuff he mentioned."

"Oh, so it's /actual/ research." People in the Games Group use /research/ as keyword for anything that blatantly isn't work. They ask /What are you researching/ to anyone they catch fooling around the office. "Well, I guess I can use some reference material myself".

Mark was assigned as Lead Background Artist for /Loom/. Purcell will do animations. It's his first video game project. They are supposed to figure out how to turn an EGA adventure into a "living tapestry", like Eyvind Earle did with /The Sleeping Beauty/.

"So what do you make of The Professor?" asks Purcell. Professor is what they've been calling the project lead. They just brought him from Infocom, the struggling text adventure shop.

"He seems cool."

"Very cool."

"He certainly knows his game design."

"Oh, yeah."

"Maybe he's a bit too...”

"Professorial?"

"...well, I don't want to say /ambitious/, because", Mark waves at the house, they are walking past the Solarium, over the right wing of the House, "who isn't around here?"

"He better be. /Be the best/, right?"

"...but, perhaps too much of an idealist. I can't believe /I'm/ saying this." In a sense, Moriarty is like him: they take their work very seriously, they are both driven by a desire to produce art. But Mark knows all too well that, despite his title, he isn't paid to make art. They pay him to produce backgrounds, conforming to a set of specifications. The art, he has to smuggle, in spite of the business. The Professor, on the other hand, seems committed to breaking new artistic ground, and operates as if everyone else shares his vision. Mark couldn't imagine any other company where they would give such a guy /carte blanche/ to make whatever game he wanted.

# TODO lookup infocom descriptions, maybe one from a moriarty game
# FIXME should the IF spoof be it's own section? it's kind of weird in the middle of this one without a break
<They are standing in the hall of the Main House, <DESCRIBE ARCHITECTURE>. The east corridor leads to the solarium. To west corridor, leads to the restaurant. To the north is a large wooden door and, on each side, a staircase. <There's a stormtrooper here.> <There's a crystal display case with a Yoda model in it here.> They go north.

"I mean, a fantasy game?" Purcell continues as they enter the Library, "/The Sleeping Beauty/? Tchaikovsky? Doesn't sound very LucasFilm to me."

"I like a good fantasy", says Mark.

"More /Lord of the Rings/ than /Star Wars/. Or /Indiana Jones./"

"But, does it sound like /Maniac Mansion/ or /Zak MacKracken/. That's the real question."

"...or /Sam & Max/."

"Or /Sam & Max/, sure,” Mark concedes. Purcell is on a mission to convince everyone there /could be/ a game based on his comic. If he plants the idea on enough heads, someone will eventually ask him to make one.

"Well, I'd say it sounds like /Zork/, obviously... and /King's Quest/?"

"Ouch."

"Well, what do I know?” says Purcell, "I haven't played any of them."

"Me neither."

There's a counter at the entry of the library. <TODO describe: spiral staircase leading to the 2nd story and to Luca's office, stain glass dome

They need to register before going in. The librarian asks them what's the purpose of their visit.

"We're looking for research material for /Loom/,” says Mark.

"He's looking for research material for /Loom/. I'm looking for research material for /Sam & Max/.”


#+begin_export html
<br/><br/>
#+end_export

The memo supplied two separate but related pieces of news: LucasFilm secured the rights to make /Indiana Jones/ video games; they have six months to come up with a game based on the new entry Spielberg is shooting.

Management assembles a team with their most experienced designers to lead the project, they pause development on /Monkey Island/ and /Loom/. This is supposed to be a quick and dirty one, no room for Mark's precious imagery and experimentation. He is relieved, if a little worried, that they let him continue his work on /Loom/ while most of his colleagues to switch to /Indiana Jones and the Last Crusade/.

The team gets a copy of the script and some early footage to go on. The designers struggle to make the game fit the script and still be playable and fun. They aren't sure how to keep it interesting to the majority of players that will already be familiar with the plot. Artists are similarly constrained by the footage and the production stills. Some of the folks even get to visit the set. Purcell comes back with a whip for "research purposes", which he incorporates to their afternoon sporting events. Someone borrows the Holy Grail and they take pictures drinking coffee from it.

When Spielberg is done editing at the Ranch, they do a screening on the Art deco theater on the Main House.
The Games Group people walk back to the Stable House, excited about the film, discussing the scenes that Spielberg cut but that's too late to remove from the game. Mark loved the movie but feels uneasy about the game. It feels rushed and derivative, all about the money. The writing is on the wall. Once they lift the /Star Wars/ embargo, it's going to take a hell of an effort to prevent the suits from putting all hands on deck to milk Chewbacca.

#+begin_export html
<br/><br/>
#+end_export

Some times Professor Moriarty gives Mark and Purcell story prompts and asks for concept art in return, but more often than not he wants /them/ to come up with stuff he can use for inspiration, based on the short treatment document he handed them and the /Sleeping Beauty/ reference material. This was the first proper illustration work he did since he joined the company two years ago.

Mark pulled everything he could get from the library on Disney, Eyvind Earl, and medieval tapestries. He would play the movie on the Media Room of the Main House, frame-freezing to take notes and make sketches. Mark would deliver two or three drawings a week, using his now legendary pencil.  Most of the times, Moriarty would come back with notes to refine an idea or a request to try again, but occasionally he would take a drawing and use it to write a piece of the story. In those cases the Professor would ask Mark to convert his illustration into a dithered EGA background, so he could wire it up in SCUMM and start experimenting with descriptions and dialog.

The Professor set up similar work streams for animation and programming and, most importantly, with the sound department. Music and sound would feature in /Loom/ more prominently than in any other LucasFilm game.
which was convenient, since the Ranch housed the best sound engineering facilities in the world
<for them, instead of Eyvind, it was tchaikovsky
<much of the game's concept would be centered around the music of Tchaikovsky, just as in the film, so he suggested they explore its art style for the background art and the animations

<Moriarty thought of games as a novel medium to produce art, and he wanted to use all of its materials to that end: sound, music, backgrounds, animation, story, and dialogs. He made sure everyone on the team picked up on his vision for the game and gave them freedom to figure out how to realize it with their tools.
Coming from a rather lonely experience writing text adventures, he was betting on team collaboration to flourish to <unlock a deeper storytelling experience. This ideal would find its way into the story, with the protagonist visiting Guilds of Craftspeople over the course of the game.

Mark would come up with the idea of using colors scheme to represent each guild, giving a distinct quality to each section of the game: the striking emerald of the Guild of Glassmakers, the softer pastoral greens of the Guild of Shepherds, the Stygian reds of the Guild of Blacksmiths and of course the lovely saturated blues and purples of the Guild of Weavers. This is a feat he imposes to himself, with the EGA colors allowing for one or two shades of each color, the rest having to be mocked with dithering and other palette tricks.

The latest version of the SCUMM engine not only allowed for Mark's dithered backgrounds, but introduced character scaling to represent distances, allowing him to move away from the horizontal axis and add perspective to his scenes.
For the first time he wouldn't be adapting someone else's rooms, he knew his tools and was free to push them to their limits to create whatever he could envision.

#+begin_export html
<br/><br/>
#+end_export

The memo sits on his desk:

#+begin_export html
<div class="center-block">
<p>The Return of the License</p>
<p><small>LucasArts Episode I</small></p>
</div>
#+end_export

He doesn't read it.

#+begin_export html
<br/><br/>
#+end_export

# maybe describe the room? or the demonstration itself?
The artists are gathered at the Technical Building with for a scanner demonstration. It's a little tray, like a Xerox machine, minus the printer. It's connected to a Macintosh computer. The scanner costs 10 times the computer, the guy said.

"This new guy, Peter, is doing this for the /Monkey 2/ backgrounds,” says Purcell, pointing to the machine.

"Really?" Mark isn't on the /Monkey Island/ sequel.

# FIXME some of this, eg vga stuff, is already partially covered by the dialogue below
<There was a lot of movement around the office during those final /Monkey Island/ weeks. Mark was just too deep in crunch mode to notice.
They seem to be growing faster, one or two new employees starting every week. They will start a magazine to include in the game boxes. They interviewed Ron and <commissioned> Purcell for one of his comics.
<Everyone got new PCs, with VGA cards and monitors.
at first it felt like an independence day to mark they would be free at last from their EGA jail
but now he wasn't sure how to adapt his work process to a 256 palette. it wasn't driven by the color planning anymore.
These new computers felt like a career reset to him.

"The art is gorgeous, but it comes out all fuzzy on the other side of /that/.", he points to the scanner. "He has to go back and clean everything up in DPaint."

"He might as well do the whole thing in the computer."

"He's no fan of the mouse, though."

"Who is?", Mark snorts. "It's funny, I would've loved this a couple of years ago. My life would've been much easier."

"Yeah."

"Now it feels like a downgrade, you know? It's like with these VGA ports they are doing now."

"The 'enhanced' versions."

"The 'butchered' versions. They just use gradients for everything. It's like they want DPaint to do all the thinking for them."

"We're right here, you know?" someone mumbles at the back.

Mark continues: "It felt like we were finally getting the hang of this, during /Monkey Island/. Now it's like starting all over."

<People said Monkey marked a new beginning for LucasFilm games, but to Mark it felt more like a culmination of the process they started four or five years before. The tools were at their best and for the first time everybody, the designers and the artists, seemed to know exactly what they were doing.

"A technology is always at its best right before it's obsolete, man", says Purcell.

"Who said that?" asks Mark.

"One Purcell."

"Smart fella."

He can almost see it: after VGA and scanners it will be compact discs, or RGB color, or those 3D models they've been using over at the ILM basement. More colors, more space, more processing power, but also more complications, more time to master the tools. Forget about creativity or innovation, squeezing any art out of the machines, they'll be struggling just to stay competent. Before they know it, they'll be starting over with the next hot thing.

#+begin_export html
<br/><br/>
#+end_export

Mark walks towards the door, then turns. "I can't leave yet, I haven't finished packing". He looks at his desk. "I should put all this stuff in the box".

A pile of sketchbooks. "They are labeled by month and year".

A worn out DPaint 2 manual. "I haven't used this in ages. I could write one myself by now."

A set of colored pencils. "I hand picked them myself, one for each of the 16 EGA colors. I guess won't be needing these anymore".

An issue of /Sam & Max/. "My favorite."

An Indiana Jones action figure. "Indy."

A /Sleeping Beauty/ reference book. "I never bothered to return this to the main house."

A Chewbacca action figure. "Chewie."

A signed /Loom/ box. "It's signed by The professor. I signed another one for him."

He picks up the box. "This box is too full, I can't carry it like this." He puts it back. He walks towards the door, then turns. "I can't leave yet, I haven't finished packing". He looks at the desk. "Neat". He looks at the desk drawer. "It's a desk drawer". He opens the desk drawer. "There's a piece of rope here". He picks up the piece of rope. "This might come in handy". He uses the piece of rope on the box. "Much better". He picks up the box. He walks out.

#+begin_export html
<br/><br/>
#+end_export

The Honda Civic drives out of the underground garage and turns around the Stable House. Lake Ewok is glowing with the reflection of the sky, like a dithered EGA sunset. The car passes by the barn and the corral, then drives away from the security kiosk and onto the main road.

A tall tree goes by, followed by two short ones. Then two short trees go by, followed by a tall one. Then there are no more trees. The hills give way into a plain, Californian unlikely, the Honda moving in front of the darker blue sky, now tallest and deprived of any texture.

The road proceeds, then ends abruptly, an abandoned flooring job. The car rides on over generic green grass for a while, then reaches an edge and moves out of the picture. But not all of it. I can still make the trunk and the bumper, and a corner of a tire, sitting there, stationary.


#+begin_export html
<br/><br/><br/>
#+end_export

*** Sources
- [[https://www.bitmapbooks.com/en-ar/products/the-art-of-point-click-adventure-games][The Art of Point-and-Click Adventure Games]].
- [[https://www.youtube.com/watch?v=z1aVDael-KM][Classic Game Postmortem: LucasFilm Games' Loom]].
- [[https://www.filfre.net/2015/07/a-new-force-in-games-part-3-scumm/][A New Force in Games, Part 3: SCUMM]].
- [[https://www.filfre.net/2017/02/loom-or-how-brian-moriarty-proved-that-less-is-sometimes-more/][Loom (or, how Brian Moriarty Proved That Less is Sometimes More)]].
- [[https://www.filfre.net/2017/03/monkey-island-or-how-ron-gilbert-made-an-adventure-game-that-didnt-suck/][Monkey Island (or, How Ron Gilbert Made an Adventure Game That Didn’t Suck)]].
- [[https://www.filfre.net/2018/09/indiana-jones-and-the-fate-of-atlantis-or-of-movies-and-games-and-whether-the-twain-shall-meet/][Indiana Jones and the Fate of Atlantis (or, Of Movies and Games and Whether the Twain Shall Meet)]].
- [[https://bossfightbooks.com/products/day-of-the-tentacle-by-bob-mackey][Day of the Tentacle: An Oral History]].
- [[https://youtu.be/ri4_3P2Oh14?feature=shared][The Making of Monkey Island - Behind The Scenes]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-4-Loom/5][LucasArts' Secret History #4: Loom Developer Reflections]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-The-Secret-of-Monkey-Island/7][LucasArts' Secret History #5: The Secret of Monkey Island Developer Reflections]].
- [[https://scummbar.com/resources/articles/index.php?newssniffer=readarticle&article=1033][The Secret of Creating Monkey Island]].
- [[https://datagubbe.se/crt/][The Effect of CRTs on Pixel Art]].
- [[https://www.superrune.com/tutorials/lucasfilm_ega.php][Lucasfilm EGA adventures: an appreciation]].
- [[https://web.archive.org/web/20030326051107fw_/http://lucasfans.mixnmojo.com/features/interview_stevepurcell.html][Steve Purcell Interview]].
- [[https://grumpygamer.com/guybrush_fact_fiction][Guybrush Fact vs Fiction]].

*** quotes                                                         :noexport:

#+begin_quote
I feel the stage sets we rendered as best we could for those earlier games conveyed all sorts of personal artistic style and evocative atmosphere, while most of the 3d game environments that came after them seemed almost universally airless, lightless, and rendered in such a uniform 'algorithmic' art style.

I think we lost things---important things--- whenever accelerating technological fixes and agendas overtook, and to some extent eclipsed, human creative navigation and intent.
#+end_quote

#+begin_quote
had chosen to center his film-making operation in Northern rather than Southern California, much closer to Silicon Valley than to Hollywood.

Lucasfilm, the owner of Star Wars, had a games division that wasn’t allowed to make Star Wars games

“We’re trying to produce an experience that’s like being part of a film, rather than just being part of a game.
#+end_quote

#+begin_quote
he Games Group got moved from their nondescript offices in San Rafael to nearby Skywalker Ranch, the “filmmaker’s retreat” at the very heart of George Lucas’s empire. They were housed in an ornate structure of Victorian brick called the Stable House, with crackling fireplaces in almost every room. Later, old-timers would tell newcomers stories of the Games Group’s time at Skywalker Ranch, which would last for just a few years, like legends from before the Fall: catching a sneak preview of a new David Lynch film in the company of Lynch himself in the Ranch’s beautiful 300-seat art-deco theater; hanging out on a regular basis with Steven Spielberg, who wanted to play everything the Games Group had in development every time he stopped by, sometimes for hours at a stretch; playing softball on the Ranch’s gorgeously manicured field with rock star Huey Lewis; hiking up to the observatory after a long day at the office to do another sort of stargazing; eating gourmet lunches every day at the Ranch’s restaurant for $5 a pop.

providing production services to the film industry (Industrial Light and Magic, Skywalker Sound) and making mass-market entertainments. The old Computer Graphics Group that had awkwardly spawned the Games Group still hadn’t really proved themselves to belong in the former category, while the Games Group, at least if you squinted just right, pretty much did belong in the latter. Thus, while the Games Group got to remain at Lucasfilm, the Graphics Group in February of 1986 was spun off to a collection of investors that included many of their own current personnel as well as, as ringmaster of the whole proceeding, Steve Jobs

Soon the old Games Group represented the only significant hacker presence left at Lucasfilm. It was during this period of colossal change that George Lucas took rare personal notice of Games for long enough to deliver his most oft-quoted piece of advice to Steve Arnold: “Stay small, be the best, don’t lose any money.” This commandment has often been taken to represent a sort of creative carte blanche for Arnold and his charges. Taken in the context in which it was uttered, however, it’s probably better seen as a warning. The Games Group was free to continue to trade on the Lucasfilm name and enjoy their gourmet lunches at the company cafeteria, but they’d have to start paying their own way from here on. Should they fail at that, their rope would not be a long one, for Lucas had little personal investment in their work.

 Driving much of the design was a philosophy that adventure games should be friendlier, less tedious, and much less deadly than was the norm from competitors like Sierra.

the big neo-Victorian “Main House” at Skywalker Ranch. The spiral staircase inside the library in Maniac Mansion is lifted straight from the “filmmaker’s research library” in the Main House.
#+end_quote

#+begin_quote
a mandate came down from Lucasfilm Games’s parent company’s management: they wanted an adventure game to go with the upcoming film Indiana Jones and the Last Crusade. Such a mandate was unusual for the privileged little artists’ enclave that still was Lucasfilm Games at this time,

  Some start using it as a defense mechanism only after being slapped in the face by the game a few times, the rest just stop playing.

   major corporate reorganization was in progress at Lucasfilm, which saw the games division given far more resources — their personnel roll grew from about 25 to more than 100 between 1989 and 1991 — but also given much closer supervision. They would now be expected to justify each of their projects to the accountants. This transformation of Lucasfilm Games from sideline to major profit center was by no means viewed as a comprehensively bad thing by everyone working inside the games division — it did after all lead to them finally being let loose on the Star Wars intellectual property, something they’d been wishing for for years — but it would change the character of the place and the games that came from it forever.
#+end_quote

#+begin_quote
This committee approach to the game’s design is typical of the workaday nature of the project as a whole. The designers were given a copy of the movie’s shooting script, and were expected not to deviate too much from it. Ron Gilbert, a comedy writer by disposition and talent, found the need to play it relatively straight particularly frustrating, but it seems safe to say that all of the designers’ creative instincts were somewhat hemmed in by the project’s fixed rules.

if you’ve seen the movie — and it seemed safe to assume that just about everybody who played the game had seen the movie — what’s the point in walking through the same story again in game form? The

Those changing circumstances would prove a not-unmixed blessing for them, forcing them to move out of the rustic environs of Skywalker Ranch and shed much of the personality of a quirky artists’ collective for that of a more hard-nosed media enterprise. On the other hand, at least they’d finally get to make Star Wars games…
#+end_quote

#+begin_quote
when the Zak project was finished I sat down one morning and rendered a twilight scene with a rising moon and stars over receding oak covered Hills all rendered smoothly and subtly and dithered EGA graphics then in silent protest I simply left a picture up on my monitor
#+end_quote

<mosaic artist
impressionist painter
rough strokes of a van gogh self portraits

assembly line

#+begin_quote
it was my first time drawing with a mouse. i'm a traditional guy, so I like to draw with a pencil. So for me to try to drawn with a potato in my hand, and then, look up on a screen, and the pixels are the size coasters
#+end_quote

observatory

#+begin_quote
The Skywalker Ranch Research Library is not your typical library. Yes, it is filled with books, but also much more than that. It houses an impressive collection of research materials curated specifically to assist in the filmmaking process.

In addition to books, the Library contains documents, photographs, props, and other items that have been used in the development of Skywalker Sound projects.
#+end_quote

#+begin_quote
contains an impressive collection of Art Nouveau furniture and fixtures. There are Tiffany lamps and original paintings by Norman Rockwell and Thomas Hart Benton. Under a stained glass skylight sit shelves of books relating to all aspects of film production. In addition to their own impressive collection, their holdings also include the Paramount Research Library and the Universal Research Library collections.
#+end_quote

#+begin_quote
And to me, the shining star, the Lucas research library -a two story open atrium with books on every topic any writer, artist or musician could need to conceptualize a story. Ladders around the perimeter, a huge fireplace, and lush leather chairs and couches. On walking in, all I could think was something in my life has gone very right to have found that place - and something gone very wrong that I wasn't spending every day there.
#+end_quote

#+begin_quote
The team of stained glass artisans took six months to build the 19-foot dome. It was comprised of 400 sheets of glass, finely sculpted into 49 separate panels.

With the dome installed, the library took on a new look. The warm redwood and sensuous curves and details were continuously bathed in the amber light from the dome. Books from Hollywood studios’ abandoned research libraries were purchased and began to fill the shelves. The spiral staircase led to the upper balcony with a door into George’s inner office. This was his library.
#+end_quote

#+begin_quote
Already the displacement
of one's thought-child
is not only conceived,
but scheduled.
#+end_quote


*** tasks                                                          :noexport:

**** TODO design documents
https://grumpygamer.com/maniac_mansion_design_1
https://grumpygamer.com/puzzle_dependency_charts
https://grumpygamer.com/even_more_monkey_island_design_scribbles
https://grumpygamer.com/rtmi_pdc
https://grumpygamer.com/stuff_and_things_and_monkey_island
https://grimfandango.network/media/Grim_Fandango_Puzzle_Document.pdf

**** DONE review the adventurer issues
CLOSED: [2024-10-19 Sat 21:35]
https://archive.org/details/lucasarts-the-adventurer--magazine-complete/The%20Adventurer%2C%20Issue%20No.%2003%20Fall%201991/page/n1/mode/2up
https://archive.org/details/lucasarts-the-adventurer--magazine-complete/The%20Adventurer%2C%20Issue%20No.%2002%20Spring%201991/page/n3/mode/2up
https://archive.org/details/lucasarts-the-adventurer--magazine-complete/The%20Adventurer%2C%20Issue%20No.%2001%20Fall%201990/page/n1/mode/2up

**** TODO experiment with dpaint
**** TODO exploration scene?
e.g amusement park, monkey island style
**** TODO cleanup quotes
CLOSED: [2024-10-05 Sat 13:52]


*** chunks                                                         :noexport:
https://i.pinimg.com/originals/53/b1/f1/53b1f1a0961866d25ed578d345945dd4.jpg
https://cdn.mobygames.com/screenshots/15832026-zak-mckracken-and-the-alien-mindbenders-amiga-the-martian-landin.png
https://cdn.mobygames.com/screenshots/7743063-zak-mckracken-and-the-alien-mindbenders-commodore-64-the-landing.png

http://iveneverdonethat.com/blog_files/skywalkerranch.html

But it doesn't take him long to become productive. That is, to work out usable backgrounds fast enough to meet the developers expectations, which are lower than his own.

<There's little room for the sort of creativity that stems from impulse and experimentation (but much from constraints, pushing the boundaries, happy accidents that lead to innovation
it gets better as /he/ gets better, more familiar with the tools; once he grasps what are his materials and what their capabilities and limitations, he can start using them to his advantage---work around and step on the constraints and push himself to be creative as with any art and any material, just like does with pencil and paper.

<The one time Lucas showed his face in the Stable House, he said to the director: “Stay small, be the best, don’t lose any money.” That became their gospel, an easy way to answer the question /what would George want us to do?/,an easy way to settle arguments and make design decisions---and an evergreen source of jokes.

Purcell is quoting Lucas's only ever command to the Games Group: /stay small, be the best, don't loose any money/. Sometimes abridged as: /don't lose money, don't embarrass George/.

<the only part of this that affected him, Mark thought, was /be the best/, and that was how he intended to operate anyway, he didn't need a manager to tell him. he left to the suits, though, to figure out how his work and that of his teammates was supposed to be connected to the money making.

his goal was to produce art and get paid for it, so he give as little thought as possible to the needs of the project and the business.
it's convenient that they don't expect much from him, because not only he isn't satisfied with his production and it doesn't come close to art, he still feels he has a long way to go to tame the computer, the mouse, the pixels, the palette, and the drawing program.

<Mark developed his own style with the dithering, something he would teach others how to do. He wants to show how he does his thing, but not be prescriptive, allowing other artists to figure out their own style

<TODO: maybe, start with them playing wishbringer.
"we're doing research"
"what are you researching"
"brian moriarty"

Mark had tried one of their games. while he was impressed by the thorough descriptions and the setting---it was like they made him the protagonist of a fantasy novel---he was quickly frustrated by the complicated gameplay and all the typing it involved. It was like the complete opposite of everything Ron and Gary were trying to do with the graphic adventures. They were comic books to infocom's novels. <despite marketing desperation to sell them as interactive movies

<Before meeting him, Mark feared that his previous experience with from text games would make him dismiss graphic work, but Mark quickly realized that Moriarty was of his kin.

there was a librarian but, even he wasn't a book person, he preferred to browse around and find things by himself
the library, perhaps along the art deco theater, is the most impressive indoors location of the ranch
Mark would occasionally look up allegedly to the dome, but it was actually to look at Lucas's office door

<purcell joked that you would go blind if you stared at Mark's screen for too long

<brian asks Mark to illustrate the box of loom
this was an unusual ask, since Purcell did most of the covers of the other games
but Brian wanted Mark, as a sort of <tribute> since he felt it was Mark's work what defined the art style of the game
he had asked Mark to show him some of this work and was impressed by his colored pencil illustrations, so he asked mark to do it
it felt weird for mark, translating the mood of the game, so determined by the blue shades of the EGA backgrounds, to the
a photo realistic drawing he felt was at odds with the primitive art in the game, but Brian seemed to like it
now that Marks is holding the game box in his hands, seeing his work live for the first time---this he could hold and touch, it was much more alive than his work on the screen---, only now he realizes that this is the first time he got paid for a traditional work of art.

it was mostly a game design thing, it didn't affect the graphics, didn't directly affect him, but it was Ron's version of /being the best/ and Mark just felt he should follow suit and apply everything he'd been learning so far and push it to the next level

all his favorite people were in this team

They give him freedom to figure out the game backgrounds, handing him a short list of room requirements and hotspots and no other game context. as long as he meets them he can do whatever he wants.
where brian had been obsessed with story telling, ron was obsessed with gameplay, with the game being fun---and funny. nobody but him really got a clear picture of the entire game, but everyone took part of the brainstorming sessions
his water cooler jokes make it to the dialog of the game.

player reward -> new areas of the game (new backgrounds)

the game was bigger and would feature more rooms than previous ones. they had people working for different parts in parallel, which at some point showd that they werent keeping a consistent style across the game

<something special about this new team and this new game
they were having so much fun with this one, and that stimulated them to try harder and do better, that surely had to show in the final thing

the fact that everyone seemed to be doing so good at their thing and they felt collectively creative made him assume the work was going to be good. the fact that management asked for a sequel right away he took as the confirmation. on the other hand, Loom, which was supposed to be a trilogy, didn't get a second entry and The Professor was too burned out to fight for one.

- 50 meg? what are we supposed to do with all of this space?
- it's the first time he sets up his own computer, and he is surprised to notice he doesn't need much help from those around him
- but the news wasn't the disk space, it was the VGA cards and monitors
- at first it seemed like his independence day, free at last from his 16 color jail
  every dithering stretch he could remember doing for /Loom/ and /Monkey Island/ would be unnecessary with this palette.  anything he may ever need seemed to be contained by these new 256 colors
  as was often the case when he is in between projects, he is free to spend his time however he sees fit.
  he decides to work on a new take of his legendary sunset landscape, to test drive the new palette. it would be a good way to try the DPaint gradients that were useless on VGA.
but this little project would reveal a new form of anxiety: he doesn't know what he's doing anymore.

<the engine was at its best
the background art and animation they produced was the best in the industry
<after having free reign to experiment in /Loom/, Mark felt like he mastered his materials,
he knew its limitations and where there was room for letting his creativity flow

<loom received praise was considered too /avant garde/. nobody asked the professor for the sequels he had planned, and he was too burned out to fight for them

Competent, boring specialist. And they got back the license for /Start Wars/. Most people were thrilled, but <Mark received the news as a death sentence.>

- receives a memo about the rebrand
- maybe
- the mail also mentions something everybody knows about, like there was a "writing on the wall"/sword of Damocles hanging over their heads: the star wars embargo lift. most people loved star wars and couldn't be more excited about getting their hands on their property for a videogame. mark also loved the movie, but he struggled not to see that date as a death sentence for the creativity of the studio

  - but now it meant that a lot of he had to learn, a lot of the craft he acquired, was now irrelevant
<I don't know. I already learned how to do the mouse thing, this sounds like <back to square one>. Just another mediocre illustrator. Not <particularly young or productive>

<People said Monkey marked a new beginning for LucasFilm games, but to Mark it felt more like a culmination of the process they started four or five years before. The tools were at their best and for the first time everybody, the designers and the artists, seemed to know exactly what they were doing. Mark is still no gamer, he doesn't play any of their games, he has no way of telling whether they turn out good. But they had such a good time working on this one that it doesn't come as a surprise to him when the executives order a sequel, the first one in the Group's history.

his is still boxed in his desk? he didn't have the time to set it up and he wasn't going to use it for monkey anyway
at leas that was the thought. mark feared he'd be lost choosing between 256 colors
His palette choices aren't as relevant anymore, his scene planning <turns into> paralysis, he has to rethink his whole process.

- he could see some of the new folks, don't even remember their names (I'm standing right here you know? it's Gene), working on VGA ports for their old games, some butchering ("enhancing" his loom and monkey island backgrounds.
  - the results were more colorful, yes, but also less vivid, they lacked the personal style, the touch of the artist, that was lost in translation.
  - each pixel on his dithered patterns was loaded with his intent, now dpaint did most of the thinking through a generic color gradient

    he knows it doesn't get better than making adventure games at Skywalker Ranch, he won't get this thrill anywhere else, much less as a freelance artist, but he won't get it by staying, either, LucasFilm is gone, replaced by LucasArts

    such a typical corporate move, rebranding to LucasArts just as they move them into an insurance office building full of cubicles, a bunch of boring technicians churning out Star Wars flight simulators
no more rebels, just stormtroopers
no more lucky breaks.

Memo: /Our new Home!/

he'll start with the landing site
the c64 version is so brown and plain, it looks like clay pyramids and mud lake
he was less tied by the old backgrounds here, and less tied by reality
for the first time he could connect with the fantasy and scifi work were he was most comfortable with

Before his work was derived from the c64 originals, largely limited to delineating shapes and picking a few colors to fill them.

He keeps the experiment to himself. He doesn't want Gary or the programmers see it before it's ready; he wants it to catch them off-guard. When it's done, Mark saves it to a floppy disk, goes over to Ron's desk, and hands it to him.


<in parallel with loom, sounded like they were getting bigger. and Mark's dithered backgrounds would feature in both
<Ron and Brian both had the player in mind, but they couldn't be more different in how they were approaching their games
<ron popcorn + game design
<brian fantasy + story telling
<They were comic books to infocom's novels.
<despite marketing desperation to sell them as interactive movies

He is suspicious of IP games.
