---
title: A Pixel Parable
date: 2024-09-22 17:52:07
layout: post
lang: en
tags: [videogames, software, fiction]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

#+begin_verse
Already the displacement
of one's thought-child
is not only conceived
but scheduled
#+end_verse

#+begin_export html
<br/><br/>
#+end_export

"How would you like working as a video game artist?"

Mark is holding his "Best of the Show" certificate on one hand and the guy's card in the other. /Gary Winnick - Art Director - LucasFilm Games/. LucasFilm as in George Lucas. As in Star Wars.

"Could you come over to the Ranch for an interview?", he insists.

This is his second lucky break of the weekend. Mark is just out of art school, trying to make it as an illustrator. A friend recommended he show up to this sci-fi convention, he said these things are good for networking. Mark wouldn't mind having some of his work on a trading card, or a rule book, or, who knows? on the cover of one of those fantasy novels he used to read growing up.

So he shows up to the convention on Friday, someone notices his work---these pencil-drawn landscapes that look like they were hand-painted---, they invite him to participate in the convention's art show, he does, two days later he wins best of the show. That was his first lucky break that weekend; the second was this guy, Gary, coming over to him, handing him a card, asking him to 'audition' for a video game job.

Mark reads the card again, stops for a second to think what to say next. He needs a job, after all. Honesty has been working wonders for him this weekend, so he tells it straight:

"I'd be happy to come over to do <anything at all there> but... I don't know the first thing about video games. I never even touched a computer."

"That's alright", Gary replies, "we've had better results teaching artists how to program than programmers how to art. I'm not worried about that part."

The last two hours of the convention are a blur. He drives back home, trying to figure out what just happened. <On his first weekend, on this first try as a professional illustrator, he's offered to interview for a job that he didn't even know existed five minutes ago, but that he now thinks it's indisputably his dream job---and one that he's terribly underqualified for.

Mark calls his parents to share the news. His father, he now learns---and this was the third and final lucky break of the weekend---has just bought a personal computer.

#+begin_export html
<br/><br/>
#+end_export

"What are you doing with this thing, anyway?", asks Mark. His sitting in front of the computer, skimming the manual. The cover reads /Atari 520ST/.
"The school made a deal for us to get them at half price. They say we should be computer-literate if we want to have a job in five years." The voice comes into the room before the rest of his father, who then appears at the doorway, leaning on the frame. "I figured I could use it for writing, but they have a different brand at school, so I can't print my files. And I'm not buying a printer. You can take it if you want."

"Let's see if I get the job, first. It says there should be a drawing program somewhere in here, 'NeoChrome'. Let's try that out." It takes them 20 minutes of collaborative effort---something they haven't done since his father thought him to change the oil of the car a decade ago---to find the disk and open the program. Then Mark drops the computer manual and switches to the NeoChrome one. Another half hour later, Mark is dropping little green dots across a blue background.

Mark secludes himself in his old high school bedroom for the next few evenings, getting familiar with this computer thing and the paint program. The little mouse forces his hand into a claw. Whenever he begins to feel that he's gotten used to it, that he can forget about the tool and focus on the task, whenever his eyes seem to spark a connection between the image on the screen and the image on his brain, his hand jumps from the mouse to grip a pencil that's not there, like a phantom limb.

He teaches himself to draw a single picture, a little African hut that he repeats over and over until he memorizes the procedure, which he will repeat a few days later to survive his interview.

#+begin_export html
<br/><br/>
#+end_export


<title: digital background artist
the same gary winnick shows him around, helps him setup his computer, deluxe paint and maniac mansion
for a couple of days they just let him play the maniac mansion game, to get a feel of the kind of thing they are trying to build
<imposter syndrome, everybody knows he's not a computer person, but also everybody is trying to figure out what it means to tell a story in this medium, in this genre, no one is an expert in that. and they value his artistic point of view

<drives out of the underground garage
<what car?
place that looks as otherworldly as one of his fantasy landscapes, as a shot from Star Wars or a scene from that adventure game the company has just published.
<a <valley>, a lake, green hills, this old victorian house, with a theater and a huge library with a spiral staircase
<cattle, farm animals
he will be driving in this underground garage for the next three years, but he'll make a point of never taking this for granted, no matter how shitty the job gets

#+begin_export html
<br/><br/>
#+end_export

ironically, lucasfilm games didn't have the license to make star wars games. there were some /Indiana Jones/ projects on the works, but the games division were expected to come up with original ideas for the games. this was both a blessing and a curse, as he'd learn.

david lynch screening at the art deco theater of the main house
<same room but worlds apart
they don't seem much of the big guy, they may catch a glimpse of him at lunch, or when browsing the library, as he climbs the spiral staircase up to his office in the roof---which is off-limits.

truth is Lucas doesn't care for video games, the existence of the division a sort of accident from a different era of the company, his survival now <off of his hands.
this group of people, mostly computer hackers, had nothing to do with film making---any possible connection disappeared when pixar was sold to steve jobs---, and an <unstated rule> was to be as invisible as possible to lucas, not to tempt them to get rid of the division
a kind o intruders

<to make up for his absence, the executives throw around the single piece of advice they managed to get from the owner: “Stay small, be the best, don’t lose any money.”

#+begin_export html
<br/><br/>
#+end_export

<he joins a team working on the enhanced version of zak mackraken
<typically needs to just port a scene from the c64 version to ega dos

# FIXME this bit about freedom doesn't really apply to this game, should be moved to loom
The programmers don't seem to care that he's a computer and video game neophyte. They invite him to join the brainstorming sessions, they ask for his input on design decisions, his water cooler jokes make it to the dialog of the game. They give him freedom to figure out the game backgrounds, handing him a short list of requirements for each one---items and doors that will be necessary for the gameplay of the scene, what they call /hotspots/---and as long as he meets them he can do whatever he wants.

it doesn't take him too long to become productive. that is, to work out a usable background fast enough to meet the developers expectations, which were lower than his own.
his goal was to produce art and get paid for it, so he give as little thought as possible to the needs of the project and the business.
it's convenient that they don't expect much from him, because not only he isn't satisfied with his production and it doesn't come close to art, he still feels he has a long way to go to tame the computer, the mouse, the pixels, the palette, and the drawing program.
<at first he tried just working out from the c64, but soon finds out that creates more problems than it solves, since the screen dimensions are different
he develops some 'coping mechanisms': he first makes sketches, plotting the pixel grid in a ruled notebook, to try options before moving to the computer screen where nothing seems to flow, where everything feels clumsy and rigid, like lego building, and it's hard to tell whether something's going to look good before it's done.

the most frustrating is encoding the pictures in those suffocating 16 colors, always the same palette for anything he may need to represent---black, dark gray, light gray, white, dark blue, light blue, cyan, yellow, mustard brown, dark red, poppy red, peach, magenta, acid-hot pink, grass green, and acid-chartreuse.
this is another thing where he needs to plan ahead, carefully measuring what colors he gets to spend, a decision he needs to make early on and that informs---constraints--- all the rest of his choices: the scene composition, the mood, what's shown, what's hinted.
<There's little room for the sort of creativity that stems from impulse and experimentation (but much from constraints, pushing the boundaries, happy accidents that lead to innovation
it gets better as /he/ gets better, more familiar with the tools; once he grasps what are his materials and what their capabilities and limitations, he can start using them to his advantage---work around and step on the constraints and push himself to be creative as with any art and any material, just like does with pencil and paper.

#+begin_export html
<br/><br/>
#+end_export

The mouse, the pixels, the 16-color palette, the hotspots, are the constraints he needs to work with and around. The programmers, too, with their arcane knowledge, can become another layer of constraints, a kind of the extension of the computers.
TODO: maybe use an example requirements for a particular zak scenario for this section. (that would require killing the paragraph above

One trick---a /hack/, as programmers would call it---he discovered early on was that if he formed a checkerboard pattern of pixel in his drawings, when he zoomed out the image pixels would blend and bleed in the screen, producing shades beyond the boring old 16 colors of the EGA palette.

This was one of those happy accidents, but since he found it he's been thinking how to use it to his advantage, and this background could be the perfect excuse.
<todo describe how he draws it, where he uses dither
<this was obviously not art, not yet, but it was better that anything he did before and anything he saw in the previous game; most importantly it was progress, it was a hint of path they could explore to get closer to his goal.
he sends it/takes it to the programmer, goes over to his desk to see their reaction and get some praise, we're taking the art on this game to a new level folks, he's expecting a pat on the back

the image loads up on the screen from top to bottom. ron takes a few seconds to look at it before speaking up

# FIXME dont throw dithering as it's an already known term

"what the hell man?"

"I... wait, what?"

"You dithered all over this thing, this won't compress." He speaks in his soothing monotone, which makes him all the more scary when the words imply he's not happy

"Dithered?"

"What's up", Gary joins them, sensing trouble. "Wow, neat <background>. Oh, wait, that won't compress. Yeah, you can't do that."

"What's compression, again?"

"Those little patterns there, you can't do that, that will take too much space."

Gary tries to be didactic in these situations, not to because he cares that Mark learns about the computer internals but because he wants to make sure Marks gets they have good reasons to clip his wings. Gary proceeds to explain that the image data is run through a compression algorithm so it takes up less storage in the disk. The idea is that instead of storing the colors pixel by pixel, they store how many times the current color needs to be repeated; the more same-color segments the image has, the fewer space it will take in disk. His little checkerboard technique---which they called /dithering/---completely breaks this idea, possibly making the compressed image take /even more/ space than the original. Dithered backgrounds would double or triple the required disk space, which would double the amount of disks required to ship the game, which would double production costs, which would double the game's price tag, which would surely get them all fired.

# FIXME: maybe too explanatory
Those damn computer. It's like they come with a set of unwritten instructions that everyone knows about but him. He's almost 6 months into the job and still can't tell when he's doing it right. How is he supposed to /be the best/ without /don't lose any money/ getting in the way?

"Try again with solid colors, please." Gary pats him on the back. "That was some background, though, huh?"


#+begin_export html
<br/><br/>
#+end_export

<veterans had warned him there was going to be crunch when they got closer to the
<here's the thing about deadlines: everybody knows we won't hit the first one or two deadlines, and that's ok, but everyone accept that you'll just crunch those final months
mark defaulted to a belligerent attitude towards authority and thus was, in principle, against overtime and having to meet executive demands and meet deadlines
but, also, he didn't really mind the effort.
he never once lost sight that
he was getting paid to be an artist---even though he didn't felt these computer drawings were there yet---
he was paid handsomely, more than every
he was having fun, he respected his teammates,
he was working at geek disneyland, having gourmet lunches across the room from leonard nimoy or the rolling stones

he was already used to working late, in the quite months they would take long lunches or hikes through the hills or they would toss a softball around in the field out back, so they ended up working late to make up for the time
most of the people on the team was in their early twenties so they didn't have anywhere better to be anyway

so as the project deadlines arrived, they just kept working late, only skipping the long breaks during the day.

weekends at the ranch, though, were off-limits. they would let him take his computer back home on fridays to work during the weekend
he figured his bodily reaction to screen time was somehow connected with sleep deprivation. at first, pulling 6 or 8 straight hours in front of the computer seemed to burn him out, but after 10 or 12 he didn't really cared, he just kept going until he literally felt asleep on the keyboard

during this periods he got used to taking breaks from the works without getting away from the computer. he always kept one or two personal illustrations on the side, where he <got off> from all the restrictions that the game backgrounds imposed on him
he would use dithering, and colors otherwise reserved for sprite characters, and unconventional image dimensions

protest dither image,
this was... art. and now hi was annoyed that he couldn't put stuff like this in the game. he set it as a screensaver in his computer to send a passive-aggressive message, a kind of protest---against no one in particular, no one in his team, anyway. Ge was protesting Turing and Von Neumann and George Lucas and Ronald Reagan, for making it so damn hard to make art for a living.

takes a long lunch, when he gets back to his desk the divsion director and gilbert are discussing, why exactly doesn't dither compress? can't we do anything about this? art like this in our games would be a game changer, the differential people came expect from our films, now in the computer.

# TODO: maybe some compression technical details

a few week later he was informed that dithering was now supported. he realizes the programmers too have their own set of constraints, their own challenging puzzles they need to resolve to get some creative output from these machines

the division head told him they would double down on dithering for the look and feel of the next game, that he would be lead artist for it. your <stock> just went up.


#+begin_export html
<br/><br/>
#+end_export

green light for indiana jones game

for all that Lucas didn't care for games, Spielberg was obsessed with them
and he took any chance he had when working in the Ranch to visit the office and see what the games folks where up to.
he said they were doing a kind of animated, interactive movies and that it was just a matter of time for our work to converge with his
game designers would get weekend calls for hints at tackling puzzles

everyone took for granted that he would eventually be involved to some capacity in one of the next games, likely an indiana jones, although not the /Last Crusade
it was a matter of time for spielberg to get involved in game, likely an Indiana Jones one
but not the one they were making now

mark was suspicious of IP games, he prefferred originals,
one thing were the constraints imposed by the tech, but ip games were like a huge requirements list handed by executives
it was obvious that once the star wars license embargo was lift off, it would take a hell of an effort to prevent the suits to send all hands to milk chewbacca

#+begin_export html
<br/><br/>
#+end_export

“Stay small, be the best, don’t lose any money.”

the only part of this that affected him, Mark thought, was /be the best/, and that was how he intended to operate anyway, he didn't need a manager to tell him. he left to the suits, though, to figure out how his work and that of his teammates was supposed to be connected to the money making.

he assumed things went well enough, as projects were still lined up, now they were doing two adventures in parallel
by all appearences they were getting bigger, new artists coming in, and mark had to help onboard them
they actually did two games in parallel now, and new people were coming in

it was a good thing that he didn't get assigned to this indy game.
they made him lead bg artist for another project, that would be all ferrari style, doubling down on his dithered style
other than compression, the scumm engine now could scale the character sprites to represent different distances, this meant that he could move away from the horizontal axis and add perspective to his scenes

# todo: read about loom
maybe: onboarding new artist scene?
still dont like computers but dpaint is his domain
wants to show how he does thing, but not be prescriptive, letting the artist figure out his own style

#+begin_export html
<br/><br/>
#+end_export

- announce lucas arts downgrade
- star wars embargo lift
- new computers, what will we do with all of this power?
- todo: lookup specs
- at first it felt like his independence day, finally free from that EGA cage.
  - but soon he felt he wasn't sure what he was doing anymore, the palette choices weren't as relevant anymore, so he had to rethink his whole process
  - these new computers were like a career reset for him
- he could see some of the new folks, don't even remember their names, working on VGA ports for their old games, some "upgrading" his loom and monkey island backgrounds.
  - the results were more colorful, yes, but also less vivid, they lacked the personal style, the touch of the artist, that was lost in translation.
  - each pixel on his dithered patterns was loaded with his intent, now dpaint did most of the thinking through a generic color gradient

    #+begin_export html
  <br/><br/>
  #+end_export

- for his first lucas arts game he got assigned a new Indiana Jones adventure
- the cool kids went on to work on the monkey island sequel
- now they were doing hand painted backgrounds, then scanned in photoshop on a Mac and moved to dpaint for cleaning up
  - it was funny that 5 years ago this would've made life much easier to old mark, it would kept most of his work in illustrator land and much less in computer land
  - but now it meant that a lot of he had to learn, a lot of the craft he acquired, was now irrelevant
  - he went from industry expert on to just another illustrator, not a particularly good, young or productive one .
  - the originals by peter chan were gorgeous but the results in the screen were filled with random noise, it would take time to figure out a polished look for the new technique
- discussed with someone
  - it finally felt like we got a hang of this thing in monkey island, that we could push it beyond its limits, but now is like we need to start over
  - "a technology is always at its best right before it's obsolete"
- that made total sense to him, he could easily see the pattern: they'll always be cornered by new developments, always chasing after the new hot thing
  - after scanners it would be compact discs or rgb color or those three dimentional things they were developing over at the ILM <basement/freezer?>
  - more colors, more space, more processing power but also more complexity, more time to get familiar and competent with the tool, let alone creative or innovative.
    - it would take them more time to find the boundaries of the tech and thus longer to squeeze some art out of them,
    - and they'll obviously lack that time, it won't be long before the next computer generation arrives

#+begin_export html
<br/><br/>
#+end_export

- last day at skywalker ranch packing his box into the car
- it was a typical corporate move to rebrand with "arts" in the name just as they move it out from the ranch to a <cubliced> office plan over at san raphael,
- they started bringing in more people, boring people, got read of the trouble makers, lined up a bunch of boring star wars action game projects

- starting as freelance career, as other folks do (purcell)
- he knew it didn't get better than making adventure games at skywalker ranch, that he wouldn't find what he had there anywhere else, much less as a freelance artist
- but he also knew he wouldn't get it here either, lucasfilm was gone, replaced by lucas arts, no more ranch, the magic/halcyon days were over / the dream/fantasy was over
- he ran out of lucky breaks
- drive out, evoke his first day

*** Sources (TODO: review)
- The Art of point & click
- mixnmojo #4 https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-4-Loom/5
- mixnmojo #5 https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-The-Secret-of-Monkey-Island/7
- The Making of Monkey Island - Behind The Scenes https://youtu.be/ri4_3P2Oh14?feature=shared
- The Effect of CRTs on Pixel Art https://datagubbe.se/crt/
- The tar pit
- Why A.I. Isn’t Going to Make Art https://www.newyorker.com/culture/the-weekend-essay/why-ai-isnt-going-to-make-art
- Day of the Tentacle Remastered (developer commentary)
- Lucasfilm EGA adventures https://www.superrune.com/tutorials/lucasfilm_ega.php
- https://mixnmojo.com/features/sitefeatures/Monkey-Island-From-EGA-to-VGA/
- https://scientificgamer.com/lucasarts-time-machine-the-secret-of-monkey-island/
- antiquarian
- https://web.archive.org/web/20030503162101fw_/http://lucasfans.mixnmojo.com/features/interview_stevepurcell_2.html
- https://www.arcadeattack.co.uk/brian-moriarty/
- https://grumpygamer.com/guybrush_fact_fiction

*** chunks

#+begin_quote
I feel the stage sets we rendered as best we could for those earlier games conveyed all sorts of personal artistic style and evocative atmosphere, while most of the 3d game environments that came after them seemed almost universally airless, lightless, and rendered in such a uniform 'algorithmic' art style.

I think we lost things---important things--- whenever accelerating technological fixes and agendas overtook, and to some extent eclipsed, human creative navigation and intent.
#+end_quote

*** research

**** TODO digital lucas arts 1, 2, 3
**** TODO digital loom
**** TODO digital monkey
**** TODO digital indiana
**** TODO research details about the ranch
eg landscape, garage. wikipedia mostly
**** TODO experiment with atari st + neochrome
**** TODO experiment with dpaint
**** TODO maybe too with c64? try c64 maniac mansion?
