---
title: A Pixel Parable
date: 2024-09-22 17:52:07
layout: post
lang: en
tags: [videogames, software, fiction]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

#+begin_verse
/An imagined town is at least as real
as an actual town./
#+end_verse

#+begin_export html
<br/><br/><br/><br/>
#+end_export

"How would you like working on video games?"

Mark is holding his "Best of the Show" certificate on one hand and, on the other, the card this guy just handed to him:
#+begin_export html
<div class="center-block">
<p>Gary W.</p>

<p><small>Art Director</small></p>
<br/>
<p><small>LucasFilm Games</small></p>
</div>
#+end_export

LucasFilm as in George Lucas. As in /Star Wars/.

This is his second lucky break of the weekend. A friend recommended he show up to this sci-fi convention, she said that these things were good for networking. He wouldn't mind having one of his illustrations on a trading card, or a rule book, or, who knows? on the cover of one of those fantasy novels he used to read in high school.

So he shows up to the convention on Friday. Someone notices his work---these pencil landscapes that look hand-painted---, they invite him to join in the art show, he does, two days later he wins  first place. That's his first lucky break. The second is this guy, Gary, coming over to him, handing him a card, asking him to 'audition' for a video game job.

"Could you come over to the Ranch for an interview?", Gary insists.

Mark reads the card again, stops for a second to think what to say next. He needs a job, after all. Honesty has been working wonders for him so far, so he tells it straight: "I'd be happy to come over to do anything at all there but... I don't know the first thing about video games. I never even touched a computer."

"That's alright", Gary replies, "we've had better results teaching artists how to program than programmers how to art. I'm not worried about that part."

He drives back home that night, trying to make sense of what just happened. On his first weekend---on his first serious attempt as a professional illustrator---he's offered to interview for a job that he didn't even know existed five minutes before, but that he now thinks is undoubtedly his dream job---and one that he's terribly unqualified for.

Mark calls his parents to share the news. His father, he now learns, has just bought a personal computer. That's his third lucky break.

#+begin_export html
<br/><br/>
#+end_export

"What are you doing with this thing, anyway?" Mark is sitting in front of the computer, skimming the manual. The cover reads /Atari 520ST/.
"The school made a deal for us to get them at half price. They say we should get /computer-literate/ if we want to have a job in five years." The voice comes through the doorway, then his father, leaning on the frame. "I figured I could use it for writing, but they have a different brand at school, so I can't print my files there. And I'm not buying a printer, so I don't see the point. You can have it if you want."

"Let's see if I get the job, first." Mark continues reading the manual. "It says here there's a drawing program in there, 'NeoChrome'. Let's try that out." It takes them about 20 minutes to find the floppy disk and open the program---their first project since his father thought him how to change his oil over a decade ago. Then Mark switches to the NeoChrome manual. Another half hour later, Mark is dropping little green dots over a blue background.

For the next few evenings, Mark secludes himself in his old high school bedroom, getting familiar with this computer thing and its painting program. The little mouse feels like a potato, forcing his hand into a claw. Whenever he begins to feel that he's got the hang of it, that he can forget about the tool and focus on the task, whenever his eyes spark a connection between the image on the screen and the image on his brain, his hand jerks to grab a pencil, his phantom limb.

He teaches himself to draw a single picture, a little African hut that he repeats over and over until he memorizes the procedure, which he will repeat a few days later to survive his interview.

#+begin_export html
<br/><br/>
#+end_export

Mark walks out of the garage and meets Gary at the porch. Gary shows him around the Stable House, introducing him to everyone in the Games Group, and takes him to his desk. He'll be sitting next to Gary and across the hall from Ron and David, the two programmers they'll be working more closely with. Mark notices there are not one but two different computers on his desk. And neither looks like the AtariST he's been using.

"That's a Commodore 64", points Gary, "and that's a DOS PC. We've been transitioning from c64 to DOS. In fact, your first job will be helping us to port the backgrounds of our new game. You'll notice these are, uh, a bit... clunky, when it comes to graphics. Especially that one", he points at the PC.

Mark feels like throwing up.

"I know, it's a lot", Gary laughs. "Look, the only thing you need to know about this one is how to run the game. And for this one... You'll mostly just be using DPaint".

Nobody around here really knows what they are doing, Gary reassures him, not even the programmers. They are all just trying to figure out what it means to tell a story in this new medium, in this new genre. What a video game worthy of LucasFilm should be like. There are no experts at /that/. "An artist perspective is what we expect you to bring to the table. The tools, you'll figure out. They change all the time, anyway".

They spend the next hour fiddling together with Deluxe Paint II, the drawing program for the PC. It's more or less the same as NeoChrome, but with more sophisticated brushes, or so Gary says. Mark notes the colors are fewer and uglier than the ones he saw in the Atari. "Oh yeah. Those are the colors of your nightmares, starting tonight".

After lunch, Ron sits with Mark to play /Maniac Mansion/, his B-horror adventure game. He shows Mark how to move around, how to talk with other characters, how to solve puzzles to make progress. /Maniac Mansion/ is a sort of blueprint of the kind of work they are trying to do. There's a newer game they've been working on, David's game, /Zak MacKracken/, but /Maniac Mansion/ is a gentler introduction. It's best if Mark just spends a couple of days playing it, to get the idea. Marks imposter syndrome kicks in now and again, and he apologizes for his dumb questions. He's no gamer, not even an arcade player. That's perfect, says Ron: they want to build something that just about anyone can pick up and have fun with.

He leaves the office with sore eyes from the computer screen and a headache from all the names and images shoved into his brain. He's relieved that no one's around to see him pull his Honda out of the underground garage. He slows down as he drives by the Main House, where they had lunch that day, a new building made to look old---not any old but period-specific old. He confirms that it looks just like the one they put in the game. He circles by the artificial lake and passes the barn, the corral, the vineyard. This little valley surrounded by green hills feels as otherworldly as one of his fantasy landscapes. Or a shot from /Star Wars/.

#+begin_export html
<br/><br/>
#+end_export

His first assignment is to port /Zak MacKracken/'s Commodore64 backgrounds to the EGA. David hands him a description of each location in the game. They call them /rooms/ even though some are outdoors---outer space, even. Each one has a short description and a list of "hotspots", the things the player can interact with: objects, doors, that kind of thing. Mark has to make sure that those remain visible on his ported backgrounds. Other than the list of rooms, the only design document is a huge puzzle chart posted on the wall, a sort of storyboard for programmers. Mark can't make sense of it, or the game, for that matter. /Zak MacKracken/ is bigger and more ambitious than /Maniac Mansion/; the work is more interesting, but the game is undecipherable to Mark.

At first, he tries working from the original c64 bit maps, but that complicates things.
Both are 16 color systems, but /not the same/ 16 colors, so swapping them is pixel Whac-A-Mole. He turns to redrawing the backgrounds from scratch. He sketches on his notebook to try options, he plots the pixel grid in graph paper and draws on acetate sheets that he then tapes to the monitor. He will try anything before moving to the computer, where nothing flows, where everything is clumsy and rigid as Lego building, and it's hard to tell whether something will work or even fit until it's almost done.

Black, dark gray, light gray, white, dark blue, light blue, cyan, yellow, mustard brown, dark red, poppy red, peach, magenta, acid-hot pink, grass green, and acid-chartreuse. Always the same suffocating 16 colors for anything he needs to draw. He has to ponder carefully what colors to "spend", an early decision that constraints the rest of his choices: the scene composition, the mood, what's shown, what's hinted. There's no room for impulse or experimentation, everything needs to be planned in advance. Despite his Digital Background Artist title, his job doesn't seem to be concerned at all with art. He's like the poet employed as copywriter. The only creativity is in subverting the tools, working against and around them, eventually leaning on their limitations.

#+begin_export html
<br/><br/>
#+end_export

# TODO maybe comment what they are having, some gourmet meal. osso buco with risotto

"Coppola", says David.

"Coppola, of course", Gary concurs. "The Rolling Stones".

"Wait, all of them?"

"Hmm. Mick Jagger. And the drummer, I guess."

"I missed them. I did see Huey Lewis."

"Yep. We played softball with the band."

It's Mark's third week, and it's the first time he catches a glimpse of George Lucas. They usually only see him at the restaurant when he has visits. Gary and David are listing all the famous people they saw at lunch. Today it's Spielberg.

"You'll understand, of course", David turns to Mark, "that while it may seem as if they were right there across the room, we are not breathing the same air. We're worlds apart."

"Galaxies", Gary suggests.

"Galaxies apart, thank you. They are holograms, like that Leia message on the first one. We can see them but they don't see us."

"Under no circumstances should we be noticed by Lucas or one of his guests, or any film-related people."

"And especially not Lucas."

The owner doesn't care at all for video games. The existence of the games division is a sort of corporate accident, a spin-off of the Graphics Group prompted by a failed collaboration with Atari, a product of another age of the company. And the fact that they got to stay while the Graphics Group---now called Pixar---was sold to Steve Jobs, is another corporate accident. They're a rounding error, the last hackers standing, the only division totally unrelated to film making. A kind of intruders. So the idea is to make themselves invisible, not to remind George Lucas that they exist, that he still owns a little video game studio, that they are spending his money and---much worse---taking up his precious space.

"Our man Steve, on the other hand, is our biggest fan", David points his fork to Spielberg. "You'll be seeing a lot of him."

"This is like an amusement park to him. He's more into it than Lucas, I think."

"He'd probably live here if he wasn't busy, you know, making blockbusters."

"Did you know he used to call Ron for /Maniac Mansion/ hints?"

"So yeah, I bet he'll get involved in one of the games sooner than later."

"An Indy game, most likely."

"When the tech is good enough."

"And when they get back the license."

"Right, when we get the license."

That part Mark already knows, he learned it on his first week: LucasFilm Games doesn't have the rights to make LucasFilm games. No /Indiana Jones/, no /Star Wars/. Some toy company holds the license.
They are expected to come up with original ideas for their games, which is both a blessing and a curse:
they have the creative freedom but they must live up to the Lucas standards without the easy cash of his IP.

#+begin_export html
<br/><br/>
#+end_export

The mouse, the pixels, the 16-color palette, the hotspots: those are the constraints he has to work with.
One trick he discovered early on---a /hack/, programmers would say---was that, if he arranged pixels to form a checkerboard pattern, they would blend and bleed as he zoomed out on the computer screen. Much like the eyes finish the job as one steps back from an impressionist painting, the monitor melts the pixel mosaic into something richer than whatever the dull EGA palette was supposedly able to project. At first this is just an accidental observation, he doesn't make much of it. It's only when he starts working on a new batch of /Zak/ backgrounds that he finds himself coming back to those mixed pixels.

This section of the game takes place in Mars, a location Mark finds very provocative.
Here he owes no loyalty to the muddy c64 backgrounds. The acid EGA palette seems strangely fitting. And he needs not abide reality here, he's safely into fantasy territory. He realizes he can weaponize the pixel blending artifact and turn this one of his classic sci-fi landscapes.


He settles quickly on a composition, a rocky horizon inspired by the Grand Canyon, sitting on top of a fiery desert and a pale sun, slightly displaced from the center of the screen. It's the palette that gives him more work, hours of trial-and-error to find the right color combinations and the right density of interleaved pixels for each figure, each boundary.
He wants the image to jump out of the screen; he wants the sky, and the sun, and the ground to bleed into each other distinctly---the sun to set the sky on fire and the earth to bed the ashes.

It's not the original c64 background, nor the EGA palette, nor the hotspots list what mandate his work. It's not what he pictured in his head. It's the braid: each pixel born out of its predecessor, each one birthing the next. They boil with possibility, they serve no purpose but to carry intent.

For the first time, he doesn't feel constrained by the material. He's so free that the work becomes free, the work now takes life and talks back. He tamed the material into rebelling and becoming something other than what he set out to produce, something better than what he could have imagined. It's then, when the work speaks for itself, that he knows. This may not be art, not yet, but it's better than anything he did and anything he's seen on a computer screen. There's the spark. This is the direction, that's where he needs to go.

#+begin_export html
<br/><br/>
#+end_export


Ron sticks the floppy in his computer and loads the image. He waits for the fringes to cover the screen and gives it a couple more seconds before speaking up.

"What the hell, man?"

"I... wait, what?" says Mark.

"The pixels here look all... dithered. This won't compress." Ron speaks in his soothing monotone, which makes it all the more scary when the words imply he's not happy.

"Dithered?"

"What's up?” Gary joins them. "Wow, that's a neat background. Oh, wait, that won't compress. Yeah, you can't do that."

"Compress?"

"Those little patterns there, you can't do that, that will take too much space."

He's been doing this for months and still can't tell when it's right. It's like computers have a bunch of rules that everyone but him knows about. And the programmers, too, come with their own rules, they are another kind of machine that he needs to poke about until something works.

In these situations, Gary gets into the little technical details, not because he cares that Mark understands them but because he wants Mark to know they have important reasons to clip his wings: the image data is run through a compression algorithm so it takes up less storage in the disk. Instead of storing the colors pixel by pixel, they store how many times the current color needs to be repeated; the more same-color segments the image has, the fewer space it will take on disk. His little checkerboard technique---his color "dithering"---completely breaks the process, changing colors at every step, never repeating, making the compressed image take /even more/ space than the source. Dithered backgrounds would double or triple the required disk space, which would double the amount of disks required to ship the game, which would double production costs, which would double the game's price tag, which would surely get them all fired. "Try again with solid colors, please,” he concludes, and pats him on the back. "That was some landscape, though, huh?"


#+begin_export html
<br/><br/>
#+end_export

His bodily reaction to screen time is somehow connected with sleep deprivation. At first, pulling 6 or 8 straight hours in front of the computer seemed to burn him out, but after 10 or 12 he doesn't really care, he just keeps going until he passes out on the keyboard.

<everyone warned him there was going to be crunch time when they got closer to the release date
<Here's the thing about deadlines: everybody knows they won't make the first one or two deadlines, and that's fine, but also everyone accepts that they'll miss them in crunch mode, if anything to keep up appearences
mark defaulted to a belligerent attitude towards authority and thus was, in principle, against overtime and having to meet executive demands and meet deadlines
but, also, he didn't really mind the effort.
he never once lost sight that
he was getting paid to be an artist---even though he didn't felt these computer drawings were there yet---
he was paid handsomely, more than every other job he ever had (more than both of his parents combined)
he was having fun, he respected his teammates,
he was working at geek disneyland,
<most people would continue to show up every day even if they cut their pay checks

he was already used to working late, in the quite months they would take long lunches or hikes through the hills or they would toss a softball around in the field out back, so they ended up working late to make up for the time
most of the people on the team was in their early twenties so they didn't have anywhere better to be anyway

so as the project deadlines arrived, they just kept working late, only skipping the long breaks during the day.

weekends at the ranch, though, were off-limits. they would let him take his computer back home on fridays to work during the weekend

during this periods he got used to taking breaks from the works without getting away from the computer. he always kept one or two personal illustrations on the side, where he <got off> from all the restrictions that the game backgrounds imposed on him
he would use dithering, and colors otherwise reserved for sprite characters, and unconventional image dimensions

if they tell him that dithering is off-limits, then he'll put in as much dithering in his personal work as he can.
what's a good excuse to do this a lot? what type of background would call for a gradient of as many colors as one can think of? A sunset.
<starry night?
# I sat down one morning and rendered a twilight scene with a rising moon and stars over receding oak covered Hills all rendered smoothly and subtly and dithered EGA graphics then in silent protest I simply left a picture up on my monitor
# twilit moonrise

# FIXME maybe too much stress in the martian background that should be here instead
# consider at least calling it back

this was... art. and now he was annoyed that he couldn't put stuff like this in the game. he set it as a screensaver in his computer to send a passive-aggressive message, a kind of protest---against no one in particular, no one in his team, anyway. Ge was protesting Turing and Von Neumann and George Lucas and Ronald Reagan, for making it so damn hard to make art for a living.

takes a long lunch, when he gets back to his desk the divsion director and gilbert are discussing, why exactly doesn't dither compress? can't we do anything about this? art like this in our games would be a game changer, the differential people came expect from our films, now in the computer.

a few weeks later he was informed that dithering was now supported. he realizes the programmers too have their own set of constraints, their own challenging puzzles they need to resolve to get some creative output from these machines

the division head told him they would double down on dithering for the look and feel of the next game, that he would be lead artist for it. your <stock> just went up.

#+begin_export html
<br/><br/>
#+end_export

"Imagine that you can get off the boat and wander around, learn more about the characters, and find a way onto those ships." This is how Ron explains his pirate game to anyone that will listen.
He wants to do something fantasy-like without doing fantasy, which he hates. So he's doing a spoof of the Disney ride.  "You'll inhabit this swashbuckling world, talk to other pirates, sail with them, instead of just watching. That right there is why we make adventure games: to give the player the leading part."

Ron may be a programmer by trade, he may be a decent writer, but game design is /his thing./ And he wants this game to be the ultimate realization of his design philosophy, what he's been preaching ever since /Maniac Mansion/. He even published it in a manifesto that became required reading around the office. /Why Adventure Games Suck/. It was mostly around game play, Mark couldn't make much of it, but one stick stuck with him: Ron wrote that the game should reward players for their accomplishments and in graphic adventures the reward is always a new piece of artwork, a new location they get to explore. That's how Mark realized than his work is more than just a backdrop, more than content to fill the screen.

#+begin_export html
<br/><br/>
#+end_export

The Main House is a ten-minute walk from the Stable House. Mark mentioned he would go over to the library and Purcell tagged along. Nobody passes on an excuse to visit the Main House.

"What are we researching?", he asks as they leave the porch.

"I want to look up some material for /Loom/. Some of that /Sleeping Beauty/ stuff he mentioned."

"Oh, so it's /actual/ research." People in the Games Group use /research/ as keyword for anything that blatantly isn't work. They ask /What are you researching/ to anyone they catch fooling around the office. "Well, I guess I can use some reference material myself".

Mark was assigned as Lead Background Artist for /Loom/. Purcell will do animations. It's his first video game project. They are supposed to figure out how to turn an EGA adventure into a "living tapestry", like Eyvind Earle did with /The Sleeping Beauty/.

"So what do you make of The Professor?" asks Purcell. Professor is what they've been calling the project lead. They just brought him from Infocom, the struggling text adventure shop.

"He seems cool."

"Very cool."

"He certainly knows his game design."

"Oh, yeah."

"Maybe he's a bit too...”

"Professorial?"

"...well, I don't want to say /ambitious/, because", Mark waves at the house, they are walking past the Solarium, over the right wing of the House, "who isn't around here?"

"He better be. /Be the best/, right?"

"...but, perhaps too much of an idealist. I can't believe /I'm/ saying this." In a sense, The Professor is like him: they take their work very seriously, they are both driven by a desire to produce art. But Mark knows all too well that, despite his title, he isn't paid to make art. They pay him to produce backgrounds, conforming to a set of specifications. The art, he has to smuggle, in spite of the business. The Professor, on the other hand, seems committed to breaking new artistic ground, and operates as if everyone else shares his vision. Mark couldn't imagine any other company where they would give such a guy /carte blanche/ to make whatever game he wanted.

# TODO lookup infocom descriptions, maybe one from a moriarty game
# FIXME should the IF spoof be it's own section? it's kind of weird in the middle of this one without a break
<They are standing in the hall of the Main House, <DESCRIBE ARCHITECTURE>. The east corridor leads to the solarium. To west corridor, leads to the restaurant. To the north is a large wooden door and, on each side, a staircase. <There's a stormtrooper here.> <There's a crystal display case with a Yoda model in it here.> They go north.

"I mean, a fantasy game?" Purcell continues as they enter the Library, "/The Sleeping Beauty/? Tchaikovsky? Doesn't sound very LucasFilm to me."

"I like a good fantasy", says Mark.

"More /Lord of the Rings/ than /Star Wars/. Or /Indiana Jones./"

"But, does it sound like /Maniac Mansion/ or /Zak MacKracken/. That's the real question."

"...or /Sam & Max/."

"Or /Sam & Max/, sure,” Mark concedes. Purcell is on a mission to convince everyone there /could be/ a game based on his comic. If he plants the idea on enough heads, someone will eventually ask him to make one.

"Well, I'd say it sounds like /Zork/, obviously... and /King's Quest/?"

"Ouch."

"Well, what do I know?” says Purcell, "I haven't played any of them."

"Me neither."

There's a counter at the entry of the library. <TODO describe: spiral staircase leading to the 2nd story and to Luca's office, stain glass dome

They need to register before going in. The librarian asks them what's the purpose of their visit.

"We're looking for research material for /Loom/,” says Mark.

"He's looking for research material for /Loom/. I'm looking for research material for /Sam & Max/.”


#+begin_export html
<br/><br/>
#+end_export

The memo supplied two separate but related pieces of news: LucasFilm secured the rights to make /Indiana Jones/ video games; they have six months to come up with a game based on the new entry Spielberg is shooting.

Management assembles a team with their most experienced designers to lead the project, they pause development on /Monkey Island/ and /Loom/. This is supposed to be a quick and dirty one, no room for Mark's precious imagery and experimentation. He is relieved, if a little worried, that they let him continue his work on /Loom/ while most of his colleagues to switch to /Indiana Jones and the Last Crusade/.

The team gets a copy of the script and some early footage to go on. The designers struggle to make the game fit the script and still be playable and fun. They aren't sure how to keep it interesting to the majority of players that will already be familiar with the plot. Artists are similarly constrained by the footage and the production stills. Some of the folks even get to visit the set. Purcell comes back with a whip for "research purposes", which he incorporates to their afternoon sporting events. Someone borrows the Holy Grail and they take pictures drinking coffee from it.

When Spielberg is done editing at the Ranch, they do a screening on the Art deco theater on the Main House.
The Games Group people walk back to the Stable House, excited about the film, discussing the scenes that Spielberg cut but that's too late to remove from the game. Mark loved the movie but feels uneasy about the game. It feels rushed and derivative, all about the money. The writing is on the wall. Once they lift the /Star Wars/ embargo, it's going to take a hell of an effort to prevent the suits from putting all hands on deck to milk Chewbacca.

#+begin_export html
<br/><br/>
#+end_export

Some times The Professor gives Mark and Purcell story prompts and asks for concept art in return, but more often than not he wants /them/ to come up with stuff he can use for inspiration, based on the reference material and a short treatment document he handed to them. This concept art is Mark's first illustration job since he joined the company, two years ago.

He pulled everything he could get from the library on Disney, /The Sleeping Beauty/, Eyvind Earl, and medieval tapestries. He would play the movie on the Media Room, frame-freezing to take notes and make sketches. Mark delivers two or three drawings a week, using his now legendary pencil technique. Most of the times, The Professor comes back with notes to refine an idea, or a request to try again, but occasionally he takes a drawing and uses it to write a segment of the story. In those cases The Professor asks Mark to convert his illustration into an EGA background, one he can wire it up in SCUMM to start experimenting with descriptions and dialog.

The Professor set up similar work streams for animation and programming and, most importantly, with the sound department. Music and sound will feature in /Loom/ more prominently than in any other LucasFilm game.
Which is convenient, considering that the Ranch houses the best sound engineering facilities in the world.
For the sound engineers, it's Tchaikovsky instead of Eyvind Earl.

The Professor sees games as a novel art medium, and he wants to use all of its materials to that end: sound, music, backgrounds, animation, story, and dialog. He made sure everyone on the team picked up on his vision and gave them freedom to figure out how to realize it with their tools.
Coming from a rather lonely experience writing text adventures, he's betting on collaboration to flourish to unlock this deeper storytelling experience. His so into this craftsmanship ideal that he put it into the story, with the protagonist visiting different Guilds over the course of the game.

Mark came up with the idea of using colors scheme to represent each Guild, giving a distinct quality to each section of the game: the striking emerald of the Guild of Glassmakers, the softer pastoral greens of the Guild of Shepherds, the Stygian reds of the Guild of Blacksmiths and the saturated blues and purples of the Guild of Weavers. This is a feat he imposes to himself, with the EGA colors allowing for one or two shades of each color, the rest having to be mocked with his palette tricks.

The latest version of the SCUMM engine not only supports Mark's dithered backgrounds, but introduced character scaling to represent depth, allowing him to move away from the horizontal axis and add perspective to his scenes. For the first time he won't be adapting someone else's work. He knows his tools and is free to push them in whatever direction he envisions.

#+begin_export html
<br/><br/>
#+end_export

The memo sits on his desk:

#+begin_export html
<div class="center-block">
<p>The Return of the License</p>
<p><small>LucasArts Episode I</small></p>
</div>
#+end_export

He doesn't read it.

#+begin_export html
<br/><br/>
#+end_export

# TODO maybe describe the room? or the demonstration itself?
The artists are gathered at the Technical Building for a demonstration. The scanner is a little tray, like a Xerox machine, minus the printer. It's connected to a Macintosh computer. The scanner costs 10 times the computer, the speaker said.

"This new guy, Peter, is scanning for his /Monkey 2/ backgrounds,” says Purcell.

"Really?"

There was a lot of movement around the office during those final /Monkey Island/ weeks. Mark was just too deep in crunch mode to notice. They seem to be growing faster, one or two new employees starting every week. They will are starting a magazine. They interviewed Ron for the first issue, and asked Purcell for one of his comics. Everyone's got new PCs, too, with VGA cards and monitors. /Monkey Island/ is getting a sequel, and Mark isn't in it.

"The art is gorgeous, but it comes out all fuzzy on the other side of /that/." Purcell points to the scanner. "He has to go back and clean everything up in DPaint."

"He might as well do the whole thing in the computer, no?" says Mark.

"He's no fan of the mouse, though."

"Who is?", Mark snorts. "It's funny, I would've loved this a couple of years ago. My life would've been much easier."

"Yeah."

"Now it feels like a downgrade, you know? It's like with these VGA ports they are doing now."

"The 'enhanced' versions."

"The 'butchered' versions. They just use gradients for everything. It's like they want DPaint to do all the thinking for them."

"We're right here, you know?" someone mumbles at the back.

Mark continues: "It felt like we were finally getting the hang of this, during /Monkey Island/. Now it's like starting all over." People say that /Monkey Island/ is new beginning for LucasFilm Games, but to Mark it feels more like a culmination of the process they started four, five years ago. The tools were at their best and for the first time everybody, the designers and the artists, seemed to know exactly what they were doing.

"A technology is always at its best right before it's obsolete, man", says Purcell.

"Who said that?" asks Mark.

"One Purcell."

"Smart fella."

He can already see it: after VGA and scanners it will be compact discs, or RGB color, or those 3D models they've been using over at the ILM basement. More colors, more space, more processing power, but also more complications, more time to master the tools. Forget about creativity or innovation, squeezing any art out of the machines. They'll be struggling just to stay competent. Before they know it, they'll be starting over with the hot new thing.

#+begin_export html
<br/><br/>
#+end_export

Mark walks towards the door, then turns. "I can't leave yet, I haven't finished packing". He looks at his desk. "I should put all this stuff in the box".

A pile of sketchbooks. "They are labeled by month and year".

A worn out DPaint 2 manual. "I haven't used this in ages. I could write one myself by now."

A set of colored pencils. "I hand picked them myself, one for each of the 16 EGA colors. I guess won't be needing these anymore".

An issue of /Sam & Max/. "My favorite."

An Indiana Jones action figure. "Indy."

A /Sleeping Beauty/ reference book. "I never bothered to return this to the main house."

A Chewbacca action figure. "Chewie."

A signed /Loom/ box. "It's signed by The Professor. I signed another one for him."

He picks up the box. "This box is too full, I can't carry it like this." He puts it back. He walks towards the door, then turns. "I can't leave yet, I haven't finished packing". He looks at the desk. "Neat". He looks at the desk drawer. "It's a desk drawer". He opens the desk drawer. "There's a piece of rope here". He picks up the piece of rope. "This might come in handy". He uses the piece of rope on the box. "Much better". He picks up the box. He walks out.

#+begin_export html
<br/><br/>
#+end_export

The Honda Civic drives out of the underground garage and turns around the Stable House. Lake Ewok is glowing with the reflection of the sky, like a dithered EGA sunset. The car passes by the barn and the corral, then drives away from the security kiosk and onto the main road.

A tall tree goes by, followed by two short ones. Then two short trees go by, followed by a tall one. Then there are no more trees. The hills give way into a plain, Californian unlikely, the Honda moving in front of the darker blue sky, now tallest and deprived of any texture.

The road proceeds, then ends abruptly, an abandoned flooring job. The car rides on over generic green grass for a while, then reaches an edge and moves out of the picture. But not all of it. I can still make the trunk and the bumper, and a corner of a tire, sitting there, stationary.


#+begin_export html
<br/><br/><br/>
#+end_export

*** Sources
- [[https://www.bitmapbooks.com/en-ar/products/the-art-of-point-click-adventure-games][The Art of Point-and-Click Adventure Games]].
- [[https://www.youtube.com/watch?v=z1aVDael-KM][Classic Game Postmortem: LucasFilm Games' Loom]].
- [[https://www.filfre.net/2015/07/a-new-force-in-games-part-3-scumm/][A New Force in Games, Part 3: SCUMM]].
- [[https://www.filfre.net/2017/02/loom-or-how-brian-moriarty-proved-that-less-is-sometimes-more/][Loom (or, how Brian Moriarty Proved That Less is Sometimes More)]].
- [[https://www.filfre.net/2017/03/monkey-island-or-how-ron-gilbert-made-an-adventure-game-that-didnt-suck/][Monkey Island (or, How Ron Gilbert Made an Adventure Game That Didn’t Suck)]].
- [[https://www.filfre.net/2018/09/indiana-jones-and-the-fate-of-atlantis-or-of-movies-and-games-and-whether-the-twain-shall-meet/][Indiana Jones and the Fate of Atlantis (or, Of Movies and Games and Whether the Twain Shall Meet)]].
- [[https://bossfightbooks.com/products/day-of-the-tentacle-by-bob-mackey][Day of the Tentacle: An Oral History]].
- [[https://youtu.be/ri4_3P2Oh14?feature=shared][The Making of Monkey Island - Behind The Scenes]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-4-Loom/5][LucasArts' Secret History #4: Loom Developer Reflections]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-The-Secret-of-Monkey-Island/7][LucasArts' Secret History #5: The Secret of Monkey Island Developer Reflections]].
- [[https://scummbar.com/resources/articles/index.php?newssniffer=readarticle&article=1033][The Secret of Creating Monkey Island]].
- [[https://datagubbe.se/crt/][The Effect of CRTs on Pixel Art]].
- [[https://www.superrune.com/tutorials/lucasfilm_ega.php][Lucasfilm EGA adventures: an appreciation]].
- [[https://web.archive.org/web/20030326051107fw_/http://lucasfans.mixnmojo.com/features/interview_stevepurcell.html][Steve Purcell Interview]].

*** quotes                                                         :noexport:

#+begin_quote
hiking up to the observatory after a long day at the office to do another sort of stargazing
#+end_quote

#+begin_quote
The Skywalker Ranch Research Library is not your typical library. Yes, it is filled with books, but also much more than that. It houses an impressive collection of research materials curated specifically to assist in the filmmaking process.

In addition to books, the Library contains documents, photographs, props, and other items that have been used in the development of Skywalker Sound projects.
#+end_quote

#+begin_quote
contains an impressive collection of Art Nouveau furniture and fixtures. There are Tiffany lamps and original paintings by Norman Rockwell and Thomas Hart Benton. Under a stained glass skylight sit shelves of books relating to all aspects of film production. In addition to their own impressive collection, their holdings also include the Paramount Research Library and the Universal Research Library collections.
#+end_quote

#+begin_quote
And to me, the shining star, the Lucas research library -a two story open atrium with books on every topic any writer, artist or musician could need to conceptualize a story. Ladders around the perimeter, a huge fireplace, and lush leather chairs and couches. On walking in, all I could think was something in my life has gone very right to have found that place - and something gone very wrong that I wasn't spending every day there.
#+end_quote

#+begin_quote
The team of stained glass artisans took six months to build the 19-foot dome. It was comprised of 400 sheets of glass, finely sculpted into 49 separate panels.

With the dome installed, the library took on a new look. The warm redwood and sensuous curves and details were continuously bathed in the amber light from the dome. Books from Hollywood studios’ abandoned research libraries were purchased and began to fill the shelves. The spiral staircase led to the upper balcony with a door into George’s inner office. This was his library.
#+end_quote

*** tasks                                                          :noexport:

**** TODO flesh out library description
**** TODO flesh out adventure segment
**** TODO wrap up crunch scene
**** TODO cleanup chunks
**** TODO flesh out remaining placeholders
**** TODO review remaining TODOs and FIXMEs
**** TODO cleanup quoutes

*** chunks                                                         :noexport:
https://i.pinimg.com/originals/53/b1/f1/53b1f1a0961866d25ed578d345945dd4.jpg

http://iveneverdonethat.com/blog_files/skywalkerranch.html

<The one time Lucas showed his face in the Stable House, he said to the director: “Stay small, be the best, don’t lose any money.” That became their gospel, an easy way to answer the question /what would George want us to do?/,an easy way to settle arguments and make design decisions---and an evergreen source of jokes.
<the only part of this that affected him, Mark thought, was /be the best/, and that was how he intended to operate anyway, he didn't need a manager to tell him. he left to the suits, though, to figure out how his work and that of his teammates was supposed to be connected to the money making.

Mark had tried one of their games. while he was impressed by the thorough descriptions and the setting---it was like they made him the protagonist of a fantasy novel---he was quickly frustrated by the complicated gameplay and all the typing it involved. It was like the complete opposite of everything Ron and Gary were trying to do with the graphic adventures. They were comic books to infocom's novels. <despite marketing desperation to sell them as interactive movies

<purcell joked that you would go blind if you stared at Mark's screen for too long

every dithering stretch he could remember doing for /Loom/ and /Monkey Island/ would be unnecessary with this palette.  anything he may ever need seemed to be contained by these new 256 colors
  as was often the case when he is in between projects, he is free to spend his time however he sees fit.
  he decides to work on a new take of his legendary sunset landscape, to test drive the new palette. it would be a good way to try the DPaint gradients that were useless on VGA.
but this little project would reveal a new form of anxiety: he doesn't know what he's doing anymore.

/Loom/ was praised but considered too /avant garde/. Nobody asked The Professor for the sequels he had planned, and he was too burned out to fight for them.

such a typical corporate move, rebranding to LucasArts just as they move them into an insurance office building full of cubicles, a bunch of boring technicians churning out Star Wars flight simulators
no more rebels, just stormtroopers

<at first it felt like an independence day to mark they would be free at last from their EGA jail
but now he wasn't sure how to adapt his work process to a 256 palette. it wasn't driven by the color planning anymore.
These new computers felt like a career reset to him.
