---
title: A Pixel Parable
date: 2024-09-22 17:52:07
layout: post
lang: en
tags: [videogames, software, fiction]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

#+begin_verse
Already the displacement
of one's thought-child
is not only conceived,
but scheduled.
#+end_verse

#+begin_export html
<br/><br/>
#+end_export

"How would you like working on video games?"

Mark is holding his "Best of the Show" certificate on one hand and, on the other, the card this guy just handed to him:
#+begin_export html
<div class="center-block">
<p>Gary W.</p>

<p><small>Art Director</small></p>
<br/>
<p><small>LucasFilm Games</small></p>
</div>
#+end_export

LucasFilm as in George Lucas. As in /Star Wars/.

This is his second lucky break of the weekend. A friend recommended he show up to this sci-fi convention, she said that these things were good for networking. He wouldn't mind having one of his illustrations on a trading card, or a rule book, or, who knows? on the cover of one of those fantasy novels he used to read growing up.

So he shows up to the convention on Friday. Someone notices his work---these pencil landscape drawings that look like hand-painted---, they invite him to participate in the convention's art show, he does, two days later he wins best of the show. That's his first lucky break. The second is this guy, Gary, coming over to him, handing him a card, asking him to 'audition' for a video game job.

"Could you come over to the Ranch for an interview?", Gary insists.

Mark reads the card again, stops for a second to think what to say next. He needs a job, after all. Honesty has been working wonders for him so far, so he tells it straight: "I'd be happy to come over to do anything at all there but... I don't know the first thing about video games. I never even touched a computer."

"That's alright", Gary replies, "we've had better results teaching artists how to program than programmers how to art. I'm not worried about that part."

He drives back home that night, trying to make sense of what just happened. On his first weekend---on his first serious attempt as a professional illustrator---he's offered to interview for a job that he didn't even know existed five minutes before, but that he now thinks it's undoubtedly his dream job---and one that he's terribly unqualified for.

Mark calls his parents to share the news. His father, he now learns, has just bought a personal computer. That's his third lucky break.

#+begin_export html
<br/><br/>
#+end_export

"What are you doing with this thing, anyway?", asks Mark. He is sitting in front of the computer, skimming the manual. The cover reads /Atari 520ST/.
"The school made a deal for us to get them at half price. They say we should get /computer-literate/ if we want to have a job in five years." The voice comes through the doorway, then his father, leaning on the frame. "I figured I could use it for writing, but they have a different brand at school, so I can't print my files there. And I'm not buying a printer, so I don't see the point. You can have it if you want."

"Let's see if I get the job, first." Mark continues reading the manual. "It says here there's a drawing program in there, 'NeoChrome'. Let's try it out." It takes them 20 minutes of effort to find the floppy disk and open the program---their first project since his father thought him how to change his oil over a decade ago. Then Mark switches to the NeoChrome manual. Another half hour later, Mark is dropping little green dots over a blue background.

For the next few evenings, Mark secludes himself in his old high school bedroom, getting familiar with this computer thing and its painting program. Using the little mouse is like holding a potato, forcing his hand into a claw. Whenever he begins to feel that he's got the hang of it, that he can forget about the tool and focus on the task, whenever his eyes spark a connection between the image on the screen and the image on his brain, his hand jumps from the mouse to grip a pencil that's not there, a phantom limb.

He teaches himself to draw a single picture, a little African hut that he repeats over and over until he memorizes the procedure, which he will repeat a few days later to survive his interview.

#+begin_export html
<br/><br/>
#+end_export

Mark walks out of the garage and meets Gary at the porch. Gary shows him around the Stable House, introducing him to everyone in the Games Group, and takes him to his desk. He'll be sitting next to Gary and across the hall from Ron and David, the two programmers they'll be working more closely with. Mark notices there are not one but two different computers on his desk. And neither looks like the AtariST he's been using.

"That's a Commodore 64", points Gary, "and that's a DOS PC. We've been transitioning our games from c64 to DOS. In fact, your first job will be helping us to port the backgrounds of our new game. You'll notice they are, uh, a bit... clunky, when it comes to graphics. Especially that one", he points at the PC.

Mark feels like throwing up.

"Haha, I know, it's a lot. Look, the only thing you need to know about this one is how to run the game. And for this one... You'll mostly just be using DPaint".

Nobody around here really knows what they are doing, Gary reassures him, not even the programmers. They are all just trying to figure out what it means to tell a story in this new medium, in this new genre. What a video game worthy of LucasFilm should be like. There are no experts at /that/. "An artist perspective is what we expect you to bring to the table. The tools, you'll figure out. They change all the time, anyway".

They spend the next hour fiddling together with Deluxe Paint II, the drawing program for the PC. It's more or less the same as NeoChrome, but with more sophisticated brushes, or so Gary says. Mark notes the colors are fewer and uglier than the ones he saw in the Atari. "Oh yeah. Those are the colors of your nightmares, starting tonight".

After lunch, Ron sits with Mark to play /Maniac Mansion/, his B-horror adventure game. He shows Mark how to move around, how to talk with other characters, how to solve puzzles to move the story forward. /Maniac Mansion/ is a sort of blueprint of the kind of work they are trying to do. There's a newer game they've been working on, David's game, /Zak MacKracken/, but /Maniac Mansion/ is a gentler introduction. It's best if Mark just spends a couple of days playing it, to get the idea. Marks imposter syndrome kicks in now and again, and he apologizes for his dumb questions. He's no gamer, not even an arcade player. That's perfect, says Ron: they want to build something that just about anyone can pick up and have fun with.

He leaves the office with sore eyes from the computer screen and a headache from all the names and images shoved into his brain. He's relieved that no one's around to see him pull his Honda out of the underground garage. He slows down as he drives by the Main House, where they had lunch that day, a new building made to look old---not any old but period-specific old. He confirms that it looks just like the one they put in the game. He circles by the artificial lake and passes the barn, the corral, the vineyard. This little valley surrounded by green hills feels as otherworldly as one of his fantasy landscapes. Or a shot from /Star Wars/.

#+begin_export html
<br/><br/>
#+end_export

Mark's first job is to port /Zak MacKracken/'s Commodore64 backgrounds to the EGA. David gives him a document describing each location of the game. They call them /rooms/ even though some are outdoors---outer space, even. Each one has a short description and a list of "hotspots", the things the player can interact with: objects, doors, that kind of thing. Mark has to make sure that those remain visible on his ported backgrounds. Other than the list of rooms, the only design document is a huge puzzle chart posted on the wall, a sort of storyboard for programmers. Mark can't make sense of it, or the game, for that matter. /Zak MacKracken/ is bigger and more ambitious than /Maniac Mansion/; the work is more interesting, but the game is undecipherable to Mark.

At first, he tries working from the original c64 bit maps, but that complicates things.
Both are 16 color systems, but /not the same/ 16 colors, so swapping them is pixel Whac-A-Mole. He turns to redrawing the backgrounds from scratch. He sketches on his notebook to try options, he plots the pixel grid in graph paper and draws on acetate sheets that he then tapes to the monitor. He will try anything before moving to the computer, where nothing flows, where everything is clumsy and rigid as Lego building, and it's hard to tell whether something will work or even fit until it's almost done.

Black, dark gray, light gray, white, dark blue, light blue, cyan, yellow, mustard brown, dark red, poppy red, peach, magenta, acid-hot pink, grass green, and acid-chartreuse. Always the same suffocating 16 colors for anything he needs to draw. He has to ponder carefully what colors to "spend", an early decision that constraints the rest of his choices: the scene composition, the mood, what's shown, what's hinted. There's no room for impulse or experimentation, everything needs to be planned in advance. Despite his Digital Background Artist title, his job doesn't seem to be concerned with art. He's like the poet employed as copywriter. The only creativity is in subverting the tools, working against and around them, eventually leaning on their limitations.

#+begin_export html
<br/><br/>
#+end_export

# TODO maybe comment what they are having, some gourmet meal. osso buco with risotto

"Coppola", says David.

"Coppola, of course", Gary concurs. "The Rolling Stones".

"Wait, all of them?"

"Hmm. Mick Jagger. And the drummer, I guess."

"I missed them. I did see Huey Lewis."

"Yep. We played softball with the band."

It's Mark's third week, and it's the first time he catches a glimpse of George Lucas. They usually only see him at the restaurant when he has visitsg. Gary and David are listing all the famous people they saw at lunch. Today it's Spielberg.

"You'll understand, of course", David turns to Mark, "that while it may seem as if they were right there across the room, we are not breathing the same air. We're worlds apart."

"Galaxies", Gary suggests.

"Galaxies apart, thank you. They are holograms, like that Leia message on the first movie. We can see them but they don't see us."

"Under no circumstances should we be noticed by Lucas or his guests, or any film-related people, for that matter."

"And especially not Lucas."

The owner doesn't care at all for video games. The existence of the games division is a sort of corporate accident, a spin-off of the Graphics Group prompted by a failed collaboration with Atari, a product of another age of the company. And the fact that they got to stay while the Graphics Group---now called Pixar---was sold to Steve Jobs, is another corporate accident. They're a rounding error, the last hackers standing, the only division totally unrelated to film making. A kind of intruders. So the idea is to make themselves invisible, not to remind George Lucas that they exist, that he still owns a little video game studio, that they are spending his money and---much worse---taking up precious space.

"Our man Steve, on the other hand, is our biggest fan", David points his fork to Spielberg. "You'll be seeing a lot of him."

"He's just nuts about tech, this is like an amusement park to him. He's more into it than Lucas, I think."

"He'd probably live here if he wasn't busy, you know, making blockbusters."

"Did you know he used to call Ron for /Maniac Mansion/ hints?"

"So yeah, I bet he'll get involved in one of the games sooner than later."

"An Indy game, most likely."

"When the tech is good enough."

"And when they get back the license."

"Right, when we get the license."

That part Mark already knows. He learned it on his first week: LucasFilm Games doesn't have the rights to make Games based on LucasFilm properties. No /Indiana Jones/, no /Star Wars/. Some toy company holds the rights.
They are expected to come up with original ideas for their games, which is both a blessing and a curse.
They have creative freedom but they must live up to the Lucas standards without the easy sales of his intellectual property.

#+begin_export html
<br/><br/>
#+end_export

The mouse, the pixels, the 16-color palette, the hotspots: those are the constraints he has to work with. One trick---a /hack/, programmers would say---he discovered early on was that, if he formed a checkerboard pattern of pixels, they would blend and bleed in the screen as he zoomed out, producing shades beyond those boring old 16 colors of the EGA palette.

This was one of those happy accidents he was so fond of when working with new materials, a side effect he didn't pay much attention to until he decided to "weaponize" it for artistic effect.
# FIXME be specific about what background he's drawing, one of zak ones
this background could be the perfect excuse.
<todo describe how he draws it, where he uses dither
<this was obviously not art, not yet, but it was better that anything he did before and anything he saw in the previous game; most importantly it was progress, it was a hint of path they could explore to get closer to his goal.
he sends it/takes it to the programmer, goes over to his desk to see their reaction and get some praise, we're taking the art on this game to a new level folks, he's expecting a pat on the back

the image loads up on the screen from top to bottom. ron takes a few seconds to look at it before speaking up

"What the hell, man?"

"I... wait, what?"

"The pixels here look all... dithered. This won't compress." He speaks in his soothing monotone, which makes him all the more scary when the words imply he's not happy

"Dithered?"

"What's up", Gary joins them, sensing trouble. "Wow, that's neat <background>. Oh, wait, that won't compress. Yeah, you can't do that."

"What's compression, again?"

"Those little patterns there, you can't do that, that will take too much space."

Those damned computers. He's been doing this for months and still can't tell when he's doing it right. It's like they come with a bunch of unwritten rules that everyone knows about but him. And the programmers, with their arcane knowledge, are yet another layer of constraints, an extension of the machines that he needs to poke about until it works.

Gary tries to be didactic in these situations, not because he cares that Mark understands the technical details but because he wants to make sure he gets that they have good reasons to clip his wings. Gary proceeds to explain that the image data is run through a compression algorithm so it takes up less storage in the disk. The idea is that instead of storing the colors pixel by pixel, they store how many times the current color needs to be repeated; the more same-color segments the image has, the fewer space it will take in disk. His little checkerboard technique---his color "dithering"---completely breaks this idea, possibly making the compressed image take /even more/ space than the original. Dithered backgrounds would double or triple the required disk space, which would double the amount of disks required to ship the game, which would double production costs, which would double the game's price tag, which would surely get them all fired. "Try again with solid colors, please." he concludes, and pats him on the back. "That was some background, though, huh?"


#+begin_export html
<br/><br/>
#+end_export

he figured his bodily reaction to screen time was somehow connected with sleep deprivation. at first, pulling 6 or 8 straight hours in front of the computer seemed to burn him out, but after 10 or 12 he didn't really cared, he just kept going until he literally felt asleep on the keyboard

<everyone warned him there was going to be crunch time when they got closer to the release date
<Here's the thing about deadlines: everybody knows they won't make the first one or two deadlines, and that's fine, but also everyone accepts that they'll miss them in crunch mode, if anything to keep up appearences
mark defaulted to a belligerent attitude towards authority and thus was, in principle, against overtime and having to meet executive demands and meet deadlines
but, also, he didn't really mind the effort.
he never once lost sight that
he was getting paid to be an artist---even though he didn't felt these computer drawings were there yet---
he was paid handsomely, more than every
he was having fun, he respected his teammates,
he was working at geek disneyland,

he was already used to working late, in the quite months they would take long lunches or hikes through the hills or they would toss a softball around in the field out back, so they ended up working late to make up for the time
most of the people on the team was in their early twenties so they didn't have anywhere better to be anyway

so as the project deadlines arrived, they just kept working late, only skipping the long breaks during the day.

weekends at the ranch, though, were off-limits. they would let him take his computer back home on fridays to work during the weekend

during this periods he got used to taking breaks from the works without getting away from the computer. he always kept one or two personal illustrations on the side, where he <got off> from all the restrictions that the game backgrounds imposed on him
he would use dithering, and colors otherwise reserved for sprite characters, and unconventional image dimensions

if they tell him that dithering is off-limits, then he'll put in as much dithering in his personal work as he can.
what's a good excuse to do this a lot? what type of background would call for a gradient of as many colors as one can think of? A sunset.
<TODO lookup details about this sunset in the interviews

this was... art. and now hi was annoyed that he couldn't put stuff like this in the game. he set it as a screensaver in his computer to send a passive-aggressive message, a kind of protest---against no one in particular, no one in his team, anyway. Ge was protesting Turing and Von Neumann and George Lucas and Ronald Reagan, for making it so damn hard to make art for a living.

takes a long lunch, when he gets back to his desk the divsion director and gilbert are discussing, why exactly doesn't dither compress? can't we do anything about this? art like this in our games would be a game changer, the differential people came expect from our films, now in the computer.

# TODO: maybe some compression technical details

a few weeks later he was informed that dithering was now supported. he realizes the programmers too have their own set of constraints, their own challenging puzzles they need to resolve to get some creative output from these machines

the division head told him they would double down on dithering for the look and feel of the next game, that he would be lead artist for it. your <stock> just went up.

#+begin_export html
<br/><br/>
#+end_export

The Main House was a 10 minute walk from the Stable House. Mark mentioned he would go over to the library and Purcell tagged along. Nobody passed on an excuse to visit the Main House.

"What are we researching?", asks Purcell as they leave the porch.

"I want to look up some material for /Loom/. Some of that /Sleeping Beauty/ stuff he mentioned."

"Oh, so you meant /actual/ research." People in the Games Group use /research/ as keyword for anything that blatantly isn't work. They ask /What are you researching/ to anyone they catch fooling around the office. "Well, I guess I can use some reference material myself".

Mark was assigned as Lead Background Artist for the new game. Purcell will do animations. He did the cover art for /Zak/, this will be his first video game project. For /Loom/, they are supposed to figure out how to turn an EGA adventure into a "living tapestry", like Eyvind Earle did with /The Sleeping Beauty/.

"So what do you make of The Professor?" Purcell asks. Professor is what they've been calling Brian Moriarty, the project lead. They brought him from Infocom, a struggling text adventure shop.

"He seems cool."

"Very cool."

"He certainly knows his game design."

"Oh, yeah."

"Maybe he's a bit too...”

"Professorial?"

"...well, I don't want to say /ambitious/", Mark waves at the house, they are walking past the Solarium, rounding the right wing of the House, "because, who isn't around here?"

# TODO not sure it's useful to add commandments here
"He better be. /Be the best/, right?" Purcell is quoting Lucas's only ever command to the Games Group: /stay small, be the best, don't loose any money/. Sometimes abridged as: /don't lose money, don't embarrass George/.

"...but, perhaps too much of an idealist. I can't believe /I'm/ saying this." In a sense, Moriarty is his kin: they take their work very seriously, they are both driven by a desire to produce art. But Mark knows all too well that, despite his title, he isn't paid to make art. They pay him to produce backgrounds, conforming to a set of specifications. The art, he has to smuggle, in spite of the business. The Professor, on the other hand, seems committed to breaking new artistic ground, and operates as if everyone else shares his vision. Mark couldn't imagine any other company where they would give such a guy /carte blanche/ to make whatever game he wanted.

# TODO lookup infocom descriptions, maybe one from a moriarty game
<They are standing in the hall of the Main House, <DESCRIBE ARCHITECTURE>. The east corridor leads to the solarium. To west corridor, leads to the restaurant. To the north is a large wooden door and, on each side, a staircase.

<there's a stormtrooper here.>

<there's a crystal display case with Yoda in it here.>

They go north.

"I mean, a fantasy game?" Purcell continues as they enter the Library, "/The Sleeping Beauty/? Tchaikovsky? Doesn't sound very LucasFilm to me."

"I like a good fantasy", says Mark.

"More /Lord of the Rings/ than /Star Wars/. Or /Indiana Jones./"

"But, does it sound like /Maniac Mansion/ or /Zak MacKracken/. That's the real question."

"...or /Sam & Max/."

"Or /Sam & Max/, sure,” Mark concedes.

Purcell is on a mission to convince everyone there /could be/ a game based on his comic. If he plants the idea on enough heads, someone will eventually ask him to make one.

"Well, I'd say it sounds like /Zork/, obviously... and /King's Quest/?"

"Ouch."

"Well, what do I know?” says Purcell, "I haven't played any of them."

"Me neither."

There's a counter at the entry of the library. <TODO describe: spiral staircase leading to the 2nd story and to Luca's office, stain glass dome

They need to register before going in. The librarian asks them what's the purpose of their visit.

"We're looking for research material for /Loom/,” says Mark.

"He's looking for research material for /Loom/. I'm looking for research material for /Sam & Max/.”


#+begin_export html
<br/><br/>
#+end_export

The memo supplied two separate but related pieces of news: LucasFilm recovered the rights to make /Indiana Jones/ video games; they have six months to come up with an Indy game based on the new entry Spielberg is shooting.

<the devs got a copy of the script and there were some screenings at the main house
some of the folks even got to visit the set
purcell came back with a whip for "research purposes", which they incorporated to their afternoon sporting activities
and drank coffee from the <holy grail> cup

mark was relieved, if a little worried, that they let him continue with loom while most of the people switched to indiana jones
he was suspicious of IP games, he preferred originals
he could see how the designers were struggling to make everything fit the movie script and still be playable
nobody was sure what the interest could be if people already knew the plot
from an artistic point of view it would've been restraining as well
and they certainly weren't about to toy with his dithering stuff with such a tight deadline
this was just a money making game

it was obvious that once the star wars license embargo was lift off, it would take a hell of an effort to prevent the suits to send all hands to milk chewbacca

#+begin_export html
<br/><br/>
#+end_export

Some times Professor Moriarty gives Mark and Purcell story prompts and asks for concept art in return, but more often than not he wants /them/ to come up with stuff he can use for inspiration, based on the short treatment document he handed them and the /Sleeping Beauty/ reference material. This was the first proper illustration work he did since he joined the company two years ago.

Mark pulled everything he could get from the library on Disney, Eyvind Earl, and medieval tapestries. He would play the movie on the Media Room of the Main House, frame-freezing to take notes and make sketches. Mark would deliver two or three drawings a week, using his now legendary pencil.  Most of the times, Moriarty would come back with notes to refine an idea or a request to try again, but occasionally he would take a drawing and use it to write a piece of the story. In those cases the Professor would ask Mark to convert his illustration into a dithered EGA background, so he could wire it up in SCUMM and start experimenting with descriptions and dialog.

The Professor set up similar workflows for animation and engine programming and, most importantly, with the sound department. Music and sound would feature in /Loom/ more prominently than in any other LucasFilm game.
which was convenient, since the Ranch housed the best sound engineering facilities in the world
<for them, instead of Eyvind, it was tchaikovsky
<much of the game's concept would be centered around the music of Tchaikovsky, just as in the film, so he suggested they explore its art style for the background art and the animations

<Moriarty thought of games as a novel medium to produce art, and he wanted to use all of its materials to that end: sound, music, backgrounds, animation, story, and dialogs. He made sure everyone on the team picked up on his vision for the game and gave them freedom to figure out how to realize it with their tools.
Coming from a rather lonely experience writing text adventures, he was betting on team collaboration to flourish to <unlock a deeper storytelling experience. This ideal would find its way into the story, with the protagonist visiting Guilds of Craftspeople over the course of the game.

Mark would come up with the idea of using colors scheme to represent each guild, giving a distinct quality to each section of the game: the striking emerald of the Guild of Glassmakers, the softer pastoral greens of the Guild of Shepherds, the Stygian reds of the Guild of Blacksmiths and of course the lovely saturated blues and purples of the Guild of Weavers. This is a feat he imposes to himself, with the EGA colors allowing for one or two shades of each color, the rest having to be mocked with dithering and similar palette illusions

The latest version of the SCUMM engine not only allowed for Mark's dithered backgrounds, but introduced character scaling to represent distances, allowing him to move away from the horizontal axis and add perspective to his scenes.
For the first time he wouldn't be adapting someone else's rooms, he knew his tools and was free to push them to their limits to create whatever he could envision.

#+begin_export html
<br/><br/>
#+end_export

After /Indy/ and /Loom/, it was the turn for Ron to lead another project. A new Ron adventure was only second in anticipation to the advent of a /Star Wars/ license; he was considered the resident ideologist and the one that was most likely to push the genre forward. His new game was to be the ultimate realization of the game design philosophy he'd been advocating ever since /Maniac Mansion/.

/Monkey Island/, Ron's /Pirates of the Caribbean/ spoof, went out just a few months after /Loom/. People said the game marked a new beginning for LucasFilm games, but to Mark it felt more like a culmination of the process they started four or five years before, where they put to practice everything they learned about the medium.

<Mark still was no gamer and didn't play any of their games. he had no way of telling wether they were any good. but it was any indication, the fact that everyone seemed to be doing so good at their thing and they felt collectively creative made him assume the work was going to be good. the fact that management asked for a sequel right away he took as the confirmation. on the other hand, Loom, which was supposed to be a trilogy, didn't get a second entry and The Professor was too burned out to fight for one.

there was a lot of movement around the office in the final weeks of /Monkey Island/. the team was too deep in crunch mode to notice. they seemed to be growing in size, one or two new employees starting every week. And everyone got new 486 PCs with VGA cards
his is still boxed in his desk, he didn't have the time to set it up and he wasn't going to use it for monkey anyway

- 50 meg? what are we supposed to do with all of this space?
- it's the first time he sets up his own computer, and he is surprised to notice he doesn't need much help from those around him

- at first it seemed like his independence day, free at last from his 16 color jail
  every dithering stretch he could remember doing for /Loom/ and /Monkey Island/ would be unnecessary with this palette.  anything he may ever need seemed to be contained by these new 256 colors
  as was often the case when he is in between projects, he is free to spend his time however he sees fit.
  he decides to work on a new take of his legendary sunset landscape, to test drive the new palette. it would be a good way to try the DPaint gradients that were useless on VGA.
but this little project would reveal a new form of anxiety: he doesn't know what he's doing anymore. His palette choices aren't as relevant anymore, his scene planning <turns into> paralysis, he has to rethink his whole process. These new computers are a career reset.

#+begin_export html
<br/><br/>
#+end_export

computer specs aren't the only thing changing around the office

- receives an internal email about the rebrand
  - maybe /The Force Awakens: LucasFilm Games is now LucasArts/
  - TODO: what's the technical org change?
- the mail also mentions something everybody knows about, like there was a "writing on the wall"/sword of Damocles hanging over their heads: the star wars embargo lift. most people loved star wars and couldn't be more excited about getting their hands on their property for a videogame. mark also loved the movie, but he struggled not to see that date as a death sentence for the creativity of the studio

- for his first lucas arts game he got assigned a new Indiana Jones adventure, from left over scripts, which was probably worse.
- Not only is he stuck with an IP game while the cool kids are working on a Monkey Island sequel, but he didn't even get a chance of working on the VGA ports of his own Loom and Monkey Island backgrounds

- he could see some of the new folks, don't even remember their names, working on VGA ports for their old games, some "enhancing" his loom and monkey island backgrounds.
  - the results were more colorful, yes, but also less vivid, they lacked the personal style, the touch of the artist, that was lost in translation.
  - each pixel on his dithered patterns was loaded with his intent, now dpaint did most of the thinking through a generic color gradient

- they start publishing a magazine, featuring sam & max comics

- now they were doing hand painted backgrounds, then scanned in photoshop on a Mac and moved to dpaint for cleaning up
  - it was funny that 3 years ago this would've made life much easier to old mark, it would kept most of his work in illustrator land and much less in computer land
  - but now it meant that a lot of he had to learn, a lot of the craft he acquired, was now irrelevant
  - he went from industry expert on to just another illustrator, not a particularly good, young or productive one .
  - the originals by peter chan were gorgeous but the results in the screen were filled with random noise, it would take time to figure out a polished look for the new technique
- discussed with someone
  - it finally felt like we got a hang of this thing in monkey island, that we could push it beyond its limits, but now is like we need to start over
  - "a technology is always at its best right before it's obsolete, man"
  - who said that? I don't know but he's right
- that made total sense to him, he could easily see the pattern: they'll always be cornered by new developments, always chasing after the new hot thing
  - after scanners it would be compact discs or rgb color or those three dimentional things they were developing over at the ILM <basement/freezer?> or over at pixar
  - more colors, more space, more processing power but also more complexity, more time to get familiar and competent with the tool, let alone creative or innovative.
    - it would take them more time to find the boundaries of the tech and thus longer to squeeze some art out of them,
    - and they'll obviously lack that time, it won't be long before the next computer generation arrives

#+begin_export html
<br/><br/>
#+end_export

<TODO consider rewriting this in adventure style look at, pick up etc

Mark is packing a box with the few last things remaining in his office. There's the pile of sketchbooks, labeled by month and year; you could read a history of LucasFilm games by skimming through them. His Indy and Chewbacca action figures. The worn out DPaint 2 manual, which he hasn't used in ages. By now he could write his own, a much better one; not even its authors know the things he knows about that program. There's a set of colored pencils that he hand picked to approximate the 16 EGA colors. He changes his mind and tosses it into the bin. The last thing in the box is an issue of /Sam & Max/, signed by Purcell.

<TODO add a loom box, signed. he signed one for brian
<maybe: the sleeping beauty reference book, that he never bothered to return
<maybe: an issue of The Journal of Computer Game Design, featuring Ron's /Why Adventure Games Suck/.

<FIXME this style doesn't really work
He puts the box in the trunk and starts the car---/maybe he should just go back to illustration, freelance like Purcell does, sell his work by the piece to Lucas or to whatever other company/---he drives out of the underground garage on his same old Honda Civic---/he knows it doesn't get better than making adventure games at Skywalker Ranch, he won't get this thrill anywhere else, much less as a freelance artist, but he won't get it by staying, either, LucasFilm is gone, replaced by LucasArts/---rounds about the stable house for the last time---/such a typical corporate move, rebranding to LucasArts just as they move them into an insurance office building full of cubicles, a bunch of boring technicians churning out Star Wars flight simulators/---Ewok lake is glowing with the reflection of the sky, like a dithered EGA sunset---/no more rebels, just stormtroopers/---he doesn't look out to the barn nor the corral, he barely nods to the security guy on his way out---/no more lucky breaks/.

#+begin_export html
<br/><br/><br/>
#+end_export

*** Sources
- [[https://www.bitmapbooks.com/en-ar/products/the-art-of-point-click-adventure-games][The Art of Point-and-Click Adventure Games]].
- [[https://www.youtube.com/watch?v=z1aVDael-KM][Classic Game Postmortem: LucasFilm Games' Loom]].
- [[https://www.filfre.net/2015/07/a-new-force-in-games-part-3-scumm/][A New Force in Games, Part 3: SCUMM]].
- [[https://www.filfre.net/2017/02/loom-or-how-brian-moriarty-proved-that-less-is-sometimes-more/][Loom (or, how Brian Moriarty Proved That Less is Sometimes More)]].
- [[https://www.filfre.net/2017/03/monkey-island-or-how-ron-gilbert-made-an-adventure-game-that-didnt-suck/][Monkey Island (or, How Ron Gilbert Made an Adventure Game That Didn’t Suck)]].
- [[https://www.filfre.net/2018/09/indiana-jones-and-the-fate-of-atlantis-or-of-movies-and-games-and-whether-the-twain-shall-meet/][Indiana Jones and the Fate of Atlantis (or, Of Movies and Games and Whether the Twain Shall Meet)]].
- [[https://bossfightbooks.com/products/day-of-the-tentacle-by-bob-mackey][Day of the Tentacle]].
- [[https://youtu.be/ri4_3P2Oh14?feature=shared][The Making of Monkey Island - Behind The Scenes]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-4-Loom/5][LucasArts' Secret History #4: Loom Developer Reflections]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-The-Secret-of-Monkey-Island/7][LucasArts' Secret History #5: The Secret of Monkey Island Developer Reflections]].
- [[https://datagubbe.se/crt/][The Effect of CRTs on Pixel Art]].
- [[https://www.superrune.com/tutorials/lucasfilm_ega.php][Lucasfilm EGA adventures: an appreciation]].
- [[https://web.archive.org/web/20030326051107fw_/http://lucasfans.mixnmojo.com/features/interview_stevepurcell.html][Steve Purcell Interview]].
- [[https://grumpygamer.com/guybrush_fact_fiction][Guybrush Fact vs Fiction]].

*** quotes                                                         :noexport:

#+begin_quote
I feel the stage sets we rendered as best we could for those earlier games conveyed all sorts of personal artistic style and evocative atmosphere, while most of the 3d game environments that came after them seemed almost universally airless, lightless, and rendered in such a uniform 'algorithmic' art style.

I think we lost things---important things--- whenever accelerating technological fixes and agendas overtook, and to some extent eclipsed, human creative navigation and intent.
#+end_quote

#+begin_quote
had chosen to center his film-making operation in Northern rather than Southern California, much closer to Silicon Valley than to Hollywood.

Lucasfilm, the owner of Star Wars, had a games division that wasn’t allowed to make Star Wars games

“We’re trying to produce an experience that’s like being part of a film, rather than just being part of a game.
#+end_quote

#+begin_quote
he Games Group got moved from their nondescript offices in San Rafael to nearby Skywalker Ranch, the “filmmaker’s retreat” at the very heart of George Lucas’s empire. They were housed in an ornate structure of Victorian brick called the Stable House, with crackling fireplaces in almost every room. Later, old-timers would tell newcomers stories of the Games Group’s time at Skywalker Ranch, which would last for just a few years, like legends from before the Fall: catching a sneak preview of a new David Lynch film in the company of Lynch himself in the Ranch’s beautiful 300-seat art-deco theater; hanging out on a regular basis with Steven Spielberg, who wanted to play everything the Games Group had in development every time he stopped by, sometimes for hours at a stretch; playing softball on the Ranch’s gorgeously manicured field with rock star Huey Lewis; hiking up to the observatory after a long day at the office to do another sort of stargazing; eating gourmet lunches every day at the Ranch’s restaurant for $5 a pop.

providing production services to the film industry (Industrial Light and Magic, Skywalker Sound) and making mass-market entertainments. The old Computer Graphics Group that had awkwardly spawned the Games Group still hadn’t really proved themselves to belong in the former category, while the Games Group, at least if you squinted just right, pretty much did belong in the latter. Thus, while the Games Group got to remain at Lucasfilm, the Graphics Group in February of 1986 was spun off to a collection of investors that included many of their own current personnel as well as, as ringmaster of the whole proceeding, Steve Jobs

Soon the old Games Group represented the only significant hacker presence left at Lucasfilm. It was during this period of colossal change that George Lucas took rare personal notice of Games for long enough to deliver his most oft-quoted piece of advice to Steve Arnold: “Stay small, be the best, don’t lose any money.” This commandment has often been taken to represent a sort of creative carte blanche for Arnold and his charges. Taken in the context in which it was uttered, however, it’s probably better seen as a warning. The Games Group was free to continue to trade on the Lucasfilm name and enjoy their gourmet lunches at the company cafeteria, but they’d have to start paying their own way from here on. Should they fail at that, their rope would not be a long one, for Lucas had little personal investment in their work.

 Driving much of the design was a philosophy that adventure games should be friendlier, less tedious, and much less deadly than was the norm from competitors like Sierra.

the big neo-Victorian “Main House” at Skywalker Ranch. The spiral staircase inside the library in Maniac Mansion is lifted straight from the “filmmaker’s research library” in the Main House.
#+end_quote

#+begin_quote
a mandate came down from Lucasfilm Games’s parent company’s management: they wanted an adventure game to go with the upcoming film Indiana Jones and the Last Crusade. Such a mandate was unusual for the privileged little artists’ enclave that still was Lucasfilm Games at this time,

  Some start using it as a defense mechanism only after being slapped in the face by the game a few times, the rest just stop playing.

   major corporate reorganization was in progress at Lucasfilm, which saw the games division given far more resources — their personnel roll grew from about 25 to more than 100 between 1989 and 1991 — but also given much closer supervision. They would now be expected to justify each of their projects to the accountants. This transformation of Lucasfilm Games from sideline to major profit center was by no means viewed as a comprehensively bad thing by everyone working inside the games division — it did after all lead to them finally being let loose on the Star Wars intellectual property, something they’d been wishing for for years — but it would change the character of the place and the games that came from it forever.
#+end_quote

#+begin_quote
This committee approach to the game’s design is typical of the workaday nature of the project as a whole. The designers were given a copy of the movie’s shooting script, and were expected not to deviate too much from it. Ron Gilbert, a comedy writer by disposition and talent, found the need to play it relatively straight particularly frustrating, but it seems safe to say that all of the designers’ creative instincts were somewhat hemmed in by the project’s fixed rules.

if you’ve seen the movie — and it seemed safe to assume that just about everybody who played the game had seen the movie — what’s the point in walking through the same story again in game form? The

Those changing circumstances would prove a not-unmixed blessing for them, forcing them to move out of the rustic environs of Skywalker Ranch and shed much of the personality of a quirky artists’ collective for that of a more hard-nosed media enterprise. On the other hand, at least they’d finally get to make Star Wars games…
#+end_quote

#+begin_quote
when the Zak project was finished I sat down one morning and rendered a twilight scene with a rising moon and stars over receding oak covered Hills all rendered smoothly and subtly and dithered EGA graphics then in silent protest I simply left a picture up on my monitor
#+end_quote

<mosaic artist
assembly line

#+begin_quote
it was my first time drawing with a mouse. i'm a traditional guy, so I like to draw with a pencil. So for me to try to drawn with a potato in my hand, and then, look up on a screen, and the pixels are the size coasters
#+end_quote

observatory

#+begin_quote
The Skywalker Ranch Research Library is not your typical library. Yes, it is filled with books, but also much more than that. It houses an impressive collection of research materials curated specifically to assist in the filmmaking process.

In addition to books, the Library contains documents, photographs, props, and other items that have been used in the development of Skywalker Sound projects.
#+end_quote

#+begin_quote
contains an impressive collection of Art Nouveau furniture and fixtures. There are Tiffany lamps and original paintings by Norman Rockwell and Thomas Hart Benton. Under a stained glass skylight sit shelves of books relating to all aspects of film production. In addition to their own impressive collection, their holdings also include the Paramount Research Library and the Universal Research Library collections.
#+end_quote

#+begin_quote
And to me, the shining star, the Lucas research library -a two story open atrium with books on every topic any writer, artist or musician could need to conceptualize a story. Ladders around the perimeter, a huge fireplace, and lush leather chairs and couches. On walking in, all I could think was something in my life has gone very right to have found that place - and something gone very wrong that I wasn't spending every day there.
#+end_quote

#+begin_quote
The team of stained glass artisans took six months to build the 19-foot dome. It was comprised of 400 sheets of glass, finely sculpted into 49 separate panels.

With the dome installed, the library took on a new look. The warm redwood and sensuous curves and details were continuously bathed in the amber light from the dome. Books from Hollywood studios’ abandoned research libraries were purchased and began to fill the shelves. The spiral staircase led to the upper balcony with a door into George’s inner office. This was his library.
#+end_quote

*** tasks                                                          :noexport:

**** TODO design documents
https://grumpygamer.com/maniac_mansion_design_1
https://grumpygamer.com/puzzle_dependency_charts
https://grumpygamer.com/even_more_monkey_island_design_scribbles
https://grumpygamer.com/rtmi_pdc
https://grumpygamer.com/stuff_and_things_and_monkey_island
https://grimfandango.network/media/Grim_Fandango_Puzzle_Document.pdf

**** TODO review the adventurer issues
https://archive.org/details/lucasarts-the-adventurer--magazine-complete/The%20Adventurer%2C%20Issue%20No.%2003%20Fall%201991/page/n1/mode/2up
https://archive.org/details/lucasarts-the-adventurer--magazine-complete/The%20Adventurer%2C%20Issue%20No.%2002%20Spring%201991/page/n3/mode/2up
https://archive.org/details/lucasarts-the-adventurer--magazine-complete/The%20Adventurer%2C%20Issue%20No.%2001%20Fall%201990/page/n1/mode/2up

**** TODO experiment with dpaint
**** TODO exploration scene?
e.g amusement park, monkey island style
**** TODO cleanup quotes
CLOSED: [2024-10-05 Sat 13:52]


*** chunks                                                         :noexport:
https://i.pinimg.com/originals/53/b1/f1/53b1f1a0961866d25ed578d345945dd4.jpg
http://iveneverdonethat.com/blog_files/skywalkerranch.html

But it doesn't take him long to become productive. That is, to work out usable backgrounds fast enough to meet the developers expectations, which are lower than his own.

<There's little room for the sort of creativity that stems from impulse and experimentation (but much from constraints, pushing the boundaries, happy accidents that lead to innovation
it gets better as /he/ gets better, more familiar with the tools; once he grasps what are his materials and what their capabilities and limitations, he can start using them to his advantage---work around and step on the constraints and push himself to be creative as with any art and any material, just like does with pencil and paper.

<The one time Lucas showed his face in the Stable House, he said to the director: “Stay small, be the best, don’t lose any money.” That became their gospel, an easy way to answer the question /what would George want us to do?/,an easy way to settle arguments and make design decisions---and an evergreen source of jokes.

<the only part of this that affected him, Mark thought, was /be the best/, and that was how he intended to operate anyway, he didn't need a manager to tell him. he left to the suits, though, to figure out how his work and that of his teammates was supposed to be connected to the money making.

his goal was to produce art and get paid for it, so he give as little thought as possible to the needs of the project and the business.
it's convenient that they don't expect much from him, because not only he isn't satisfied with his production and it doesn't come close to art, he still feels he has a long way to go to tame the computer, the mouse, the pixels, the palette, and the drawing program.

<Mark developed his own style with the dithering, something he would teach others how to do. He wants to show how he does his thing, but not be prescriptive, allowing other artists to figure out their own style

<TODO: maybe, start with them playing wishbringer.
"we're doing research"
"what are you researching"
"brian moriarty"

<the new game, /Loom/, was lead by Brian Moriarty, an experienced designed they brought in from Infocom, the struggling text adventure shop. Mark had tried one of their games. while he was impressed by the thorough descriptions and the setting---it was like they made him the protagonist of a fantasy novel---he was quickly frustrated by the complicated gameplay and all the typing it involved. It was like the complete opposite of everything Ron and Gary were trying to do with the graphic adventures. They were comic books to infocom's novels. <despite marketing desperation to sell them as interactive movies

<Before meeting him, Mark feared that his previous experience with from text games would make him dismiss graphic work, but Mark quickly realized that Moriarty was of his kin.

there was a librarian but, even he wasn't a book person, he preferred to browse around and find things by himself
the library, perhaps along the art deco theater, is the most impressive indoors location of the ranch
Mark would occasionally look up allegedly to the dome, but it was actually to look at Lucas's office door

<purcell joked that you would go blind if you stared at Mark's screen for too long

<brian asks Mark to illustrate the box of loom
this was an unusual ask, since Purcell did most of the covers of the other games
but Brian wanted Mark, as a sort of <tribute> since he felt it was Mark's work what defined the art style of the game
he had asked Mark to show him some of this work and was impressed by his colored pencil illustrations, so he asked mark to do it
it felt weird for mark, translating the mood of the game, so determined by the blue shades of the EGA backgrounds, to the
a photo realistic drawing he felt was at odds with the primitive art in the game, but Brian seemed to like it
now that Marks is holding the game box in his hands, seeing his work live for the first time---this he could hold and touch, it was much more alive than his work on the screen---, only now he realizes that this is the first time he got paid for a traditional work of art.

it was mostly a game design thing, it didn't affect the graphics, didn't directly affect him, but it was Ron's version of /being the best/ and Mark just felt he should follow suit and apply everything he'd been learning so far and push it to the next level

all his favorite people were in this team

They give him freedom to figure out the game backgrounds, handing him a short list of room requirements and hotspots and no other game context. as long as he meets them he can do whatever he wants.
where brian had been obsessed with story telling, ron was obsessed with gameplay, with the game being fun---and funny. nobody but him really got a clear picture of the entire game, but everyone took part of the brainstorming sessions
his water cooler jokes make it to the dialog of the game.

player reward -> new areas of the game (new backgrounds)

the game was bigger and would feature more rooms than previous ones. they had people working for different parts in parallel, which at some point showd that they werent keeping a consistent style across the game

<something special about this new team and this new game
they were having so much fun with this one, and that stimulated them to try harder and do better, that surely had to show in the final thing


<the engine was at its best
the background art and animation they produced was the best in the industry
<after having free reign to experiment in /Loom/, Mark felt like he mastered his materials,
he knew its limitations and where there was room for letting his creativity flow
