---
title: A Pixel Parable
date: 2024-09-22 17:52:07
layout: post
lang: en
tags: [videogames, software, fiction]
draft: true
excerpt: An imagined town is at least as real as an actual town.
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

#+begin_verse
/An imagined town is at least
as real/ /as an actual town/
#+end_verse

#+begin_export html
<br/>
#+end_export


#+begin_export html
<div class="org-center"><h3>I</h3></div><br/>
#+end_export

"How would you like working on video games?"

Mark is holding his /Best of the Show/ certificate in one hand and Gary's card in the other:
#+begin_export html
<div class="center-block">
<p>Gary W.</p>

<p><small>Art Director</small></p>
<br/>
<p><small>LucasFilm Games</small></p>
</div>
#+end_export

LucasFilm. As in George Lucas. As in /Star Wars/.

#+begin_export html
<br/><br/>
#+end_export


This is his second lucky break of the weekend. A friend recommended he went to this sci-fi convention, she said it would good for networking. Mark wouldn't mind having one of his illustrations on a trading card, or a rule book, or, who knows? on the cover of one of those fantasy novels he used to read in high school.

So he shows up to the convention on Friday. Someone notices his work---these pencil landscapes that look hand-painted---, they invite him to join in the art show, he does, two days later he wins  first place. That's his first lucky break. The second is this guy, Gary, coming over to him, handing him a card, asking him to 'audition' for a video game job.

"Could you come over to the Ranch for an interview?" Gary insists.

Mark reads the card again, stops for a second to think what to say next. He needs a job, after all. Honesty has been working wonders for him so far: "I'd be happy to come over to do anything at all there but... I don't know the first thing about video games. I never even touched a computer."

"That's alright," Gary replies, "we've had better results teaching artists how to program than the other way around. I'm not worried about that part."

Driving back home, Mark tries to make sense of what just happened. On his first weekend---on his first serious attempt as a professional illustrator---he's offered to interview for a role that he didn't even know existed, but that he's now convinced must be his dream job---and one that he's terribly unqualified for.

Later that night, he calls his parents and learns his father has just bought a personal computer. That's his third lucky break.

#+begin_export html
<br/><br/>
#+end_export

"What are you doing with this thing, anyway?" Mark is sitting in front of the computer, skimming the manual. The cover reads /Atari 520ST/.
"The school made a deal for us to get them at half price. They say we should get /computer-literate/ if we want to have a job in five years." The voice comes through the doorway, then his father, leaning on the frame. "I figured I could use it for writing, but they have a different brand at school, so I can't print my files there. And I'm not buying a printer, so I don't see the point. You can have it if you want."

"Let's see if I get the job, first." Mark continues reading the manual. "It says here there's a drawing program in there, 'NeoChrome'. Let's try that out." It takes them about 20 minutes to find the floppy disk and open the program---their first project since his father thought him how to change his oil over a decade ago. Mark switches to the NeoChrome manual. Another half hour later, He's dropping little green dots over a blue background.

For the next few evenings, Mark secludes himself in his old high school bedroom, getting familiar with this computer thing and its painting program and the constant touch of the mouse forcing his hand into a claw. Whenever he manages to forget the tool and focus on the task, when a connection sparks between the image on the screen and the image in his brain, his hand jerks for the pencil he's been missing like a phantom limb.

He puts together a little African hut picture and teaches himself to reproduce it, repeating it over and over from the blank page. He executes this procedure again, a few days later, and survives his interview.

#+begin_export html
<br/><br/>
#+end_export

Mark walks out of the garage and meets Gary at the porch. Gary shows him around the Stable House, introducing him to everyone in the Games Group, and takes him to his desk. He'll be sitting next to Gary and across the hall from Ron and David, the two programmers they'll be working more closely with. Mark notices there are not one but two different computers on his desk. And neither looks like the Atari he already knows.

"That's a Commodore 64,” points Gary, "and that's a DOS PC. We've been transitioning from c64 to DOS. In fact, your first job will be porting the backgrounds of our new game. You'll notice these are, uh, a bit... clunky, when it comes to graphics. Especially that one,” he points at the PC.

Mark feels like throwing up.

"I know, it's a lot,” Gary laughs. "Look, the only thing you need to know about this one is how to run the game. And for this one... You'll mostly just be using DPaint."

Gary reassures him, nobody around here really knows what they are doing, not even the programmers. They are all just trying to figure out what it means to tell a story with a computer. What a video game worthy of LucasFilm should be. There are no experts at /that/. "An artist's perspective is what we expect you to bring to the table. The tools, you'll figure out. They change all the time, anyway."

They spend the next hour fiddling with Deluxe Paint II, the drawing program for the PC. It's like NeoChrome but better, or so Gary says. Mark notes the colors are fewer and uglier than the ones he saw on the Atari. "Oh, yeah. Those are the colors of your nightmares, starting tonight."

After lunch, Ron sits with Mark to play /Maniac Mansion/, his B-horror adventure game. He shows Mark how to move around, how to talk with other characters, how to solve puzzles to make progress. /Maniac Mansion/ is a blueprint of the kind of work they are trying to do. There's a new game they've been working on, David's game, /Zak MacKracken/, but Ron says /Maniac Mansion/ is better to get started. It's best if Mark spends a couple of days just playing it. His impostor syndrome kicks. He's no gamer, not even an arcade player. "That's perfect,” Ron says. "We want to build something that just about anyone can pick up and have fun with."

He leaves the office with sore eyes from the computer screen and a headache from all the names and images shoved into his brain. He's relieved that no one's around to see him pull his Honda out of the underground garage. He slows down as he drives by the Main House, where they had lunch that day, a new building made to look old---not any old but period-specific old. It looks just like the one they put in the game. He circles by an artificial lake, a barn, a vineyard. This little valley surrounded by green hills feels as otherworldly as one of his fantasy landscapes. As a shot from /Star Wars/.

#+begin_export html
<br/><br/>
#+end_export

His first assignment is to port /Zak MacKracken/\’s Commodore64 backgrounds to the EGA PC. David hands him a description of each location in the game. They call them /rooms/ even though some are outdoors---outer space, even. Each one has a short description and a list of "hotspots", the things the player can interact with: objects, doors, that kind of thing. Mark has to make sure that those remain visible on the new backgrounds. Other than the list of rooms, the only design document is a huge puzzle chart posted on a wall, a sort of storyboard for programmers. Mark can't make sense of it---or the game, for that matter. /Zak MacKracken/ is bigger and more ambitious than /Maniac Mansion/; the work is more interesting but the game is undecipherable to Mark.

At first, he tries working from the original c64 bit maps, but that complicates things.
Both are 16 color systems, but /not the same/ 16 colors, so swapping palettes is pixel Whac-A-Mole. Instead, He turns to reproducing the pictures from scratch. He sketches on his notebook, plots a grid in graph paper and tapes acetate sheets to his monitor. Anything to delay the moment when he moves to the computer, where nothing flows, everything clumsy and rigid and LEGO-like.

Then there's the palette. Black, dark gray, light gray, white, dark blue, light blue, cyan, yellow, mustard brown, dark red, poppy red, peach, magenta, acid-hot pink, grass green, and acid-chartreuse. Always the same suffocating 16 colors for anything he needs to draw. He has to ponder carefully what colors to "spend", an early decision that constraints the rest of his choices: the scene composition, the mood, what's shown, what's hinted. There's no room for impulse or experimentation, everything has to follow a plan. Despite his Digital Artist title, his job doesn't seem much concerned with art. The only creativity is in subverting the tools, working around them, against them, exploiting their limitations.

#+begin_export html
<br/><br/>
#+end_export

"Coppola,” says David.

"Coppola, of course,” Gary concurs. "The Rolling Stones."

"Wait, all of them?"

"Hmm. Mick Jagger. And the drummer, I guess."

"I missed them. I did see Huey Lewis."

"Yep. We played softball with the band."

It's Mark's third week, and it's the first time he catches a glimpse of George Lucas. They usually only see him at the restaurant when he has visits. Gary and David are listing all the famous people they saw at lunch. Today it's Spielberg.

"You'll understand, of course,” David turns to Mark, "that, while it may seem as if they were right there across the room, we are not breathing the same air. We're worlds apart."

"Galaxies,” Gary suggests.

"Galaxies apart, thank you. They are holograms, like that Leia message on the first one. We can see them but they don't see us."

"Under no circumstances should we be noticed by Lucas."

"Or one of his guests."

"Or any film-related people."

"And especially not Lucas."

The owner doesn't care for video games. The existence of the games division is a sort of corporate accident, a spin-off of the Graphics Group prompted by a failed collaboration with Atari, a product of another age of the company. And the fact that they got to stay while the Graphics Group---now called Pixar---was sold to Steve Jobs, is another corporate accident. They're a rounding error, the last hackers standing, the only division totally unrelated to film making. A kind of intruders. So the idea is to make themselves invisible, not to remind George Lucas that they exist, that he still owns a little video game studio, that they are spending his money and---much worse---taking up his precious space.

"Our man Steve, on the other hand, is our biggest fan,” David points his fork to Spielberg. "You'll be seeing a lot of him."

"This is like an amusement park to him. He's more into it than Lucas, I think."

"He'd probably live here if he wasn't busy, you know, making blockbusters."

"Did you know he used to call Ron for /Maniac Mansion/ hints?"

"So yeah, I bet he'll get involved in one of the games sooner than later."

"An Indy game, most likely."

"When the tech is good enough."

"And when they get back the license."

"Right, when we get the license."

That part Mark already knows, he learned it on his first week: LucasFilm Games doesn't have the rights to make LucasFilm games. No /Indiana Jones/, no /Star Wars/. Some toy company holds the license. Instead,
they are expected to come up with original ideas, which is both a blessing and a curse:
they have creative freedom but they must live up to the Lucas name.
And they have to pay the bills without the easy cash from his IP.

"Stay small, be the best, don't lose any money", Gary recites.

"And don't embarrass George."

#+begin_export html
<br/><br/>
#+end_export

The mouse, the pixels, the 16-color palette, the hotspots: those are the constraints he has to work with.
One trick he discovered early on---a /hack/, programmers would say---is that, if he arranges pixels to form a checkerboard pattern, they will blend and bleed as he zooms out on the screen. Much like the eyes finish the job as one steps back from an impressionist painting, the monitor melts the pixel mosaic into something richer than what the dull EGA palette could ever project. At first this is just an accidental observation, he doesn't make much of it. It's only when he starts working on a new batch of /Zak/ backgrounds that he finds himself coming back to those mixed pixels.

This section of the game takes place in Mars, a location Mark finds very provocative. The acid EGA palette seems strangely fitting. He owes no loyalty to the muddy c64 backgrounds and he needs not abide reality, either: he's safely into fantasy territory. He realizes he can weaponize the pixel blending artifact and turn this into one of his old sci-fi landscapes.


Drawing from Red Rock and Grand Canyon photos, he easily settles on a composition: a fiery desert, a rocky horizon, and a pale sun, slightly displaced from the center of the picture. It's the palette that gives him the most work, hours of trial-and-error. He needs the right color combinations and the right density of interleaved pixels for each figure, each boundary.
He wants the image to jump out of the screen; he wants the sky, and the sun, and the ground to bleed into each other distinctly---the sun to set the sky on fire and the earth to bed the ashes.

It's not the original c64 background, nor the EGA palette, nor the hotspots list what dictates his work. It's not what he pictured in his head. It's the braid: each pixel born out of its predecessor, each one birthing the next. Little squares boiling with possibility, with no purpose but to carry intent.

For once, he doesn't feel constrained by the material. He's so free that the work becomes free in turn, it takes life and talks back. He tamed the material into rebelling and becoming something other than what he set out to produce, something better than what he could have imagined. It's then, when the work speaks for itself, that he knows. This may not be art, not yet, but it's better than anything he did and anything he's seen on a computer screen. There's the spark. This is the direction, that's where he needs to go.

#+begin_export html
<br/><br/>
#+end_export


Ron sticks the floppy in his computer and loads the image. He waits for the fringes to cover the screen, top to bottom, and gives it a couple more seconds before speaking up.

"What the hell, man?"

"I... wait, what?" says Mark.

"The pixels here look all... dithered. This won't compress." Ron speaks in his soothing monotone, which makes it all the more scary when the words imply he's not happy.

"Dithered?"

"What's up?” Gary joins them. "Wow, that's a neat background. Oh, wait, that won't compress. Yeah, you can't do that."

"Compress?"

"These noisy patterns here, you can't do that, that will take too much space."

It's like computers have a bunch of unwritten rules that everyone knows about but him. And the programmers, too, come with their own rules, another kind of machine that needs poking about until it works. Gary gets into the little technical details, not because he cares that Mark understands them but because he wants him to know they have good reasons to clip his wings: the image data is run through a compression algorithm so it takes up less storage in the disk. Instead of storing the colors pixel by pixel, they store how many times each one needs to be repeated; the more same-color segments the image features, the less space it will take on disk. His little checkerboard technique---the pixel "dithering"---completely breaks this process, changing colors at every step, no repetitions, making the new picture take /even more/ space than the original. Dithered backgrounds would double or triple the required disk space, which would double the amount of disks required to ship the game, which would double production costs, which would double the game's price tag, which would surely get them all fired. "Try again with solid colors, okay?” he concludes, and pats him on the back. "That was some landscape, though, huh?"


#+begin_export html
<br/><br/>
#+end_export

His bodily reaction to screen time is somehow connected with sleep deprivation. At first, pulling 6 or 8 straight hours in front of the computer seemed to burn him out, but after 10 or 12 he doesn't really notice anymore, he just keeps going until he passes out on the keyboard.

They warned him there was going to be crunch time when they got closer to the release date. "Here's the thing about deadlines,” David said: "everybody knows we won't make the first one or two, and that's fine. Nobody really cares. As long as they look out to the hallway and see some glow coming out of the offices, they'll leave us alone."

Mark defaults to a belligerent attitude towards authority so he is, in principle, against overtime, deadlines, and any other management demand. But he doesn't really mind the effort. Never once he loses sight of the fact that he's paid handsomely to make pretty pictures. He may be no artist, but he wasn't at any of his previous jobs, either. And he didn't get to eat gourmet meals, play catch on the field, or hang around in geek Disneyland. Everyone at the office is used to working late, anyway. They just need to pause the afternoon recreations until the game ships.

During those crunch days he gets into the habit of taking breaks without leaving the computer. Instead of taking a walk, or a nap, or grabbing his sketchbook, he just keeps drawing on DPaint. He saves the picture he's working on, saves  again with a different name, clicks the CLR button, then saves again. And then he's not at work anymore. He doodles absently. Or he loads one of his own pictures. Anything to distract him from those flat and blocky /Zak/ backgrounds he's been staring at all day.

They told him that dithering is forbidden, so he's been abusing it on his personal projects. It's a form of stress relief. What's a good excuse to put as much dithering as possible on a single picture? What type of image calls for spreading as many colors as one can squeeze out of the EGA palette? He remembers a sunset he saw once at the Ranch, a rainbow-colored sky that seemed to spill onto the hills. And then he thinks of how bright the moon and the stars looked that time at the Observatory. The /Wheatfield with Crows/ and /The Starry Night/ come to mind, with all the punch Van Gogh managed to pack in those rough, almost childlike brushstrokes and a handful of strange colors.

With all of that in the shaker, he places a line for the horizon. And he piles layers of receding hills. He switches to the spare page and cobbles together a couple of brushes to plant the hills full of oak trees. He adds a rising moon and starts on a twilight sky. He has to figure out how the light should project on every fragment on screen. In his old /Zak/ background, the idea of Mars forced the reds on him: he was pulled into fire, sulfur, and rust. Here, the theme is day and night, and all forms of light: no pair of colors can fall out of place in this scene. He places broad patches and fringes of color, then smears and smudges to tear them apart, as if burning scraps of paper with a lighter. Wherever he finds a stretch of same-colored pixels, he stops to think how to break it. He wants this to be the least-compressible image in computing history.

He works on this twilight scene for minutes at a time, for days in a row. And when /Zak/ is finally done and he enters that weird purgatory in between projects, he turns it into his full-time job to make this picture as good as he can. And he makes it good. And he makes it art. He subverts the materials, just like he used to do with his pencils. It's hard to tell these are just 16 colors, the same old 16 colors.

Now that he leaped over its limitations, he's annoyed to see that a computer can produce art, that /he can make the computer/ produce art, and yet he is not allowed to use it, he's supposed to just shelve it.

The day after he's finished, before lunch, he puts the picture up as his screen saver, in silent protest. A protest against no one in particular. No one in his team, anyway. He's protesting Turing and Von Neumann, and George Lucas, and Ronald Reagan, for making it so damn hard to put art in a video game---to make art for a living.

When he gets back from lunch, Ron and David are having a heated discussion in front of his desk. Why exactly is it that dither can't compress? Is there /really/ nothing they can do about it? Wouldn't this be worth the extra disk space? This is LucasFilms material, they can't afford not to use it in their games.

A week later, David tells Mark that it turns out that dithering is very hard /but not impossible/ to compress. And that Ron is already working on their SCUMM engine to support it. This is now /his/ puzzle to solve. Mark will get to use dithering on his next project. In fact, until further notice, Mark's dithered backgrounds are the official house style. His stock just went up.

#+begin_export html
<br/><div class="org-center"><h3>II</h3></div><br/>
#+end_export

# TODO depending on how the warehouse scene ends up structure, it may be better to send this stuff over there
# maybe add back some of the extra remarks about ron made game

"Imagine that you can get off the boat and wander around, learn more about the characters, and find a way onto those ships." This is how Ron explains his pirate game to anyone that will listen.
He wants to do something fantasy-like without doing fantasy, which he hates. So he's doing a /Pirates of the Caribbean/ spoof. "You'll get to hunt for treasures, board ships, fight other pirates. That right there is the point of adventure games: to take part in the story, not just be told."

Ron may be a programmer by trade, he may be a decent writer, but game design is /his thing./ And he wants this game to be the ultimate realization of his design philosophy, what he's been preaching ever since /Maniac Mansion/. He even published it in a manifesto that became required reading around the office. /Why Adventure Games Suck/. It was mostly around game play, Mark couldn't make much of it, but one stuck with him: Ron wrote that the game should reward players for their accomplishments and, in graphic adventures, the reward is always a new piece of artwork, another location they get to explore. That's how Mark realized than his work is more than just a backdrop, more than content to fill the screen.

#+begin_export html
<br/><br/>
#+end_export

The Main House is a ten-minute walk from the Stable House. Mark mentioned he would go over to the library and Purcell tagged along. Nobody passes on an excuse to visit the Main House.

"What are we researching?", he asks as they leave the building.

"I want to look up some material for /Loom/. Some of that /Sleeping Beauty/ stuff he mentioned."

"Oh, so it's /actual/ research." People in the Games Group use /research/ as keyword for anything that blatantly isn't work. They ask /What are you researching/ to anyone they catch fooling around the office. "Well, I guess I could use some material myself."

Mark was assigned as Lead Background Artist for /Loom/. Purcell will do characters and animations. They are supposed to figure out how to turn an EGA adventure into a "living tapestry". What Eyvind Earle did with /The Sleeping Beauty/.

"So what do you make of The Professor?" asks Purcell. 'Professor' is what they've been calling the project lead. They brought him from Infocom, the struggling text adventure shop.

"He seems cool."

"Very cool."

"He certainly knows his game design."

"Oh, yeah."

"Maybe he's a bit too...”

"Professorial?"

"...well, I don't want to say /ambitious/, because,” Mark gestures towards the House as they pass by the Solarium, "who isn't around here?"

"He better be. /Be the best/, right?"

"...but, perhaps too much of an idealist. I can't believe /I'm/ saying this." In a sense, The Professor is like him: they are both invested in their work, they are driven by a desire to produce art. But Mark knows all too well that, despite his title, he isn't paid to make art. They pay him to produce backgrounds, conforming to a set of specifications. The art he has to smuggle, in spite of the business. The Professor, on the other hand, seems committed to breaking new artistic ground, and operates as if everyone is on board with him. Mark can't imagine any other company where they would let such a guy make whatever game he wants.

"I mean, a fantasy game?" Purcell continues as they walk across the hall, "/The Sleeping Beauty/? Tchaikovsky? Doesn't sound very LucasFilm to me."

"I like a good fantasy,” says Mark.

"More /Lord of the Rings/ than /Star Wars/. Or /Indiana Jones/."

"But, does it sound like /Maniac Mansion/ or /Zak MacKracken/?"

"...or /Sam & Max/?"

"Or /Sam & Max/, sure,” Mark concedes. Purcell is on a mission to convince everyone there /could be/ a game based on his comic. If he plants the idea on enough heads, someone will eventually ask him to make one.

"Well, I'd say it sounds like /Zork/, obviously... and /King's Quest/?"

"Ouch.” Mark pushes one side of the big door.

"Well, what do I know?” says Purcell, "I haven't played any of them."

"Me neither."

The Research Library is the work of a budding interior designer with unlimited budget: a crackling fireplace,
leather couches, Tiffany Lamps. A stained glass dome, bathing the room in amber skylight. A spiral staircase---featured in /Maniac Mansion/---leading to the upper balcony and to Lucas's office door.

There's a counter near the entrance. The librarian asks them what's the purpose of their visit.

"We're looking for research material for /Loom/,” Mark replies.

"He's looking for research material for /Loom/. I'm looking for research material for /Sam & Max/.”

#+begin_export html
<br/><br/>
#+end_export

<start narrating some of the chalice scene on screen
<what will be amazement in the regular public, here, in the stag theater at the tech building, is expected with anticipation
just sitting in there, <dim> faded lights and rounded corners, the smell and the sound of its silence, was a shown on its own
but watching a movie in there was an entirely different thing.
<this is theater is different from others, designed not for selling tickets or for entertainment. it's designed for study and observation.
<not only did he get to experience a film in the Stag theater, he gets to see an unreleased Spielberg-Lucas collaboration, with both of them sitting in the front row
Spielberg has allegedly been living in the ranch for the last couple of weeks, but it's ironically the longest stretch they went without seeing him around the Stable House
he's been secluded in the tech building, editing the film

<when the face disintegrates, the entire theater wakes up in standing ovation
this is the most accomplished ILM work on the movie, <first all digital composite>
footage had been circling around the campus for weeks so everyone has seen it in some way or another, everyone in the room feels part of accomplishment, and feers proud of it. this is why the skywalker ranch exists.
but the scene is a Games Group's favorite for special reasons
with just a few sleepless DPaint sessions
he single-handledly delivered the EGA equivalent of a million dollar ILM scene
<
wearing an indy hat
< and turns into acclaim for purcell, he bows

Spielberg's crunch to finish the film was mirrored at the stable house,
that's another thing, like this film premiere, that Mark was a privileged spectator to

<six months ago, a corporate memo supplied two separate but related pieces of news: LucasFilm Games secured the rights to make /Indiana Jones/ games; they had to come up with one based on the new entry Spielberg is shooting, to go out together with the theatrical release.

Management put other projects on hold and assembled a team with the most experienced designers to lead the new one. Mark was relieved, if a little worried, that they let him continue with /Loom/ while most of his colleagues switched to /Indiana Jones and the Last Crusade/. This was supposed to be a quick and dirty one, no room for his precious imagery and experimentation.

The team got a copy of the script and some early footage to go on.
<The designers struggle to follow the script while making the game interactive and fun. They aren't sure how to keep it interesting for the majority of players that will already be familiar with the plot. Artists are similarly constrained by the footage and the production stills.

some of the folks make a couple of visits to the set. Purcell comes back with a whip for "research purposes", which he incorporates to their afternoon sporting events.
<They borrow the Holy Grail and they take turns to drink coffee from it.

The Games Group walks back to the Stable House, excited about what everyone agrees is the best entry of the trilogy. They discuss the scenes that Spielberg ended up cutting from the movie, but that it's too late for them to remove. This accident suddenly becomes a selling point of the game.

Mark loved the movie but feels uneasy about the project.
< uneasy, perhaps because he felt a bystander to the production.
< but mostly because what he felt this experience <foretells> for the group
It feels rushed and derivative, all about the money. Once they lift the /Star Wars/ embargo, it's going to be hard to keep the suits from putting all hands on deck to milk Chewbacca.

#+begin_export html
<br/><br/>
#+end_export

<TODO monkey island packaging scene at a warehouse, at night

a couple of programmers were copying and labeling the floppies in the other room
purcell was riveting manuals, hint books and copy-protection wheels with
mark was in charge on putting everything in the box and ron took over for shrinkwrapping it

<after indy was done, they worked /Loom/ and /Monkey/ in parallel and they went out months apart. Not only was Mark Lead Background Artist for both games, but he was there from start to finish. Other than the creative process and the leadership styles of Ron and The Professor, /Loom/ and /Monkey/ melt into each other in Mark's head, and that shows in his backgrounds. To him, the island of Loom is the same as Melee island, the village and the town both below the same blue EGA sky.

<the most <picturesque> form of crunch
this was so different from their usual job that almost feels like a thematic going away party for the game, literally pushing it out the door
<the closer a video game could get to a hand crafted work: personally packaged by its designers

the silent fit of the cover in the box, the smell of fresh plastic and the warmth of the printed paper
even if it's mostly purcell artwork and his background merely made it to a little shot in a corner of the box and another in the manual
holding the box in his hands make the work he's been doing a little more real

#+begin_export html
<br/><div class="org-center"><h3>III</h3></div><br/>
#+end_export

The artists are gathered at the Technical Building for a demonstration. The scanner is a little tray, like a Xerox machine minus the printer, connected to a Macintosh computer. The scanner costs 10 times the computer, says the speaker.

"This new guy, Peter, is scanning for his /Monkey 2/ backgrounds,” says Purcell.

"Yeah?"

<There was a lot of movement around the office during the final /Monkey Island/ weeks. Mark was just too deep in crunch mode to notice. They seem to be growing faster, one or two employees joining every week. Everyone's got new PCs, too, with VGA cards and monitors. /Monkey Island/ is getting a sequel, and Mark isn't in it. He's stuck with the new /Indiana Jones/. In a typical corporate move, they renamed the Games Group to Lucas /Arts/ just as they move them out of the Ranch and into some office building. And they finally got the rights to make /Star Wars/ games.>

"The art is gorgeous, but it comes out all fuzzy on the other side of /that/." Purcell points to the scanner. "He has to go back and clean everything up in DPaint."

"He might as well do the whole thing in the computer, no?" says Mark.

"He's no fan of the mouse, though."

"Who is?" Mark snorts. "It's funny, I would've loved this a couple of years ago. My life would've been much easier."

"Yeah."

"Now it feels like a downgrade, you know? It's like with these VGA ports they are doing now."

"The 'enhanced' versions."

"More like the 'butchered' versions. They just use gradients for everything. It's like they want DPaint to do all the thinking for them."

"We're right here, you know?" someone mumbles at the back.

Mark continues: "It felt like we were finally getting somewhere, during /Monkey/. Now it's like starting all over."

"A technology is always at its best right before it's obsolete, man,” says Purcell.

"Who said that?" asks Mark.

"One Purcell."

"Wise fella."

After VGA and scanners it will be compact discs, or RGB color, or those 3D models they've been using over at the ILM basement. More colors, more space, more processing power, but also more complications, more time to master the tools. Forget about creativity or innovation, squeezing any art out of the machines. They'll be struggling just to stay competent. Before they know it, they'll have to start over with the hot new thing.

#+begin_export html
<br/><br/>
#+end_export

Mark walks towards the door, then turns. "I can't leave yet, I haven't finished packing." He looks at his desk. "I should put all this stuff in the box."

He picks up a pile of sketchbooks. "They are labeled by month and year." He puts the pile of sketchbooks in the box.

He picks up a worn out DPaint 2 manual. "There's a picture of an Egyptian mask on the cover." He puts the worn out DPaint 2 manual in the box.

He picks up a set of colored pencils. "I hand picked these myself, one for each of the 16 EGA colors. I guess I won't be needing them anymore." He puts the set of colored pencils in the thrash bin.

He picks up a /Sam & Max/ issue. "My favorite." He puts the /Sam & Max/ issue in the box.

He picks up an Indiana Jones action figure. "Indy." He puts the Indiana Jones action figure in the box.

He picks up a Chewbacca action figure. "Chewie." He puts the Chewbacca action figure in the box.

He picks up a /Sleeping Beauty/ reference book. "I never bothered returning this to the main house." He puts the /Sleeping Beauty/ reference book in the box.

He picks up a signed /Loom/ box. "It's signed by The Professor. I signed another copy for him." He puts the signed /Loom/ box in the box.

He picks up the box. "This box is too full, I can't carry it like this." He puts the box back on the desk. He walks towards the door, then turns. "I can't leave yet, I haven't finished packing." He looks at the desk. "Neat." He looks at the desk drawer. "Neat." He opens the desk drawer. He looks at the open desk drawer. "There's a piece of rope here." He picks up the piece of rope. "This might come in handy." He looks at the open desk drawer. "It's empty." He uses the piece of rope on the box. "Much better." He picks up the box. He walks out.

#+begin_export html
<br/><br/>
#+end_export

The Honda Civic drives out of the underground garage and turns around the Stable House. Lake Ewok glows and mirrors a dithered sunset. The car passes by the barn and the corral, then drives away from the security kiosk and onto the main road. A tall tree goes by, followed by two short ones. Then two short trees go by, followed by a tall one. Then two short trees go by, followed by a tall one. Then there are no more trees, just hills and grass and road. The hills smooth down into a plain, Californian unlikely, and the flat darker blue sky grows naked in turn.

The Honda proceeds and the road proceeds but then ends abruptly, like an abandoned flooring job. The car rides on  generic green grass for a while, approaching an edge, moving out of the picture. But not all of it. Half way out, it freezes. I can still make out the trunk and the glass, and the corner of a tire, sitting there, stationary.


#+begin_export html
<br/><br/><br/>
#+end_export

*** Sources
- [[https://www.bitmapbooks.com/en-ar/products/the-art-of-point-click-adventure-games][The Art of Point-and-Click Adventure Games]].
- [[https://www.youtube.com/watch?v=z1aVDael-KM][Classic Game Postmortem: LucasFilm Games' Loom]].
- [[https://www.filfre.net/2015/07/a-new-force-in-games-part-3-scumm/][A New Force in Games, Part 3: SCUMM]].
- [[https://www.filfre.net/2017/02/loom-or-how-brian-moriarty-proved-that-less-is-sometimes-more/][Loom (or, how Brian Moriarty Proved That Less is Sometimes More)]].
- [[https://www.filfre.net/2017/03/monkey-island-or-how-ron-gilbert-made-an-adventure-game-that-didnt-suck/][Monkey Island (or, How Ron Gilbert Made an Adventure Game That Didn’t Suck)]].
- [[https://www.filfre.net/2018/09/indiana-jones-and-the-fate-of-atlantis-or-of-movies-and-games-and-whether-the-twain-shall-meet/][Indiana Jones and the Fate of Atlantis (or, Of Movies and Games and Whether the Twain Shall Meet)]].
- [[https://bossfightbooks.com/products/day-of-the-tentacle-by-bob-mackey][Day of the Tentacle: An Oral History]].
- [[https://youtu.be/ri4_3P2Oh14?feature=shared][The Making of Monkey Island - Behind The Scenes]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-4-Loom/5][LucasArts' Secret History #4: Loom Developer Reflections]].
- [[https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-The-Secret-of-Monkey-Island/7][LucasArts' Secret History #5: The Secret of Monkey Island Developer Reflections]].
- [[https://scummbar.com/resources/articles/index.php?newssniffer=readarticle&article=1033][The Secret of Creating Monkey Island]].
- [[https://datagubbe.se/crt/][The Effect of CRTs on Pixel Art]].
- [[https://datagubbe.se/dpaint/][An Ode to Deluxe Paint]].
- [[https://www.superrune.com/tutorials/lucasfilm_ega.php][Lucasfilm EGA adventures: an appreciation]].
- [[https://web.archive.org/web/20030326051107fw_/http://lucasfans.mixnmojo.com/features/interview_stevepurcell.html][Steve Purcell Interview]].

*** quotes                                                         :noexport:

https://www.seattlepi.com/entertainment/movies/article/inside-the-secure-world-of-skywalker-ranch-1173112.php
https://www.youtube.com/watch?v=qRcxD3Tw0QU

"campus"

#+begin_quote
In the context of the Deluxe Paint 2 manual:

- **Hue** refers to the color itself, such as red, blue, or yellow. It represents the distinct characteristic that differentiates one color from another.

- **Shade** is a variation of a hue created by adding black, which results in a darker version of the original color. It implies a darker tone while maintaining the core characteristics of the hue.

- **Spread** in this context likely means a range or gradient of shades within the same hue. It provides a variety of subtle transitions from lighter to darker versions of the same color, allowing for more nuanced color work in digital painting.

So, the software allows you to create a gradient or series of subtle, darker variations of a single color, providing more depth and options in your artwork.
#+end_quote


#+begin_quote
whichever kind of gradient fill you choose, you can adjust its dither, the amount of random overlap between each shade
#+end_quote

#+begin_quote
Your copy of The Secret Of Monkey Island may have been hand-packed by Ron Gilbert himself. “Monkey Island was done and out the door to manufacturing. In those days you couldn’t just upload your game, you had to have someone make floppy disks and put them in a box,” Dave Grossman recalls. “The manufacturing facility didn’t have the capacity to meet the initial orders the next day. So a bunch of us from the games division worked the graveyard shift at this warehouse, staying up all night riveting code wheels, packing and shrink-wrapping boxes, and so on. It was the shortest and most awesome crunch ever in the history of games.”
#+end_quote

#+begin_quote
The smooth mode blurs already existing pixels together, smear smudges and smears existing pixels around (great for turning gradient fills into clouds).
#+end_quote

#+begin_quote
Spielberg wanted Donovan's death shown in one shot, so it would not look like an actor having makeup applied between takes. Inflatable pads were applied to Julian Glover's forehead and cheeks by Nick Dudman that made his eyes seem to recede during the character's initial decomposition, as well as a mechanical wig that grew his hair. The shot of Donovan's death was the first all-digital composite scene in a movie,[30] and was created over three months by morphing together three puppets of Donovan created by Stephan Dupuis in separate stages of decay, a technique ILM mastered on Willow (1988).[20] A fourth puppet was used for the decaying clothes, because the puppet's torso mechanics had been exposed. Complications arose because Alison Doody's double had not been filmed for the scene's latter two elements, so the background and hair from the first shot had to be used throughout, with the other faces mapped over it. Donovan's skeleton was hung on wires like a marionette; it required several takes to film it crashing against the wall because not all the pieces released upon impact.[28]
#+end_quote

*** tasks                                                          :noexport:
**** TODO review chalice scene + fx description
**** TODO rewrite/extend indy
**** TODO proofread again
**** TODO review outline/structure
**** TODO grammar
**** TODO proofread again
**** TODO review/cleanup quotes

*** chunks                                                         :noexport:
https://i.pinimg.com/originals/53/b1/f1/53b1f1a0961866d25ed578d345945dd4.jpg

http://iveneverdonethat.com/blog_files/skywalkerranch.html

<The one time Lucas showed his face in the Stable House, he said to the director: “Stay small, be the best, don’t lose any money.” That became their gospel, an easy way to answer the question /what would George want us to do?/,an easy way to settle arguments and make design decisions---and an evergreen source of jokes.
<the only part of this that affected him, Mark thought, was /be the best/, and that was how he intended to operate anyway, he didn't need a manager to tell him. he left to the suits, though, to figure out how his work and that of his teammates was supposed to be connected to the money making.

Mark had tried one of their games. while he was impressed by the thorough descriptions and the setting---it was like they made him the protagonist of a fantasy novel---he was quickly frustrated by the complicated gameplay and all the typing it involved. It was like the complete opposite of everything Ron and Gary were trying to do with the graphic adventures. They were comic books to infocom's novels. <despite marketing desperation to sell them as interactive movies

<purcell joked that you would go blind if you stared at Mark's screen for too long

every dithering stretch he could remember doing for /Loom/ and /Monkey Island/ would be unnecessary with this palette.  anything he may ever need seemed to be contained by these new 256 colors
  as was often the case when he is in between projects, he is free to spend his time however he sees fit.
  he decides to work on a new take of his legendary sunset landscape, to test drive the new palette. it would be a good way to try the DPaint gradients that were useless on VGA.
but this little project would reveal a new form of anxiety: he doesn't know what he's doing anymore.

/Loom/ was praised but considered too /avant garde/. Nobody asked The Professor for the sequels he had planned, and he was too burned out to fight for them.

such a typical corporate move, rebranding to LucasArts just as they move them into an insurance office building full of cubicles, a bunch of boring technicians churning out Star Wars flight simulators
no more rebels, just stormtroopers

<at first it felt like an independence day to mark they would be free at last from their EGA jail
but now he wasn't sure how to adapt his work process to a 256 palette. it wasn't driven by the color planning anymore.
These new computers felt like a career reset to him.

in the quite months they would take long lunches or hikes through the hills or they would toss a softball around in the field out back, so they ended up working late to make up for the time most of the people on the team was in their early twenties so they didn't have anywhere better to be anyway

so as the project deadlines arrived, they just kept working late, only skipping the long breaks during the day.
weekends at the ranch, though, were off-limits. they would let him take his computer back home on fridays to work during the weekend


#+begin_export html
<br/><br/>
#+end_export

The memo sits on his desk:

#+begin_export html
<div class="center-block">
<p>The Return of the License</p>
<p><small>LucasArts Episode I</small></p>
</div>
#+end_export

He doesn't read it.

#+begin_export html
<br/><br/>
#+end_export

Some times The Professor gives Mark and Purcell story prompts and asks for concept art in return, but more often he wants /them/ to come up with stuff he can use for inspiration, based on the reference material and a short treatment he handed to them. This concept art is Mark's first traditional illustration job since he joined the company.

He pulled everything he could get from the library on Disney, /The Sleeping Beauty/, Eyvind Earl, and medieval tapestries. He plays the movie on the Media Room, frame-freezing to take notes and make sketches. Mark delivers two or three drawings a week, using his now legendary pencil technique. Most of the times, The Professor comes back with notes to refine an idea, or a request to try again, but occasionally he takes a drawing and uses it to write a segment of the story. In those cases The Professor asks Mark to convert his illustration into an EGA background, one he can wire up in SCUMM to try dialog and descriptions.

The Professor set up similar work streams for animation and programming and, most importantly, with the sound department. Music and sound will feature in /Loom/ more prominently than in any other LucasFilm game.
Which is convenient, considering that the Ranch houses the best sound engineering facilities in the world.
For the sound engineers, it's Tchaikovsky instead of Eyvind Earl.

The Professor sees games as a novel art medium, and he wants to use all of its materials to that end: sound, music, backgrounds, animation, story, and dialog. He made sure everyone on the team picked up on his vision and gave them freedom to figure out how to best realize it with their tools.
Coming from a rather lonely experience writing text adventures, he's betting on collaboration to unlock this deeper storytelling experience. He's so driven by this craftsmanship ideal that he incorporates it to the story, with the protagonist visiting different Guilds over the course of the game.

Mark came up with the idea of using colors to represent each Guild, giving a distinct quality to each section of the game: the striking emerald of the Guild of Glassmakers, the softer pastoral greens of the Guild of Shepherds, the Stygian reds of the Guild of Blacksmiths and the saturated blues and purples of the Guild of Weavers. This is a feat he imposes to himself, with the EGA palette allowing for one or two shades of each hue, the rest having to be mocked with dithering and other tricks.

For the first time, he won't be adapting someone else's work. The latest version of the SCUMM engine not only supports Mark's dithered backgrounds, but introduced character scaling to represent depth, enabling him to enhance his scenes with perspective. He knows the tools and he's free to push them where he wants to go.

#+begin_export html
<br/><br/>
#+end_export


They are starting a newsletter to put in the boxes---they already interviewed Ron, and asked Purcell for a comic strip


the art deco theater is only second to the library as a legendary ranch location
mark had visited and seen some footage but never an entire film

a room designed to observe / for observation

not for selling tickets or enjoying a film, but to observe, and listen.
you can hear the silence of the footsteps and the seats.
a place that sounds and smells of silence
one more interesting to mark than Harrison Ford rolling and tumbling on screen, again


<People say that /Monkey Island/ marks a new chapter for the Games Group, but to him it was more of an end. Like the culmination of something. The tools were at their best and for the first time everybody, the designers and the artists, seemed to know exactly what they were doing.

remark about kung fu movie
<TODO add some monkey production notes
<remarks about the box (purcell artwork, read the box description, removed dog)

<this well oiled assembly line
this seemed like a good metaphor of how team gelled during the production of the game
brainstorming, lunch jokes made it to the game
