---
title: Local-First and Personal Software
date: 2024-08-12
layout: post
lang: en
tags: [software]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

There's a lot to be frustrated about contemporary software and the modern web. (If you are a software user and you are not frustrated, you can safely skip this article.)
#+BEGIN_EXPORT html
<br/>
<div></div>
#+END_EXPORT

There's a lot to be frustrated about software, the cloud, and Big Tech, especially if you've been using computers long enough to remember how it used to be. It was worst, of course, in some ways, more limited and primitive, but much better in others. And that's the thing: we probably didn't notice that we were making this trade-off---not before we were all-in.

We gave up privacy and control in exchange of convenience and information sharing, but we also gave up performance and offline access, and data durability and ownership. There are things we can do now---things we /need/ to do now, like video conferencing and real-time collaboration---that couldn't be done with traditional desktop software. But for the things we /could/ do back then, it's likely that the overall experience has gotten worse, and it seems to be getting worse all the time.


#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

There's a lot to be frustrated about, many problems with contemporary software and many possible ways to address them:

# FIXME maybe not mention and move here
- Local-First Software. Its [[https://www.inkandswitch.com/local-first/][original paper]] superbly describes the transition from desktop to the cloud, what we lost along the way, and how we could get it back.
- The idea of replacing platforms with protocols, <NOTE>.
- Self-hosted Open-Source software.
- P2P networks, like BitTorrent and the InterPlanetary File System.
- Federated networks, like those powered by [[https://en.wikipedia.org/wiki/ActivityPub][ActivityPub]].
- The [[https://www.jvt.me/posts/2019/10/20/indieweb-talk/][IndieWeb]], <Note | online presence, breaking away from silos but not isolating from them>.
- [[https://maggieappleton.com/home-cooked-software][Home-Cooked Software]], <NOTE>.
