---
layout: post
title: "Álgebra"
date: 2020-09-08
tags: [ficción, literatura]
favorite: true
lang: es
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

X lee relatos de muchos autores. En cierto punto de su itinerario lector,  se cruza con A y lee uno de sus cuentos (A_{1}), que le gusta mucho, aunque todavía no se da cuenta. Según X, una historia le gusta cuando se encuentra evocando retazos de ella —una situación, una descripción, una imagen— meses o años después de haberla leído. X todavía no lo sabe, pero A_{1} le gustó mucho. Lee otros relatos de A que no le gustan tanto y finalmente lo deja atrás.

Sigue leyendo y, en cierto punto, empieza a escribir sus propios cuentos. Primero escribe anécdotas autobiográficas, indescifrables para cualquiera que no sea él. Con trabajo, las mejora hasta hacerlas comprensibles pero no dejan de ser meras transcripciones de sus recuerdos; la suya no es una vida excepcional y X carece de los recursos técnicos para dotar de interés a lo cotidiano. Con trabajo, sin embargo, adquiere los recursos técnicos suficientes para reconocer, al leer sus cuentos, que son malos.

En una segunda etapa se despega de su vida a la hora de escribir. En muchos casos, incluso, se despega por completo de la realidad, es decir, hace incursiones en territorios extraños y fantásticos. Alguna idea \mdash{}una situación, una descripción, una imagen\mdash{} surge en su cabeza y la escribe, y después escribe un cuento alrededor de ella. A veces, aunque con frecuencia decreciente, al terminar un relato y releerlo se da cuenta de que es un plagio, que reprodujo algo que había leído antes; otras, que reformuló algo que él mismo había escrito ya.

En cierto punto de su itinerario escritor, X comienza a evocar retazos de una historia, fragmentos que acumula en su mente como piezas de un rompecabezas sin que pueda precisar dónde la leyó ni quién es el autor. X no sabe, como nosotros, que la historia que evoca corresponde a A_{1}, el cuento de A, así que por un tiempo se dedica a revolver su biblioteca y repasar lecturas juveniles tratando de rastrearla. La historia permanece inamovible, se le aparece en sus noches de desvelo, toma una forma cada vez más nítida, mejora con cada repetición. X querría leerla de nuevo en vez de tener que reescribirla incesantemente en su cabeza pero agota los recursos que tiene para encontrarla \mdash{}llegando incluso a dudar de su existencia\mdash{} y se resigna a ponerla él mismo en papel para dar por terminado el asunto, es decir que escribe su propio cuento (X_{1}).

X envía X_{1} a concursos con la esperanza de que algún jurado le marque amablemente su falta, pero no solo nadie lo hace sino que el cuento se termina llevando un premio. X_{1} es incluido en una antología de autores jóvenes y es reproducido en revistas y diarios latinoamericanos y en algún que otro blog. Contra sus expectativas, ningún lector, editor ni jefe de redacción le insinúa nunca un plagio.

Un poco por presión de su editor pero también por cierto impulso autodestructivo, X incluye X_{1} y hasta le pone el mismo título a su primera colección de relatos. El libro es bien recibido y, a estas alturas, X empieza a convencerse de que la historia es completamente suya, al menos en la medida en que una obra puede legítimamente pertenecer a alguien.

No es ningún lector, crítico ni periodista quien acaba anunciando el plagio sino el propio A, más precisamente su abogado (723), en una carta documento donde se acusa a X de copiar A_{1} en su trabajo publicado recientemente. X queda menos preocupado por la intimación que aliviado por poder, de una vez por todas, releer aquella historia que lo persiguió durante tanto tiempo. Corre a una librería y compra un libro de A que incluye A_{1} y lo lee en un café cercano. Pero lo que lee no le gusta. No soporta la manera en que A abordó el material; para X, A_{1} es un desperdicio: toma una buena historia, /su/ historia, y la hace pedazos.

X y A se embarcan, entonces, en su juicio, observados con atención por la comunidad literaria que, como en todos lados, gusta de tomar partido: los que están con X, el autor de moda, la joven promesa, y los que están con A, una institución en decadencia, una vieja gloria que apenas sigue escribiendo, etc. A los dos les viene bien la publicidad.

X puede pagarse un buen abogado por lo que a la larga termina ganando el juicio, aunque prefiere pensar que el que ganó fue su cuento por sobre el de A. Con todo, la experiencia es suficientemente traumática (y su editor lo suficientemente insistente) para que X decida tomarse una licencia de su "inhibición autobiográfica" y se explaye largamente sobre el litigio en su primera novela (X_{2}).

Lo que ni X ni su editor tienen en cuenta es que A, si bien en el ocaso de su carrera, es un escritor de oficio y le toma poco tiempo terminar A_{2}, su nueva novela, en la que se explaya largamente sobre el litigio con X. A_{2} es un éxito inmediato de ventas \mdash{}en la medida en que una novela sobre el mundo literario puede serlo. La crítica no tarda en hacerse eco del esperado regreso de A, el viejo lobo de mar, el fénix que resurge de las cenizas de su módico escándalo judicial, etc.
Para cuando X_{2} llega a las librerías, un par de meses después, X ya fue reducido a personaje de una novela de A. X_{2} pasa mayormente desapercibida para el público, con la notable excepción de 723, quien no pierde la oportunidad de enviar una segunda acusación de plagio.

Y aunque fue A quien inició el pleito, la prensa lo relata como un intento de X por recuperar la notoriedad: se trata de una continuación mediocre del juicio anterior, una pobre imitación de los hechos que A narra en su novela, reforzando así la idea del plagio, esgrimida astutamente por 723.

Con el viento en contra, como si la opinión pública fuera en sí misma una sentencia, X pierde el juicio, pierde su dinero, pierde para siempre su interés en la literatura, etc.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
 #+END_CENTER

(α pone punto final y se pregunta si esta historia se le acaba de ocurrir o la leyó en alguna parte).
