---
title: Are We Living in a Simulation?
date: 2024-09-05
layout: post
lang: en
tags: [software]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

[[https://ludic.mataroa.blog/][Ludicity]] blog author lucidly uses the word 'cosplay' to characterize our industry's dysfunction:

#+begin_quote
It feels as if 95% of engineering teams are cosplaying as being whatever we imagine real engineers to be. (...) This explains things like why I've seen teams at major employers that store <4 kB of logs a day in fucking DynamoDB - they just read that this is what people do and want to do the cosplay better.
#+end_quote

#+begin_quote
The industry is so primed with nonsense that we effectively have two industries. We have a real engineering market, where people are fairly serious and gather in small conclaves, and then a gigantic field of people that are cosplaying at engineering. The real market is large in absolute terms, but tiny relative to the number of candidates and companies out there. The fake market is all people that haven't cultivated the discipline to engineer but nonetheless want software engineering salaries and clout.
#+end_quote

The wording hits a nerve; I immediately associated these ideas with what I've been thinking and writing about over the last couple of years.

*** Startup Cosplay
The quotes above focus on the engineering side of things. I see inefficiencies everywhere, but I've seen this tendency to cosplay most consistently in startup founders and product owners. They seem to make a cult of working tactically and reactively, of always showing a sense of urgency, moving towards a vague vision but with no concrete plans or priorities. It's as if the tactical attitude---the long hours, the constant changes, the lack of direction---was the only way a startup is supposed to work. As if it was less about achieving some goal than about looking the part.

This is perhaps explained by the fact that startups live on investor's money. Their survival is less concerned with accountability and effectiveness than with making a convincing case for investors to keep pouring money in the company.

*** Imaginary Software
How does this startup culture affect the work of software engineers?

First, there's pressure to adopt a tactical programming mindset, of always choosing the shortest path to completion for a given task, never stopping to think about the long-term health of the systems. The ideal startup employee is what John Ousterhout calls the /tactical tornado/, <a programmer that ...> like there is no tomorrow. Which is fitting, since for startups /there usually is/ no tomorrow.

<Second, the usual focus on growth as the primary goal of the product,
<culturally, not baking scalability may be interpreted as a lack of committing, as not believing hard enough in the success of the vision.

But even when engineers manage to ignore external pressures, if they strive to keep things simple and produce the best design they can under the given constraints, there's the problem that early startup software is usually greenfield software built on quicksand. As Michael Nygard puts it in /Release it!/: the beginning is when teams are most ignorant about the eventual structure of the system---the eventual needs of the product--- and yet it's when some of the most irrevocable decisions must be made. Startup engineers are building on assumptions that will be tested, at best, years later, when they likely won't be around to deal with the consequences of their decisions.
Since most startups fail, these assumptions may never get tested at all. From a technical standpoint it doesn't really matter how they design the system; there's nothing at stake: they are building imaginary software.

*** Legacy Systems
On the opposite end of the spectrum to startups we have stable companies, running systems in production, with users; they have a business model if they aren't already profitable. They know what problem they are solving and who they are solving it for.

Systems running in production are systems already designed. Such designs may not be documented, they may be implicit; they may not have individual authors but resulted from years of uneven contributions, or they may have authors that have long left the scene. This is what we call legacy systems.

Legacy software is not a problem in itself, only that it's very hard to relate to software engineering as discussed in blogs and books and conferences. It's a less glamorous activity than designing beautiful interfaces or envisioning sophisticated architectures and scaling to the world. The day to day work is maintenance: bug fixing, operations, small feature extensions, reading and documenting old code. Change is slow and difficult, and often hard to justify economically.

Any long-lived software system must become legacy. Legacy software should be our default. It's only by historical accident that it isn't.

*** The Dilemma

Indulge, dear reader, one final exercise in reductionism.

I posit that it's statistically unlikely for an engineer to get a job working on a system that isn't either imaginary or legacy software. There is no middle ground. If the product was ever going to be successful, it would already be successful; if /it is/ successful, then it comes with baggage.

This is the dilemma. Software engineers must choose between imaginary software---where they get to envision and design and architect, where they have agency, but where their decisions are ultimately irrelevant---and legacy software---where most design decisions have already been made, and change is slow and heavily constrained.

The software engineer has to choose one.

I made my choice.
