---
title: Augmentation / Replacement
date: 2025-05-01 13:40:49
layout: post
lang: en
tags: [ai, software, programming, emacs]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

I settled on a convenient way to integrate LLMs to my workflow[fn:3] and I've been using them increasingly for work, personal projects, and writing. It fills several roles for me:

- <a sophisticated search engine>
- <ultimate rubber duck>
- <slippery sloppy junior developer>

Beyond these concrete use cases, I see much potential in its flexibility: you can come up with arbitrary ways of integrating it to your tasks. I believe it helps that I use Emacs as my "center of computing operations": since I'm aware of my coding and writing habits, I can be deliberate and precise about to improve them with such a malleable tool.

I think I unlocked some of that extra ambition Simon Willison keeps talking about: that of tackling projects that I would otherwise skip not because I couldn't do them but because they wouldn't be worth the effort[fn:2]. I can see myself building more sophisticated workflows, more personal tools; I can see the technology getting good enough that I can trust it more, and rely less on googling and source checking; I can see myself using voice instructions, letting it run commands in the terminal and more.

I don't tend to get excited about technology in and of itself, and LLMs aren't the exception, but if I filter all the noise---which is loud---and try to be objective, I can accept that already in their current incarnation they may well be the most powerful human augmentation tool in the history of computing[fn:1].

But for all its current and future power as a human augmentation tool, I'm convinced that generative AI is and will continue to be a mediocre human replacement for anything resembling intellectual and creative work.


#+BEGIN_CENTER
\lowast{}
#+END_CENTER

*** scraps
<The times they are a-changin' but not in the way enthusiasts seem to believe, at least not from where I'm standing.

*** Notes

[fn:1] If anything, I'm more impressed by the technology evolution that led to millions of humans producing the digital information necessary to train the models, than by the models or their underlying technology.

[fn:2] I recently embarked on a big emacs config overhaul despite still being terrible at emacs lisp and with superficial knowledge of emacs internals

[fn:3]
