---
title: My retrogaming handheld
subtitle: BATLEXP G350 setup notes
date: 2026-02-20T13:53:16-03:00
layout: post
lang: en
tags: [games]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

** intro

0. [@0] A few years ago, I setup a retro gaming console in a raspberry pi, with recalbox. Using that I cleared a lot of classics from my backlog: /A Link to the Past/, /Final Fantasy VI/, /Chrono Trigger/, /Suikoden II/, /Final Fantasy Tactics/. I started many others that I didn't stick with, and I upgraded the rapsberry pi, and I tried other emulation station distros, but eventually stopped using it. Mostly because it was a lot of hassle to plug into my old tv and pair the bluetooth controller when I ocassionally wanted to play.
1. Months ago I learned a few interesting facts from a [[https://www.421.news/en/r36s-retro-handheld-taking-over-2025/][local magazine article]]:
   - Now there are cheap chinese handheld consoles running the same kind of emulation linux distributions that I used in my raspberry pi.
   - The most common of these is the R36S.
   - Those can be bought online (through AliExpress) and sent over to my country (which is not always the case, depending on what year it is).
   - In addition to traditional emulators, these handhelds support this amazing thing called [[https://portmaster.games/][portmaster]], which brings a bunch of linux ports of games, both classics and newer indie games
2. I made my mind about buying one but didn't right away. Instead I started lurking subreddits like [[https://www.reddit.com/r/R36S/][r/R36S]], [[https://www.reddit.com/r/SBCGaming/][r/SBCGaming]], and [[https://www.reddit.com/r/BATLEXPG350/][r/BATLEXPG350]]. There I learned a new batch of facts:
   - Even though they already are a knockoff of a knockoff console, there are good and bad R36S depending on which seller you buy them from.
   - The pre-intalled OS, ROMS, and SD card suck and you should change all of these.
   - There are actually better quality options in the same price range as the R36S.
3. With all this info I decided to buy a BATLEXP G350 (yes batle with a single T) for 50 dollars, and it arrived about a month later.
   - Buying guide [[https://handhelds.wiki/BATLEXP_G350_Buying_Guide][here]].
   - After using it for a while I noticed the form factor can be a bit demanding on the hands, so it's probably a good idea to also buy or 3D-print a grip for it.
     - Also, since I'm enjoying this so much I might end up just buying another console with an horizontal form factor.
       - Currently on my radar: Anbernic's [[https://anbernic.com/products/rg40xx-h][RG40XX H]] and [[https://anbernic.com/products/rg353ps?variant=43876118528257][RG353PS]]
   - This is high quality enough to also warrant a storage case. I didn't buy one but I repurposed one I got with an 8BitDo controller.
4. This is a very fun hobby that's completely orthogonal with the actual playing of video games. The fun comes from:
   a. setting up the system
   b. making plans or interesting games to try, and get them working on the console

[TODO screenshot]

** setup

1. As with the R36S, I read recommendations of changing the stock OS and romset from the BATLEXP.
   - I went with the ArkOS distribution; another popular one is Pan4Elec.
   - I followed [[https://www.youtube.com/watch?v=eyih2i5bWYk][this]] setup video from the [[https://handhelds.wiki/BATLEXP_G350_Guides_Tutorials_HowTos][handhelds wiki]]
   - Since I'm on MacOS I used Balena Etcher instead of Rufus (~brew install --cask balenaetcher~)
   - I flashed the RG351MP image (from the [[Arkos image][ArkOS wiki]]) into a 128gb SD card
   - I overrode the .dtb and Image files in the BOOT partition with those linked in the video
     - Later I saw some issues with the right stick which I fixed by installing [[https://www.reddit.com/r/BATLEXPG350/comments/1kjjf13/arkos_right_analog_stick_fix/][these other files]]. Both look the same so maybe didn't copy it right the first time?
     - Later later I had the console freeze on a black screen on boot, and I was able to fix this by overriding the dtb and Image files again.
2. I downloaded the base and 64gb versions of the tiny tiny set go from the internet archive and manually distributed the roms to the corresponding dir in the EASYROMS partition of the SD card.
   - This provided a good baseline of curated ROMS that includes most of what I'd like to play without cluttering the collection.
3. On restart I noticed a bunch of ._ prefixed files in the collection. There's a handy builtin tool in the options menu to remove them.
4. I Installed portmaster from [[https://portmaster.games/installation.html][this]] instructions.
   - Since the BATLEXP has no wifi connection, I had to use the Install.Full.PortMaster.sh
   - I cleared the preexisting portmaster files in EASYROMS/tools/
   - Back in the console, I run the script from options / tools / Install.Full.PortMaster.sh
   - After this I can add new ports by placing them in EASYROMS/tools/PortMaster/autoinstall

5. I applied some hotkey re-mappings as recommended in the setup video
   - Also some extra ones to handle the save state slots
   - Note that these only apply to retroarch managed ROMS, other emulators like the PSP one, use the default keybindings.
6. Since the BATLEXP has no internet access, and the tiny tiny set go images would have to be configured manually in the gamelist.xml, I have no preview cover images in the menu.
   - I've seen in the [[https://www.skraper.net/][Skraper tool]] recommended for this, but it doesn't run on MacOS and I couldn't be bothered to try it on my windows laptop, so no cover images for now.

** games

- interesting games:
  1. doom, obviously
     - but also wolf and quake
     - also doom 64 which I understand it's different enough, although I didn't get it running
     - poom
  2. prince of persia portmaster
     - also its cousin flashback. it has a modern portmaster but couldn't get it to look good. the genesis one looks very slick though
  3. winning 2002
     - also PES 2004
  4. mario tennis gba
     - virtua tennis psp
  5. xeno crisis. this one warrants some remapping to leverage the analog stick
     - smash tv arcade
  6. Shovel Knight
  7. outrun portmaster.
  8. Metroidvanias
     - castlevania psx
     - super metroid snes
  9. rpgs
     - earthbound -> maternal bound?, mother 3
     - dragon quest III or V
     - golden sun
     - pokemon unbound, emerald
     - tactics ogre
  10. n64 classics: ports zelda and sm64
  11. GTA (3/VC)
  12. Aracde classics
      - turtles in time (but SNES)
      - Turtles 1 arcade
      - also simpsons
      - schredder's revenge
      - metal slug (X and 3)
      - sunset riders arcade

- now that I set up my console and spent a couple of days choosing and configuring games, it's almost as if I'd already played them. I can safely move one to other activities.
