---
title: "Desde Monkey Island hasta Half-Life: cine multimedia en la PC"
date: 2026-05-21T09:02:27-03:00
layout: post
lang: es
tags: []
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

Cada vez que la innovación tecnológica abrió el camino para nuevas formas de arte, ese medio naciente atravesó un período de búsqueda de identidad, de definirse por comparación con lo conocido, con aquello que vino antes. Los videojuegos no fueron la excepción. En el caso de los juegos de computadora, surgidos en terminales de texto a finales de los setenta, es normal que el primer espejo haya sido la literatura. Así explicamos que, ya probada la fórmula de /Colossal Cave Adventure/, empresas pioneras como Infocom hablaran de /ficción interactiva/, tildaran a sus programadores de /autores/, y convocaran a figuras como Ray Bradbury y Douglas Adams para ponerle la firma a sus juegos. Por unos años se habló del /bookware/ y parecía que cualquier editorial estadounidense medía las posibilidades de meterse en el entretenimiento por computadora.

Pero como Ken Williams probó al sumarle gráficos a la ecuación, los videojuegos estaban destinados a ser experiencias no meramente interactivas sino /audiovisuales/. La década que siguió a /King's Quest/ y /Maniac Mansion/ fue la década en que el entretenimiento por computadora buscó inspiración en las técnicas y las formas de producción de Hollywood. Esa pretensión de imitar al cine asumió muchas formas, según las capacidades del hardware de turno y el ingenio y la exuberancia con que los diseñadores supieron aprovecharlas. Revisemos algunos casos interesantes.

** Amiga y Cinemaware: vista previa al futuro
- pc vs macintosh, iphone vs android en los 80
- tercero en discordia: amiga
- la vision cinematografica de cinemaware
- defender of the crown
- it came from the dessert
- muerte por falta de espacio

** Prince of Persia y la experiencia cinemática
- intro mechner: técnica en vez de tecnología
- prince of persia, rotoscoping
- secuela pero herederos: flashback, another world
- también de francia: alone in the dark, lynch hitchcock, survival horror

** Myst y la revolución multimedia
- vga y sonido: la pc se va poniendo al día con la amiga
- el problema seguía siendo el espacio. todos sabían que lo que se venía era el CD, la pregunta era cuando. pusheado por la industria muscal
- consolas dubitativas
- huevo y la gallina: algunos juegos con upgrades (sonido, talkies). empiezan a aparecer celebridades. exclusivo en CD era una apuesta demasiado arriesgada
- consorcio microsoft sony y otod
- myst, killer app
  - (TODO como se decidieron a hacerlo cd?)
  - mundos interactivos no videojuegos, similar a adventure. historia.puzzles accessorios

** Full-Motion Video: el espejismo del cine interactivo
- 7th guest: la otra killer app, mansion david lync, aplicaba la técnica de pasar videos entre puzzles
  - TODO revisar wing commander
- x files, ripper, hollywood actors (christopher walken, chris lloyd, buscar más)
- asi como a mediados de los 80 había apostado fuerte por la PC, Ken Williams había apostado fuerte por el CD-ROM. En ambos casos tuvo que esperar pero el tiempo le dio la razón.
  mientras su Sierra seguía publicando un éxito atrás de otro, como siempre impresionantes desde el punto de vista audiovisual pero desparejos en jugabilidad, Williams ya se preparaba para lo que vendría una vez que el CD se <estableciera>
  - inversion  en estudio, storyboards dirección artística
- phantasmagoria gabriel knight
- venden pero son juegos malos, pronto perdieron favor de la crítica

- quizas justicia poética que el mejor exponente de este estilo haya venido de la mano de Jordan Mechner, que una década antes se había fundido tratando de exprimir la última gota de jugabilidad a su gastada apple 2
  - pudo cumplir su sueño frutrado de director
  - no cayó en la fácil de sierra de pasar videoclips entre puzzles. en vez de eso volvió a apelar su técnica favorita, el rotoscoping, pero esta vez con la tecnología a su favor. grabó a sus actores maquillados para aumentar el contraste y después los metió en las secuencias in game y en clips en los que parecen dibujos animados más que actores berreta.
  - el juego es un murder mystery arriba del orient express (doble guiño a Agatha Christie y Hitchcock), situado en medio del caldo geopolítico de una europa al borde de la primera guerra mundial
    una inusual aventura con perspectiva 3D que se parece en movimiento al myst
    en tiempo real, que también incluye un control para avanzar y retroceder el tiempo, para poder explorar lo que pasa en el tren en distintos lugares a la vez
  - ¿suena complicado? Lo es! el juego es genial pero dificilísimo. de más está decir que fue carísimo de producir y que la inversión no se recuperó. Solo el curioso estado de la industria a mediados de los 90 puede explicar que hayan intentado semejante empresa delirante. Mechner quedó en bancarrota, vendió el estudio que había creado específicamente para el juego y suspendió sus pretensiones de carrera en el cine. Pero qué juegazo, Jordan!

** LucasArts y las aventuras animadas
- Ya con las licencias de Star Wars disponibles y aprovechando el boom del CD-ROM, LucasArts (antes conocida como LucasFilm Games) le dio el gusto a su público: Rebel Assault combinó acción con secuencias directamte extraídas de las películas, inaugurando una nueva dimensión para la franquicia.

<por el lado de las aventuras el cine también estaba presente: con la presencia de Spielberg llamando por teléfono para pedir indicios, más juegos de indiana, y produciendo una aventura de exploración espacial (interesante pero que no está a la altura del resto de la producción del estudio)

Pero mucho más interesante que la búsqueda directa de conectar con el cine, (un poco burda en otros estudios), son las posibilidades que la evolución tecnológica abrió del estudio.
- EGA: Indiana Jones, Loom, Monkey Island, pixel art a mano
- Lechuck's revenge, arte escaneado. aprendizaje: muchos colores dan imágenes pixeladas
- Day of the tentacle fue por los colores planos y esa elección artística dio la clave en el tono del juego: esta secuela de Maniac Mansion no miraría al cine de horror sino a los dibujos animados <los cartoons de X>.
- situada en la misma mansión pero estructurada como una aventura de viajes en el tiempo, el jugador controla a tres protagonistas en tres épocas distintas. Los puzzles requieren colaboración a la distancia: talar un árbol en el siglo XIX para descolgar a un personaje en el siglo XXI.
DoTT puede bien entrar también en la categoría de "aventura perfecta" de Secret of Monkey Island, un juego que ejecuta impecablemente todo lo que se propone y de alguna manera la culminación del estilo point-and-click, la exploración de los límites de la forma que ellos habían inventado. <En todo lo que vendría después estaría marcado por un mandato de innovar para no quedarse atrás antes que profundizar en formas establecidas>

- Sierra seguía haciendo lo suyo, juegos peor diseñados pero más pochocleros que LucasArts, pero a esta altura la aventura gráfica era un género bien establecido y (por el momento) redituable, así que aparecían nuevos jugadores. Quizás el más meritorio sea <revolution games>, un estudio británico que con su /Broken Sword/ no solo dio un paso adelante en el estilo de animación 2D sino que con una interfaz reducida y las descripción en off del protagonista profundizaba la experiencia de película interactiva. Toda la personalidad de este juego queda a la vista en la secuencia inicial:

- Pero el ápice de este estilo de aventura vendría, cómo no podía ser de otra forma, de LucasArts y de Monkey Island. Para la tercera entrega de la franquicia, ya sin el autor intelectual Ron Gilbert ni su heredero Tim Schafer ---ocupado en otros proyectos--- pero con todo el presupuesto y el capital artístico del estudio puesto al servicio de una experiencia multimedia. Curse of Monkey Island ahora tiene escenarios de 256 colores ya sin artefactos del escanner, Guybrush y Lechuck ahora tienen voces, todo se ve y se siente como una película interactiva de Disney: [video]

<Curse of Monkey Island es uno de los pocos, probablemente el último, seguramente el mejor, juego 2D AAA, la muestra de una dirección no tomada por la industria.

CoMI se ve y se juega como una película de disney, pero una de los 60 o de los 80. En los 90 Disney caía en picada y había sido destronado por Pixar. Como habían predicho sus directores, una década antes cuando todavía formaban parte de LucasFilm, la gente iba ahora al cine a ver películas generadas por computadora. Si hasta los dibujos animados eran ahora en 3D, ¿qué le quedaba a los videojuegos?

** Grim Fandango y la amenaza 3D

- doom: antítesis
- full throttle
- grim fandango
- flop
- half life: síntesis
