---
title: Diario de Lechuck's Revenge
date: 2024-11-16 11:44:19
layout: post
lang: es
tags: [videojuegos]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es


Me postergaron la fecha para empezar con el trabajo nuevo. Otra semana libre después de muchas.
Busco algún juego para llenar el tiempo, algo que pueda empezar y terminar en unos días o que, en todo caso, pueda abandonar sin culpas. Veo /Lechuck's Revenge/ en mi lista de Steam y lo instalo impulsivamente.

Deben hacer casi veinte años desde que lo jugué por última vez. No por falta de interés sino por logística: para repasar la saga /Monkey Island/ me resultaba más ordenado empezar por el primero y solo después pasar a la secuela. En estas dos décadas debo haber empezado /The Secret of Monkey Island/ cinco o seis veces y siempre lo abandoné al completar el primer capítulo. Entonces a /Lechuck's Revenge/ no volví nunca.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER


Por buenas que sean, las aventuras gráficas no se prestan bien a jugarlas por segunda vez. El motor son los puzzles, y una vez que conocés las soluciones se hace difícil sostener el interés, lo que queda es una trabajosa película interactiva. Pero /Lechuck's Revenge/ es tan vasto, sus puzzles tan complejos, que el efecto se atenúa. Todavía me acuerdo de algunas soluciones ---las del principio, las obvias, las que más trabajo me dieron--- pero tuve oportunidad de olvidarme de otras.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Como adulto, programador, veterano de aventuras y de libros, reparo en otros detalles, en la narrativa, en el diseño.
Los gráficos de la /Special Edition/ son una aberración y me atengo estrictamente a jugar en modo retro, pero hay algo que sí vale la pena del remaster: el audio con comentarios de los diseñadores del juego.

En sus mandamientos para el diseño de aventuras, que ya cité muchas veces en este blog, Ron Gilbert decía que es fundamental recompensar al jugador por sus logros, y que la recompensa suele venir en forma de arte: un escenario nuevo, otro lugar para explorar. Me doy cuenta que, conociendo bien cada rincón del juego, me incentiva ahora escuchar qué tendrán para decir los diseñadores, qué anécdota o qué chiste sobre el próximo lugar que vaya a visitar.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

<diego

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

<la oficina

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

<mi propia pc

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Por segunda vez me postergaron la fecha de inicio en mi trabajo nuevo. Sigo jugando.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Me está costando el puzzle del torneo de escupidas.


#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Me sigue costando. Ya entré en la etapa de negación: /a lo mejor no soy yo, a lo mejor hay un bug en esta edición/. Me tienta usar una guía para destrabarme, para no terminar abandonando el juego. Claro que usar una guía también constituye una forma de abandono, un riesgo de convertir el juego en una suerte de trámite, un seguir las instrucciones que escribió alguien. Nunca me recuperé de haber quemado el /Grim Fandango/ siguiendo una guía de la XTREME PC, porque era demasiado para mis 12 años.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Terminé googleando la solución, nomás. Qué vergüenza. Requería notar un detalle demasiado sutil en el movimiento de un pixel. El diseño es flojo pero podría haberlo logrado. Fallé.


#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Con esa trampa cierro rápidamente el segundo capítulo del juego, que es el más largo y el mejor. Ingreso en el terreno sinuoso en que la aventura se empieza a cerrar.

<

Acá está el mayor riesgo de desinteresarme y abandonar. Un riesgo agravado porque finalmente empecé con el trabajo nuevo.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

<efecto clasico + variante puzzle

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Ya trabajando. Pasé una semana sin jugar.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Otra semana sin jugar. Son estas notas, esta especie de diario, las que me impiden abandonar.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Otra semana. El juego sigue presente porque en mis pensamientos por otro texto en el que trabajo en mi tiempo libre, que le concierne.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Vuelvo al juego después de mucho tiempo, como quien termina un trámite postergado, como quien retoma un diario ---este.

Se confirmaron las preocupaciones que había consignado: después del segundo capítulo el juego entra en un embudo, se vuelve lineal y poco queda de su encanto. Los comentarios de los desarrolladores se apagan a su vez. Los últimos puzzles quizás sean los más difíciles pero estos sí que me los acuerdo bien. Despacho lo que queda del juego en una o dos horas, sin demoras, en una sentada.

Con el [[file:volviendo-los-monos][recuerdo fresco]] de /Return to Monkey Island/, el final me resulta mucho menos abierto de lo que esperaba, lejos del mito que la espera de treinta años había ayudado a construir. Me parece un buen desenlace, elegante, el cierre de una historia en dos partes. Lo que vino después fue una franquicia improvisada ---aún con buenas entregas.

Es simpático ver pasar los créditos. Más que cualquier otro elemento del juego, son una cápsula del tiempo, me transportan momentáneamente a 1991, a un 1991 imaginado, distinto del que yo viví.
