---
title: Simulador discófilo
date: 2026-08-08T14:08:20-03:00
layout: post
lang: es
tags: [ideas, software, música]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

Tuve una idea para algo a medio camino entre juego y aplicación. Como lo más mersa que se puede hacer hoy día con una idea de software es implementarla, me limito acá a contarla, lanzándola así al mar de información de donde podrá levantarla alguno de los bots que hacen la mayoría de mi público.


#+BEGIN_EXPORT html
<br/><br/>
#+END_EXPORT


La aplicación (o el juego) es un tocadiscos de escritorio, es decir, un reproductor musical que solo permite escuchar álbumes. No canciones sueltas, ni artistas completos, ni radios, ni listas. Hasta ahí poco de especial, un subconjunto de lo que ya hacen todos los reproductores musicales del mundo. Pero hay más: el usuario no tiene, como en spotify o bit torrent, una cantidad virtualmente infinita de álbumes a disposición, sino que solo puede escuchar lo que tiene en su colección, lo que, virtualmente, /le pertenece/. En este simulador discófilo el usuario (o el jugador) empieza con unos pocos discos, que tal vez elija o tal vez herede, y con un presupuesto mensual para cambiar su colección. Entretanto, solo puede escuchar de eso que ya tiene.

Es decir que la experiencia incluye: elegir bien, deliberadamente, las opciones de escucha; convivir, al menos por un tiempo, con esas elecciones; fantasear con eso que podría, eventualmente, escucharse;
desbloquear eso que surge cuando el disco es la unidad de medida y cuando uno escucha, una y otra vez, un mismo disco. Cuando uno entiende que hay /zonas/ en el disco, que lo que parecía extenderse apenas en el tiempo constituye también una superficie. Sin juicio de valor y sin nostalgia: lo que hay ahí, en ese modo de escucha, no es necesariamente mejor pero es algo forzosamente distinto a saber un universo musical en la punta de los dedos.

De nuevo: el usuario (o jugador) instala la aplicación y ve algo que imagino como un pre-render noventoso, quizás una escena en un living, con un tocadiscos y un estante con sus vinilos. Arranca con poco, supongamos dos o tres discos, como quien se compraba un Winco en los '70, o quien pasaba al CD en los '90 y tenía que rearmar su colección. Como el nostálgico o el audiófilo que ahora vuelve a los vinilos. El usuario (el jugador) empieza con, digamos, tres discos y eso es lo único que puede escuchar. Si se lo toma en serio entonces toda su escucha musical va a pasar por esa <limitada colección | aplicación>. Nada de Spotify o Apple Music en el bondi ni de YouTube en el living: la simulación consiste en armar una colección y convivir con ella.

A falta de algo distinto que escuchar profundiza eso que tiene adelante. Escucha y mientras tanto observa las tapas, <recorre los libros internos>, ve las fotos, lee las letras. Imagina posibles futuros recorridos, qué convendría sumar a esa colección. Si ahora convivo con /Revolver/, ¿insisto con /Rubber Soul/? ¿O paso a Cream o a Jimi Hendrix? ¿O a Bob Dylan o a Mercedes Sosa?

<Supongamos que el presupuesto alcanza para comprar un disco por mes. Y que se pueden revender los discos o cambiarlos por otros. Ahí la aplicación podría empezar a mutar en juego: administrar fondos, proyectar futuras compras, balancear lo que se tiene y lo que se quiere para que siempre haya algo <deseable> de escuchar.

Podría, también, aparecer el factor del tiempo. Si la simulación arranca en 1970 va a haber que esperar unos años para comprar /Dark Side of the Moon/. Si arranca en los noventa, a esperar el próximo de Nirvana.

Ya puestos a "gamificar" la experiencia, la fuente de dinero, el trabajo que permite ampliar la colección, tendría que ser parte del juego. Algo así como en el /Moonlighter/ uno va a minar las piedras que al otro día pone en venta en el negocio. O como, en /Dave the Diver/, pescamos por la mañana lo que cocinamos por la noche. Claro que para que exista resonancia temática ese trabajo tendría que ser también musical. El jugador (ya no usuario) podría, por ejemplo, como John Cusack en /Alta fidelidad/, atender un negocio de discos (negocio anacrónico en la novela del '95 y la película del 2000 pero que hoy en día podría ser rentable). Pero el juego, entonces, sería algo así como el /RetroRewind/ o el argentino /VHS Paradise/, un simulador de tienda que demanda organizar un inventario y disponerlo los anaqueles, lidiar con los clientes y los freaks y otras sombras ominosas que nos llegan de la calle. Algo que suena como a mucho esfuerzo. La verdad es que yo no quería otro trabajo, yo solo quería una colección de discos. Esta simulación se parece demasiado a la vida real.
