---
layout: post
title: "El tipo de las necrológicas"
date: 2021-12-09T08:49:18-03:00
tags: [ficción]
lang: es
book: "vol1"
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

El tipo quiere ser novelista pero hay que pagar las cuentas, así que acepta una oferta de su director de tesis y entra como colaborador de la sección cultural de un diario. Se pasa un par de años sin pena ni gloria, aprendiendo el oficio --trata de controlar su verborragia, busca un registro aceptable para el lector ocasional sin formación académica---, produciendo una nota por semana que no siempre es publicada y fracasando continuamente en sus intentos de ficción, hasta que su mentor y amigo fallece abruptamente, sumiéndolo en una depresión de la que solo puede salir escribiendo. Aunque no se había propuesto publicarla, comparte la semblanza de su amigo con compañeros de la redacción y su jefe le propone incluirla en la siguiente edición del diario. La nota es muy bien recibida, todos en el diario están de acuerdo en que es su mejor contribución hasta la fecha, lo que él atribuye a su cercanía con el difunto.

Cuando, semanas después, muere una personalidad de la cultura, su jefe le pide que escriba algo, sin decirlo pero dando a entender: /algo como lo que escribiste para tu amigo/. A él no le gusta el pedido, le parece falso repetir el procedimiento para alguien que no conoce pero al fin y al cabo es su trabajo, así que accede con igualmente satisfactorio resultado. La situación se repite con otros muertos, a él no termina de convencerlo este oficio encontrado pero lo hace bien, evidentemente tiene un don para destilar en unos pocos párrafos la esencia de una vida, y de todas formas su carrera de novelista sigue sin despegar, para no decir que nunca arrancó. Así que se convierte en /el tipo de las necrológicas/ y, como muertos no faltan, ejerce ese rol no solo en la sección cultural sino en el resto del diario y en otros medios, perfeccionando su método. Después de unos años empieza a distinguir patrones, al hablar con una persona se le ocurre qué pondría en su obituario, de los más viejos o enfermos especula sobre cuándo van a morir y termina por escribir borradores de sus notas por adelantado, antes de que mueran, cambiando detalles circunstanciales al momento de la publicación. Lo que resulta ser una buena inversión, demasiado buena o terrible porque aquellos sobre los que escribe efectivamente mueren al poco tiempo, a decir verdad mueren justo después de que él termina de escribir.

Al tercer o cuarto muerto se queda sin margen para creer en las casualidades, desiste de escribir borradores pero no puede apagar su cabeza, se convence de que cada pedazo de información que absorbe le resta a alguien años de vida y de que mata gente con solo pensarla. Deja su trabajo y se recluye preventivamente, por años evita el contacto con los demás y vuelve a la rutina de fracasar con sus novelas, siempre cuidándose de no pensar en nadie real, en nadie que siga vivo. Al final solo le quedan sus propios recuerdos para masticar y los escribe en el tono que le dio el oficio, escribe lo que puede ser leído como una necrológica pero que él sabe una nota suicida, se escribe a sí mismo, brevemente, tres párrafos y un punto final.
