---
title: Ese chicle que te gusta va a volver a estar de moda
date: 2025-03-21 18:15:53
layout: post
lang: es
tags: [cine, memorias]
refs: []
draft: true
img: lynch.png
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

Me despertaba la radio a las 5:50, me tomaba un colectivo abajo del puente y otro al costado de la Gral. Paz, todavía de noche, con olor a tortilla parrillera, intimando con trabajadores y estudiantes de Arquitectura, o, más bien, con las esquinas de los trabajos prácticos que llevaban encima. Nos bajábamos los últimos, ya de día, cuarenta segundos de pasto seco y aire de río, un subsuelo con olor a medialuna recalentada y café quemado y listas de nombres pegadas en las paredes, un habitáculo que había sido cancha de básquet y pretendía ser aula pero que no era ni más ni menos que un freezer. Los días que no tenía clase igual me levantaba a las 6 y me pasaba la mañana haciendo los mismos ejercicios de Análisis Matemático, encadenando tazas de té como los personajes de las novelas rusas que había empezado a leer.

A la par de esa colimba universitaria inicié un proceso autodidacta, reconociendo, con una mezcla de vergüenza, curiosidad y sed de infinito (sic), que mi ignorancia se extendía mucho más allá de la matemática. Resolví enfocar mi educación cultural en el cine y la literatura. Empecé a leer y mirar sistemáticamente todo lo que pude encontrar, con la torpeza de aque personaje de Sartre ---a quien no conocía--- que se lee toda la biblioteca pública en orden alfabético. 2006 era un buen año para estos berretines, la información era todavía valiosa y requería cierto esfuerzo conseguirla, pero se iba haciendo lo suficientemente accesible como para que un post-adolescente del conurbano, sin ingresos pero con mucho tiempo, pueda salir a bunuscarla haciendo de ello un proceso de aprendizaje, de construcción de identidad.

Así que buscaba rankings online y recorría foros, armaba listas, dejaba la computadora zumbando mientras dormía y cuando salía de casa, siempre bajando y ensamblando archivos comprimidos de Megaupload o Rapidshare. Pero también leía el suplemento de espectáculos y la cartelera de cine en el diario de los domingos, resaltaba cualquier cosa potable de la guía del cable a principios del mes, me tomaba el tren a Caballito para comprar libros usados y elegir películas truchas de un catálogo en los puestos de Parque Rivadavia. Me compré un reproductor de DivX y todas las noches miraba una película distinta antes de irme a dormir.

Aprendí también a ir solo al cine y lo hice sobre todo en ese /no-lugar/ que fue el Showcenter de Haedo, una falla menemista en la superficie del conurbano, exageradamente grande, fondo de pantalla de mi infancia y mi pre-adolescencia, sucesivamente desmantelado con las crisis pero que por alguna incongruencia concesionaria se resistía a cerrar del todo. Para el 2006 solo quedaban los cines en pie, perennemente semivacíos, y todo lo otro ---los locales y los patios, los segundos y terceros pisos--- clausurados y tapiados, todo un pueblo fantasma devenido en decorado devenido en pasillo con la única función de prolongar una antesala.

Mi recorrido cinéfilo empezó por donde pude, por lo obvio y lo que tocaba de oído: /El Padrino/, /Casablanca/, /La Naranja Mecánica/, y sucesivamente siguiendo recomendaciones y nombres famosos que encontraba en internet, hasta que las conexiones empezaron a surgir por sí solas. En esos años vi las películas de Kubrick, Bergman, Kurosawa, Kobayashi, Fritz Lang, Orson Welles, Billy Wilder, Sergio Leone, Godard, Truffaut, Melville, Spielberg, Coppola, Scorsese, Hitchcock, Buñuel, Kieslowski, Bertolucci, Woody Allen, Ridley Scott, Tarantino, los hermanos Coen, González Iñárritu, David Fincher, Christopher Nolan, Darren Aronofsky, Wes Anderson, Richard Linklater, Charlie Kaufman. A ninguno de esos directores y escritores me los apropié, ninguno pasó a componer mi personalidad, de ninguno /me hice hincha/ como sí lo hice con David Lynch.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER
