---
title: Ese chicle que te gusta va a volver a estar de moda
date: 2025-03-21 18:15:53
layout: post
lang: es
tags: [cine, memorias]
refs: []
draft: true
img: lynch.png
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

Me despertaba la radio a las 5:50, me tomaba un colectivo abajo del puente y otro al costado de la Gral. Paz, todavía de noche, con olor a tortilla parrillera, intimando con trabajadores y estudiantes de Arquitectura, o, más bien, con las esquinas filosas de los trabajos prácticos que llevaban a la Facultad. Nos bajábamos los últimos, ya de día, cuarenta segundos de pasto seco y aire de río, un subsuelo con olor a medialuna recalentada y café quemado y listas de nombres pegadas en las paredes, un habitáculo con pupitres apilados que había sido cancha de básquet y pretendía ser aula pero que no era ni más ni menos que un freezer. Los días que no tenía clase igual me levantaba a las 6 y me pasaba la mañana haciendo los mismos ejercicios de Análisis Matemático, encadenando tazas de té como los personajes de las novelas rusas que recién empezaba a leer.

A la par de esa colimba universitaria inicié un proceso de autoeducación observando, con una mezcla de curiosidad y vergüenza, que mi ignorancia se extendía mucho más allá del cálculo infinitesimal. Resolví enfocarme en el cine y la literatura: empecé a leer y mirar sistemáticamente todo lo que pude encontrar, con la torpeza de aquel personaje de Sartre ---a quien no conocía--- que se lee toda la biblioteca pública en orden alfabético. 2006 era un buen año para estos berretines, la información era todavía valiosa y requería cierto esfuerzo conseguirla, pero se iba haciendo lo suficientemente accesible como para que un post-adolescente del conurbano, sin ingresos pero con mucho tiempo, pueda salir a bunuscarla haciendo de ello un proceso de aprendizaje, de construcción de identidad.

Así que buscaba rankings y recorría foros, armaba listas, dejaba la computadora zumbando mientras dormía y cuando salía de casa, siempre bajando y ensamblando archivos comprimidos de Megaupload o Rapidshare. Pero también leía el suplemento de espectáculos y la cartelera de cine en el diario de los domingos, resaltaba cualquier cosa potable de la guía del cable a principios del mes, me tomaba el tren a Caballito para comprar libros usados y elegir películas truchas de un catálogo en los puestos de Parque Rivadavia. Me compré un reproductor de DivX y todas las noches miraba una película distinta antes de irme a dormir.

Aprendí también a ir solo al cine y lo hice sobre todo en ese /no-lugar/ que fue el Showcenter de Haedo, una falla menemista en la superficie del conurbano, exageradamente grande, fondo de pantalla de mi infancia y mi pre-adolescencia, sucesivamente desmantelado con las crisis pero que por alguna incongruencia concesionaria se resistía a cerrar del todo. Para el 2006 solo quedaban los cines en pie, perennemente semivacíos, y todo lo otro ---los locales y los patios, los segundos y terceros pisos--- clausurados y tapiados, todo un pueblo fantasma devenido en decorado devenido en pasillo con la única función de prolongar una antesala.

Mi recorrido cinéfilo empezó por donde pude, por lo obvio y lo que tocaba de oído: /El Padrino/, /Casablanca/, /La Naranja Mecánica/, y sucesivamente siguiendo recomendaciones y nombres famosos que encontraba en internet, hasta que las conexiones empezaron a surgir por sí solas. En esos años vi las películas de Kubrick, Bergman, Kurosawa, Kobayashi, Fritz Lang, Orson Welles, Billy Wilder, Sergio Leone, Godard, Truffaut, Melville, Spielberg, Coppola, Scorsese, Hitchcock, Buñuel, Kieslowski, Bertolucci, Woody Allen, Ridley Scott, Tarantino, los hermanos Coen, González Iñárritu, David Fincher, Christopher Nolan, Darren Aronofsky, Wes Anderson, Richard Linklater, Charlie Kaufman. A ninguno de esos directores y escritores me los apropié, ninguno pasó a componer mi personalidad, de ninguno /me hice hincha/ como sí lo hice con David Lynch.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

Cuando se murió Lynch mi primera reacción fue tomármelo en broma. Mi segunda reacción fue ponerme muy triste, más de lo que esperaba. Durante días me entregué a un duelo colectivo que también me tomó por sorpresa: resulta que este director /under/, autoproscripto de la picadora de carne hollywoodense, gozaba de popularidad. Y sus raros seguidores conformábamos sin saberlo una especie de sociedad secreta, una organización clandestina que reventó con la muerte de su líder.

Sería de mal gusto teorizar o suministrar explicaciones, pero me gusta pensar que David Lynch, el David Lynch de /Blue Velvet/ y /Twin Peaks/, sintonizó o emitió él mismo la frecuencia de una época; que la rareza que prodigó en su breve auge televisivo no solo habilitó el sci-fi de /X-Files/, la televisión de autor de la década siguiente y la ficción de adolescente-asesinada-en-pueblito ya repetida hasta el hartazgo, sino que explica cierta inclinación al surrealismo de toda la televisión con la que crecimos ---pienso sobre todo en /Pete & Pete/, pero también en /Freakazoid/, /Rocko/, /Ren & Stimpy,/ /Eerie, Indiana/. Y que esa ficción excéntrica, influida por Lynch o por las reverberaciones de su trabajo, fue lo que nos preparó a su vez para volver a Lynch cuando crecimos.

Entre todos los elogios fúnebres, retrospectivas y homenajes que leí en esos días ---de los que este es apenas oblicuamente uno más--- lo que más disfruté fue [[http://www.lynchnet.com/lh/lhpremiere.html][una crónica]] de David Foster Wallace, no con motivo de la muerte de Lynch (Wallace se mató 16 años antes) sino escrita en el '96 desde el set de /Lost Highway/.

El '96 era un momento peculiar para observar a Lynch, el público yanqui no lo terminaba de descifrar o, en todo caso, no terminaba de encasillar su indescifrabilidad: a la nominación al Oscar por /Elephant Man/, el hit de culto de /Blue Velvet/, la fenómeno de la primera temporada de /Twin Peaks/ y la Palma de Oro en Cannes por /Wild at Heart/ siguieron la decepción de la segunda temporada y la despareja precuela de /Twin Peaks/, y la cancelación de la olvidable /On the Air/. Foster Wallace supone que la reputación de David Lynch se va a terminar de establecer, para bien o para mal, con /Lost Highway/, pero para Foster Wallace el éxito de la película y la eventual reputación David Lynch le importa mucho menos que entender cuánto de todo eso le importa a su vez al propio Lynch. Y, como nosotros nos podemos imaginar y Foster Wallace termina por aceptar, su reputación a David Lynch le chupa un huevo.

Foster Wallace le atribuye a Lynch un fuerte influjo sobre el resto de los directores indie de los '90, a saber: Gus Van Sant, Tarantino, Los Hermanos Coen, a quienes tilda de imitadores edulcorados, empaquetando en películas más lineales y menos incómodas un tono y un método que Lynch inventó. A mí, que también soy hincha de los Coen, me resulta difícil ver esa conexión: uno me parece un expresionista intuitivo, los otros unos relojeros irónicos. Pero como no soy crítico de cine, ni comentarista cultural ni sociólogo, me ahorro aplicar sobre mis opiniones el barniz de alguna teoría.

Sí veo un punto de contacto, que probablemente solo exista en mi imaginario personal, en una escena de una de las películas de los hermanos Coen, que no es lyncheana sino meta-lyncheana, que no habla en el tono de Lynch sino que habla sobre el efecto que el tono de Lynch produce en el público, un público desahuciado ante la no resolución de los acertijos que el director aparentemente les plantea. En esta película de los Coen, un profesor de física cuántica le exige coherencia al padre de su alumno, cuando este le hace dos acusaciones mutuamente contradictorias. El profesor se queja porque el discurso de su interlocutor no tiene sentido desde un punto de vista lógico: las dos afirmaciones no pueden ser verdaderas a la vez. Su interlocutor sencillamente lo invita a que /acepte el misterio/. Créanlo o no, esa escena es la más espiritual de toda la filmografía de los Coen, por razones que no voy a elaborar.

Y ya que hablamos de relojeros irónicos, aprovecho para pagar el peaje que es citar a Borges. Borges, que tuvo fama de desarrollar argumentos como demostraciones matemáticas, se permite curiosamente ciertas licencias poéticas en sus ensayos. Al leerlos, uno puede elegir perderse en sus laberintos de referencias y en oscuras analogías, tratando de desentrañar la lógica del argumento; o bien puede dejarse llevar por la cadencia de las frases y la belleza de las imágenes, dejar que la forma lo arrastre a uno a las orillas de una conclusión perfecta e inapelable. A decir de Chiqui Tapia, y tal vez de David Lynch: /no trates de entenderlo, disfrutalo/. Es de mi ensayo preferido de Borges desde donde trazo esa línea hacia Lynch ---lo que no es original porque a ese ensayo le veo conexiones con prácticamente todo. Borges define en [[borges-linkeado][/La muralla y los libros/]] el /hecho estético/, nos dice que

#+begin_quote
La música, los estados de la felicidad, la mitología, las caras trabajadas por el tiempo, ciertos crepúsculos y ciertos lugares, quieren decirnos algo, o algo dijeron que no hubiéramos debido perder, o están por decir algo; esta /inminencia de una revelación, que no se produce/, es, quizá, el hecho estético.
#+end_quote

¿Hay una concepción más lyncheana del arte que esa?
