---
title: En realidad quería hablar de David Foster Wallace
date: 2025-06-28
layout: post
lang: es
tags: [literatura, memorias]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

# using a zero width space to prevent bullet treatmetn
1.​ podría ir a revisar el blog de Martín Zariello, donde estoy casi seguro que leí de él por primera vez
#+BEGIN_EXPORT html
<br/><br/>
#+END_EXPORT

2.​ <me interesé en su obra después de ver su biopic durante un viaje en avión. <protagonizada por Marshall de /How I Met Your Mother/ y Mark Zuckerberg, no me acuerdo en qué viaje la vi, si estaba solo o acompañado, pero sí me acuerdo de, o en todo caso integro a mi recuerdo, la pantallita en el respaldo de los asiento---esa pantallita ominosa que se multiplica al volver del baño---, las sobras de pollo-o-pasta apilados sobre la bandeja desplegable, los auriculares descartables en los que se escucha mejor el murmullo aéreo que el diálogo de la película, los popups anticlimáticos cada vez que el piloto hace un anuncio.

#+BEGIN_EXPORT html
<br/><br/>
#+END_EXPORT

3.​ hablar del libro de ensayos que me bajé y nunca tuve el coraje de empezar[fn:3] o del libro de cuentos que empecé y abandoné[fn:4].
 Me pareció que empezar por ensayos podría ser más accesible que la narrativa, considerando que la obra más recomendada es un mamotreto de 1000 páginas, pero resulta que sus ensayos también son, a su manera, pequeños mamotretos, y solo atravesándolos uno se da cuenta que el mamotretismo es un feature no un bug de la escritura de Foster Wallace, algo que no estaba equipado para resolver en aquel primer intento cuando me vi que el primer ensayo de /Hablemos de Langostas/ era sobre una convención de cine porno y duraba 50 páginas.
TODO /La niña del pelo raro/, demasiado largos, demasiado yanquis, el conductor de jeopardy! alex trebek, el vicepresidente lyndon johnson
