---
title: Leer a Saer
date: 2026-08-29T18:56:55-03:00
layout: post
lang: es
tags: [literatura, libros]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

En un principio, la literatura era un tren en el que yo viajaba colgado. Para no soltarme, participaba de supersticiones como la de leer un solo libro a la vez y terminar todos los libros que empezaba. Después aprendí a relajarme y a ignorar las recomendaciones, las instrucciones, las opiniones preestablecidas y a dejarme llevar por el impulso y el placer. Con esa actitud intento encarar la mayoría de mis lecturas ahora y así también lo intenté cuando, hace muchos años, intenté leer /Cicatrices/... y me choqué con una pared.

#+begin_quote
Hay esa porquería de luz de junio, mala, entrando por la vidriera. Estoy inclinado sobre la mesa, haciendo deslizar el taco, listo para tirar. La colorada y la blanca —mi bola es la de punto— están del otro lado de la mesa, cerca del rincón. Tengo que golpear suavecito, para que mi bola corra muy despacio, choque primero con la colorada, después con la blanca y pegue después en la baranda entre la colorada y la blanca: la colorada va a golpear contra la baranda lateral, antes de que mi bola choque contra la baranda del fondo, hacia la que tiene que ir en línea oblicua después de chocar contra la blanca. Así: suavecito, mi bola va a despedir a la colorada —la cual va a chocar contra la baranda lateral— y va a rebotar hacia la blanca, mientras la colorada viene a su vez hacia la blanca desde la baranda lateral, en línea recta. Mi bola va a formar un triángulo imaginario. La colorada va a recorrer la base de ese triángulo, de una punta a la otra. Si el cálculo no es exacto la colorada no va a tener tiempo de recorrer una determinada parte del trayecto hacia la blanca. La colorada tiene que haber pasado ya determinado punto de la mesa —viniendo desde la baranda lateral— antes de que mi bola choque contra la baranda del fondo y vuelva para abajo otra vez, despacito, en línea oblicua.
#+end_quote

Así proseguía la narración por varios párrafos y varias páginas, discurriendo sobre la mesa de billar,
como si esa primera persona no compusiera un punto de vista sino apenas el soporte de una cámara que siguiera las alternativas del taco y las bolas y el humo de un cigarro y la interacción de cada una de esas cosas con la luz eléctrica y la luz de la calle. Una cámara empecinada en el detalle, como esa que al principio de /Blue Velvet/ se hunde en el pasto y se amontona con los bichos, como esa pero como si esa persistiera ahí, en esa perspectiva, durante las dos horas de la película. Porque eso que en /Cicatrices/ yo suponía un canchereo inaugural que el autor hacía para marcar la cancha y ahuyentar a lectores despistados como yo, se prolongaba todavía por párrafos e incluso más allá de esa primera escena. Se prolongaba, de hecho, por el resto de ese libro y aún en otros 15 más que escribió Saer durante 35 años, porque constituía, más o menos, su programa estético. El detalle y la descripción sometían al argumento: eran su forma de narrar. /Cicatrices/, en fin, me resultó impenetrable ---en palabras de Martín Zariello: [[https://ilcorvino.blogspot.com/2013/10/el-mundo-se-divide-entre-las-personas_31.html][inabordable]]--- y, como yo religioso ya no era, la abandoné.

Unos años después, durante la primera cuarentena, ese tiempo en que, un poco como, supe un poco después, Saer hacía en sus novelas, el tiempo parecía detenerse o estirarse hasta que perdíamos su noción (la del tiempo), lo que nos llevaba a ocupaciones exóticas como amasar pan o mirar la bundesliga, hice otro intento de lectura de Saer, con /El entenado/. Y esta vez, sí, pude terminar el libro, e incluso disfrutarlo por momentos, aunque la operación en su conjunto tuvo menos de placer que de hazaña, de ejercicio de destreza y resistencia, como amasar pan o hacer flexiones de brazos o extraerle entretenimiento a un desolado partido de fútbol alemán. La del /Entenado/ fue una lectura que no floreció en nada, que se cerró sobre sí misma.

Más años más tarde, en 2024, siguiendo un nuevo impulso pero ya mucho más consciente de eso en lo que me metía, me llevé a un viaje /La pesquisa/. Y porque estaba mejor preparado y era otro momento y yo era, en cierta medida, una persona distinta (si bien, en cierta otra medida, ¿no?, la misma), y por determinadas características particulares de ese libro a elaborar más luego, no solo lo terminé y lo disfruté sino que inicié un proceso de lectura en el que Saer pasó de /inabordable/ o /de difícil abordaje/ a ser uno de mis escritores favoritos y el que más leo desde entonces. Resulta que no solo Saer escribe difícil, no solo exige trabajo y paciencia, sino que hay que saber por dónde entrarle. Quiero vindicar entonces a /La pesquisa/ como punto de partida.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER

- Saer escribe difícil
- Lo argumental queda en segundo plano, parece que no pasa nada, o que pasa poco, infinitamente lento,  repetidamente hasta la exasperación
- Eso poco que pasa, el esbozo de situación, parece apenas un soporte par alo otro, para la forma, que es la razón de ser del relato
- Saer abunda en digresiones metafísicas, en descripciones microscópicas y minuciosas y extravagantes, en párrafos interminables y oraciones zigzagueantes cuyo sujeto o su predicado termina siendo una revelación
- La prosa de Saer es sumamente bella, pero la belleza es accesible abordándola como poesía: menos por la información que acarrea sino por las imágenes que evoca y la cadencia con la que avanza
- y después está el humor, el humor de las ironías y las guarradas y los delirios de los personajes pero también el humor del narrador, que aparece mediante insistencias y repeticiones, mediante las metáforas extravagantes y la interrelación de lo mundano con lo existencial
- una vez uno se acostumbra a ese estilo, ya adentro de ese modo de lectura que demanda, uno puede saborear el texto aún trastabillando a través de él, aún si no pasa objetivamente nada en la trama y la narración parece no llevarnos a ningún lugar, hay algo que termina apareciendo, como por acumulación. Porque, resulta que atrás de todas esa nada algo surge, como un sedimento argumental, aunque solo vaya a realizarse mediante un puente hacia otros libros.

<En /La pesquisa/, una obra tardía de Saer, ese juego ya está consolidado; pasadas las tentativas de los primeros libros pero también de sus expresiones más radicales (/La mayor/, /El limonero real/, /Nadie nada nunca/). Pero la pesquisa es, también, como aclara el subtítulo, una /novela policial/, y eso modifica también su lectura. Es decir que, aunque el género es apenas un punto de partida y como siempre Saer subordina la trama a la forma, hay a fin de cuentas un asesino serial matando viejas en París y un detective protagonista que lo persigue y eso le da al lector primerizo un soporte argumental al que aferrarse. Acá, decididamente hay /algo/ que sucede, y aunque esos hechos sean accesorios al dispositivo narrativo, el lector se involucra en ese esclarecimiento de los crímenes y en esa búsqueda del asesino.

Ya envueltos en ese esquivo misterio policial nos enteramos, pasado un tercio del libro, de que el relato que leímos se lo está haciendo un personaje a otro en un patio cervecero en en Santa Fe. Es decir que el relato nos traslada bruscamente a /la zona/, ese territorio ficcional entre la ciudad de Santa Fe y el pueblo que Saer pobló de personajes recurrentes a lo largo de su obra. En este relato exterior aparecen todos los clásicos de Saer: amigos contándose historias (glosando), en este caso Tomatis y Pichón Garay, el río Paraná y el calor tórrido del litoral, carne asada, pan y vino (descriptos hasta la última burbuja crepitante).

Así /La Pesquisa/ nos ofrece entrar por un relato universal para pasar a lo típicamente saeriano, pero hay más: el relato lo hace Pichón, emigrado a París 20 años antes, que ahora, como nosotros, juega de visitante. El relato se lo hace a Tomatis, el personaje más frecuente y el que más tiene de Saer, pero se lo hace también a uno de los "nuevos", Pinocho Soldi, cuya perspectiva se parece un poco a la nuestra:

#+begin_quote
Soldi —Pinocho para los amigos, como ha dicho Tomatis en el momento de la presentación— los viene a su vez observando en los últimos quince días. Desde un par de años atrás, cuando se acercó por primera vez a Tomatis, lo oye hablar con frecuencia de los mellizos Garay, uno de los cuales desapareció hace unos ocho años, sin dejar rastro como se dice, y el otro vive en París desde hace más de veinte. Según Tomatis, eran tan idénticos que la gente los confundía todo el tiempo y ellos mismos, sin siquiera haberse puesto de acuerdo de un modo explícito, contribuían con maniobras sutilísimas, por pura broma o por razones oscuras incluso para ellos, a aumentar la confusión. De modo que, ahora que ha conocido personalmente a uno, a Soldi le parece que los dos han entrado a través de su experiencia en su imaginación, y que se ha filtrado en ella, probablemente ya para siempre, la misma confusión. El único ejemplar todavía viviente del inconcebible ente repetido que supo atravesar la luz del día en la ciudad durante tantos años, le sirve a Soldi como referencia empírica para representarse, cuando escucha a Tomatis hablar de ellos, a cualquiera de los dos e incluso a los dos a la vez, como una misma imagen desdoblada y no como dos seres autónomos y diferentes.

A veces, cuando escucha hablar a Tomatis y a Pichón, si bien todo lo que dicen lo divierte y le interesa, después, cuando se queda solo, tiene que someterlo a una especie de traducción: los juicios que emiten le parecen exactos en el momento en que los escucha, pero en las horas y en los días siguientes los descompone en todos sus elementos simples, sometiendo cada uno de ellos a un examen riguroso. La compañía de esos dos cuarentones irónicos y tranquilos, ya más cerca de los cincuenta que de los cuarenta a decir verdad, lo delecta aunque, o tal vez por eso mismo, las convenciones que presiden su conversación se le escapan. Aunque la relación que mantiene con ellos, y sobre todo con Tomatis, con quien desde hace más o menos dos años se ve casi todas las semanas, se ha establecido en un plano de igualdad, Soldi cree notar que, cuando se dirigen a él, los dos amigos cambian imperceptiblemente de tono, y sus frases parecen volverse levemente más claras y explicativas que las que intercambian, elípticas y llenas de sobreentendidos, cuando hablan entre ellos.
#+end_quote

La historia progresa alternadamente entre París y Santa Fe, y ya nos interesa menos descubrir al asesino que presenciar a Pichón y Tomatis discutiendo la posibilidad de descubrir al asesino, embebido en los recuerdos de ese día y de los días anteriores de la visita de Pichón y de los días recordados de 20 años atrás. Y, sobrevolándolo todo, la ausencia del Gato Garay, aquel doble de Pichón.

#+begin_quote
De esa casa habían desaparecido varios años antes, sin dejar literalmente rastro, el Gato y Elisa. Fueron, como tenían la costumbre de hacerlo desde hacía años, a pasar un par de días juntos, y nunca nadie más volvió a verlos. La casa de Rincón había sido desde siempre para ellos el recinto sacrosanto donde repetían periódicamente el ritual del adulterio. La puerta de calle estaba como de costumbre sin llave, pero todo seguía limpio y ordenado. No había señales de lucha o de presencias extrañas. Las camas estaban hechas y la mesa puesta. En la heladera, los alimentos para varios días se encontraban todavía en buenas condiciones. Aunque había algunos objetos de valor, máquina de escribir, ventiladores y otros artefactos, no faltaba nada y cada cosa seguía, intacta y en perfecto estado de funcionamiento, en su lugar. Un amigo publicitario, para el que el Gato hacía de tanto en tanto algún trabajito, fue el que descubrió que habían desaparecido: como eran tiempos de terror y de violencia, y como al entrar en la casa silenciosa, empezó a sentir un olor nauseabundo, el amigo publicitario se asustó bastante, pero cuando entró en la cocina descubrió que el olor venía de un pedazo de carne que se descomponía sobre el fogón, en un plato. Al lado había un gran cuchillo de cocina y una tabla de picar carne, pero no habían tenido tiempo de usarlos. En el momento en que había sacado el plato de carne de la heladera y lo habían depositado sobre las baldosas rojas del fogón, el fluir de sus actos se había detenido y ellos se habían como quien dice volatilizado. Nunca más en siete u ocho años un solo signo de su existencia material, ni siquiera sus cenizas, había aparecido.
#+end_quote
