---
title: Leer a Saer
date: 2026-08-29T18:56:55-03:00
layout: post
lang: es
tags: [literatura, libros]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

En un principio, la literatura era un tren en el que yo viajaba colgado. Para no soltarme, participaba de supersticiones como la de leer un solo libro a la vez y terminar todos los libros que empezaba. Después aprendí a relajarme y a ignorar las recomendaciones, las instrucciones, las opiniones preestablecidas y a dejarme llevar por el impulso y el placer. Con esa actitud intento encarar la mayoría de mis lecturas ahora y así también lo intenté cuando, hace muchos años, intenté leer /Cicatrices/... y me choqué con una pared.

#+begin_quote
Hay esa porquería de luz de junio, mala, entrando por la vidriera. Estoy inclinado sobre la mesa, haciendo deslizar el taco, listo para tirar. La colorada y la blanca —mi bola es la de punto— están del otro lado de la mesa, cerca del rincón. Tengo que golpear suavecito, para que mi bola corra muy despacio, choque primero con la colorada, después con la blanca y pegue después en la baranda entre la colorada y la blanca: la colorada va a golpear contra la baranda lateral, antes de que mi bola choque contra la baranda del fondo, hacia la que tiene que ir en línea oblicua después de chocar contra la blanca. Así: suavecito, mi bola va a despedir a la colorada —la cual va a chocar contra la baranda lateral— y va a rebotar hacia la blanca, mientras la colorada viene a su vez hacia la blanca desde la baranda lateral, en línea recta. Mi bola va a formar un triángulo imaginario. La colorada va a recorrer la base de ese triángulo, de una punta a la otra. Si el cálculo no es exacto la colorada no va a tener tiempo de recorrer una determinada parte del trayecto hacia la blanca. La colorada tiene que haber pasado ya determinado punto de la mesa —viniendo desde la baranda lateral— antes de que mi bola choque contra la baranda del fondo y vuelva para abajo otra vez, despacito, en línea oblicua.
#+end_quote

Así proseguía la narración por varios párrafos y varias páginas, discurriendo sobre la mesa de billar,
como si esa primera persona no compusiera un punto de vista sino apenas el soporte de una cámara que siguiera las alternativas del taco y las bolas y el humo de un cigarro y la interacción de cada una de esas cosas con la luz eléctrica y la luz de la calle. Una cámara empecinada en el detalle, como esa que al principio de /Blue Velvet/ se hunde en el pasto y se amontona con los bichos, como esa pero como si esa persistiera así, en esa perspectiva, durante dos horas de película. Porque eso que en /Cicatrices/ yo suponía un canchereo estilístico que el autor hacía para marcar la cancha y ahuyentar a lectores despistados como yo, se prolongaba todavía por párrafos e incluso más allá de esa primera escena. Se prolongaba, de hecho, por el resto de ese libro y aún en otros 15 más que escribió Saer durante 35 años, porque constituía, más o menos, su programa estético. El detalle y la descripción sometían al argumento: eran su forma de narrar. /Cicatrices/, en fin, me resultó impenetrable ---en palabras de Martín Zariello: [[https://ilcorvino.blogspot.com/2013/10/el-mundo-se-divide-entre-las-personas_31.html][inabordable]]--- y, como yo religioso ya no era, la abandoné.

Unos años después, durante la primera cuarentena, ese tiempo en que, un poco como, supe un poco después, Saer hace en sus novelas, el tiempo parecía detenerse o estirarse hasta que perdíamos su noción (la del tiempo), lo que nos llevaba a ocupaciones exóticas como amasar pan o mirar la bundesliga, hice otro intento de lectura de Saer, con /El entenado/. Y esta vez, sí, pude terminar el libro, e incluso disfrutarlo por momentos, aunque la operación en su conjunto tuvo menos de placer que de hazaña, de ejercicio de destreza y resistencia, como amasar pan o hacer flexiones de brazos o extraerle entretenimiento a un desolado partido de fútbol alemán. La del /Entenado/ fue una lectura que no floreció en nada, que se cerró sobre sí misma.

Más años más tarde, en 2024, siguiendo un nuevo impulso pero ya mucho más consciente de eso en lo que me metía, me llevé a un viaje /La pesquisa/. Y porque estaba mejor preparado y era otro momento y yo era, en cierta medida, una persona distinta (si bien, en cierta otra medida, ¿no?, la misma), y por determinadas características particulares de ese libro a elaborar más luego, no solo lo terminé y lo disfruté sino que inicié un proceso de lectura en el que Saer pasó de /inabordable/ o /de difícil abordaje/ a ser uno de mis escritores favoritos y el que más leí desde entonces.

Resulta que no solo Saer escribe difícil, no solo exige trabajo y paciencia, sino que hay que saber por dónde entrarle. Quiero vindicar entonces a /La pesquisa/ como puerta de entrada.

#+BEGIN_CENTER
\lowast{} \lowast{} \lowast{}
#+END_CENTER
