---
title: my blogging setup is my writing process
subtitle: (my writing process is my blogging setup)
date: 2024-11-21
layout: post
lang: en
tags: [meta]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

I do all of my writing in Emacs, with org-mode.

#+begin_export html
<br/><br/>
#+end_export


Any post begins as a TODO entry in an ~ideas.org~ file. The entry can be a tentative title, the thing I want to write about, or the list of sources I want to connect.


#+begin_export html
<br/><br/>
#+end_export


The entry sits there for weeks, months, even years. Whenever I think about something that seems connected, I attach a note to it. Or, if I'm away from my personal computer, I jot something down in any of the notebooks I keep around---on the desk, in my bag, in my nightstand drawer.

#+begin_export html
<br/><br/>
#+end_export

At some point I gather enough notes or I find myself thinking frequently about the ideas in the post, even trying full sentences in my mind, one after another. Then I know I'm ready to write.

#+begin_export html
<br/><br/>
#+end_export

I don't have a strict method for what comes next, which is for the better, I think. Sometimes I try to shuffle my notes into cohesive paragraphs. Sometimes I toss the notes and start with an outline. Increasingly, I take a stab at  handwriting in my notebook. Whatever the route my goal at this point is to arrive as quickly as possible to a first draft. To me, a first drat means a sequence of paragraphs without placeholders or missing pieces. When I get to that, if I get to that, the post will cascade into existence, even if I end up rewriting every line of thing.

#+begin_export html
<br/><br/>
#+end_export

The good thing about a handwritten first draft is that I can take as much time as I want revising and rephrasing as I type it in, without derailing or losing momentum. I can always channel back to the next paragraph in the notebook.

#+begin_export html
<br/><br/>
#+end_export

Notebook or not, before I start typing I need to a new file. I use [[https://jorge.olano.dev/][my own]] static site generator and it's integrated in my [[https://github.com/facundoolano/emacs.d/blob/784b20e7bb25f861dc1450ace7ce5e4719c001f9/modules/facundo-blog.el][Emacs configuration]], so I start with ~M-x org-blog-new-post~. This prompts for a title and visits a buffer in org-blog-mode with these contents:

#+begin_src yaml
---
title: My Blogging Setup is My Writing Process
date: 2024-11-21 19:47:20
layout: post
lang: en
tags: []
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en
#+end_src

And this is most of my Emacs setup:

#+begin_src elisp
(defun org-blog-setup ()
  "Setup the blog mode."
  (if (string= "es" (org-kw-language))
      (progn (ispell-change-dictionary "spanish")
          (set-input-method "spanish-prefix")))
  (setq-local org-footnote-section nil)
  (flyspell-mode 1)
  (company-mode -1)
  (writeroom-mode 1)
  (hl-line-mode -1)
  (global-hl-line-mode -1)
  (text-scale-increase 1))

(add-hook 'org-blog-mode-hook 'org-blog-setup)

(defun org-blog-new-post (title)
  "Create a new jorge post with the given TITLE and switch to it in blog mode."
  (interactive "MPost title: ")
  (let* ((project-root (projectile-project-root))
         (default-directory project-root)
         (output (shell-command-to-string (concat "jorge post \"" title "\"")))
         (post-path (string-trim (string-remove-prefix "added " output))))
    (find-file (expand-file-name post-path project-root))
    (org-blog-mode)))
#+end_src

I use [[https://github.com/joostkremers/writeroom-mode][writeroom-mode]] to get a centered block of text with minimal interface and a big font. And I adjust the input method and spell checking to the language of the post. ~org-blog-new-post~ just calls ~jorge post~ on the root of the project to create a new post file, and visits it in an org-blog-mode buffer. While I work on the file I keep ~jorge serve~ running on the terminal and the post open on a browser tab[fn:1]. And I save my progress with [[https://magit.vc/][Magit]] just as I would do with code.

#+begin_export html
<br/><br/>
#+end_export

With a first draft typed in, I just revise over and over until I can't find anything obviously wrong with the text---or until I can't stand the thing anymore, whatever happens first.

#+begin_export html
<br/><br/>
#+end_export

You'll see a lot of blogging advice around lowering the bar, writing about anything, not worrying about the quality of the post or whether anyone would want to read it. This is good advice to get started and I followed it here, for instance in my initial decision to write exclusively in Spanish, to write about personal stuff or things I'm not an expert at. But once I got the hang of it---now that I have more ideas than what I can get to write and I'm good enough at getting something finished---I shifted my focus to experimenting with form and style and imagination, trying to make the text as good as I can, no matter how long it takes. That's what I enjoy about this[fn:2].

#+begin_export html
<br/><br/>
#+end_export

This means that I may spend hours trimming the paragraphs, rearranging the sentences, searching for verbs, removing the superfluous adjective, counting the syllables until the rhythm feels right. This also means that, while I don't cater for a specific audience, I keep a model reader in mind while I write; that I don't publish what I can't make interesting for someone other than me; that I won't let the text grow unnecessarily long, or cryptic, or boring[fn:3].

#+begin_export html
<br/><br/>
#+end_export

I rely heavily on the dictionary and the thesaurus during revision, so I have handy commands for [[https://github.com/atykhonov/google-translate][google-translate]].
This is my favorite feature of writing in Emacs. The ability to dissect a word with a keystroke feels almost like a superpower.

#+begin_export html
<br/><br/>
#+end_export

I wouldn't be caught dead asking an LLM to write or rewrite for me but, since I'm not a native English speaker, I do keep a [[https://github.com/karthink/gptel][gptel]] chat buffer to check if an expression sounds awkward or I'm unsure about a preposition[fn:4]. This is one of the few things where the tool shines---or where I don't know better to tell in what way it sucks. Similarly, when I'm about done with an English post, I paste it on grammarly for grammar checks. I don't use their more advanced features, much like I don't ask GPT to proofread. I sense these tools want to push me towards a blander style, and I'd much rather own my faulty weirdness.


#+begin_export html
<br/><br/>
#+end_export

After every revision, I send the text to my Kindle to read away from my laptop. This lets me look at it with slightly fresher eyes, at the beginning or the end of the day. I highlight and make notes for any error and anything that sounds off or unnecessary or confusing, and fix it next time I sit to work on my desk. I repeat this for a few days until I stop finding obvious things to fix, which I take as a sign that I'm ready to publish.

#+begin_export html
<br/><br/>
#+end_export

(I mentioned how my process differs from typical blogging. This is how it's different from "serious" writing: if I really wanted to make the text as good as I can, I would shelve it for a few months, let myself forget about it, and go back to it as if someone else had written it, maybe starting a new draft from scratch. But I don't do that; I prefer a shorter life cycle, to get the thing out of my list and off of my head and move on to the next one.)


#+begin_export html
<br/><br/>
#+end_export

When I think the post is ready to ship I update the date, remove the ~draft~ flag, set an ~excerpt~---usually some phrase I like from the text---and a thumbnail picture.


#+begin_export html
<br/><br/>
#+end_export

This blog runs on debian and nginx, on a 4-dollar Hetzner box. When I'm done I run ~jorge build~ and [[https://github.com/facundoolano/olano.dev/blob/81563d563d9cf2f9fcdf5cc84b47544da2ba1f65/Makefile#L9-L10][rsync]] the files to it.


#+begin_export html
<br/><br/>
#+end_export


*** Notes
[fn:1] The implementation of this dev server is described [[https://jorge.olano.dev/blog/a-site-server-with-live-reload/][here]].
[fn:2] The more I write, the more I care about form and the less about content. /You must switch your allegiance from the triggering subject to the words/. If I keep writing for an infinite number of years, my blog posts would converge on poetry.
[fn:3] And if I can't resist the urge for a joke or a digression, at least I have the courtesy of sending it to a footnote.
[fn:4] Before LLMs I would google the phrase and count the results, something that doesn't even work anymore.
