---
title: La pieza ausente
date: 2026-02-03T14:32:17-03:00
layout: post
lang: es
tags: [libros, literatura, puzzles]
draft: true
refs: [missingpiece, parentesis, perec]
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es

Conjeturo que así vino la mano: en los '90 (como ahora), Anagrama publicaba a Georges Perec; alguien en Anagrama, pongamos que Jorge Herralde para hacerlo fácil, recibe esta novela del francés Antoine Bello, /Éloge de la pièce manquante/ (1998), una especie de cover u homenaje a /La vida instrucciones de uso/, un Perec "pasado por agua", y piensa, Herralde, que sería un buen agregado al catálogo, así que la manda a traducir y la saca en español en 2001. En los '90 Anagrama publicaba también a Bolaño, a esa altura un Bolaño ya consagrado con /Los detectives salvajes/, y es de suponer que el chileno recibía muestras de todo lo que publicaba la casa, o que cuando se pasaba por la oficina en Barcelona, digamos para cobrar un adelanto por /Una novelita lumpen/ o /Putas asesinas/, rebuscaba en la pila de novedades y se llevaba cualquier cosa que le fuera de interés, y que a lo mejor la ojeaba en el tren de regreso a Blanes, y que si pescaba su interés lo seguía leyendo, digamos fumando por la rambla o tomándose un café con leche en una taberna como la que describe en el último capítulo de /Estrella distante/. De vez en cuando alguno de esos libros le interesaba lo suficiente o le suscitaba una opinión suficientemente acabada como para tomarse la molestia de escribir una reseña para alguno de los medios de España o Chile o México con los que colaboraba por esos años. Tal fue el caso de /Elogio de la pieza ausente/. El libro de Bello pasa sin pena ni gloria por las librerías españolas y nunca se reimprime. El Bolaño, en cambio, se muere unos años después y se convierte en un fenómeno editorial (o viceversa). Entre las muchas obras póstumas que le empiezan a publicar, aparece /Entre paréntesis/, que recopila el trabajo periodístico de Bolaño, incluida su reseña de /La pieza ausente/. Como es natural, los devotos bolañistas que desde entonces leemos /Entre paréntesis/, tomamos nota de sus recomendaciones y salimos a cazar esos libros, particularmente el de Antoine Bello, particularmente si además nos fascinan los puzzles y las novelas policiales y sabemos algo de Georges Perec.
