---
title: The Mark Ferrari Parable
date: 2024-09-22 17:52:07
layout: post
lang: en
tags: [videogames, software, fiction]
draft: true
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

#+begin_verse
Already the displacement of one's thought-child
is not only conceived, but scheduled.
#+end_verse

MAYBE: /A Digital Artist/
/The Pixel Parable/
/A Pixel Parable/


#+begin_export html
<br/><br/>
#+end_export

"How would you like working as a video game artist?".

Mark holds his first prize certificate on one hand and the guy's card in the other. /Gary Winnick - Art Director - LucasFilm Games/. LucasFilm as in George Lucas. As in Star Wars.

"Could you come over to the Ranch for an interview?", he insists.

This is his second lucky break of the weekend. Mark is just out of art school, trying to make it as an illustrator. A friend recommended he show up to this sci-fi convention, he said these things are good for networking. Mark wouldn't mind having some of his work on a trading card, or a rule book, or, who knows? on the cover of one of those fantasy novels he used to read growing up.

So he shows up to the convention on Friday, someone notices his work---these pencil-drawn landscapes that look like they were hand-painted---, they invite him to participate in the convention's art show, he does, two days later he wins best of the show. That was his first lucky break that weekend; the second was this guy, Gary Winnick, coming over to him, handing him a card, asking him to 'audition' for a video game job.

Mark reads the card again, stops for a second to think what to say next. He needs a job, after all. Honesty has been working wonders for him this weekend, so he tells it straight:

"I'd be happy to come over to do <do anything at all there>, but... I don't know the first thing about video games. I never even touched a computer".

"That's alright", Gary replies, "we've had better results teaching artists how to program than programmers how to art. I'm not worried about that part".

Gary tells him about the job and Mark asks how is it to work at the Ranch. They agree on a date for the interview. The last two hours of the conference are a blank. He drives back home, trying to figure out what just happened. <On his first weekend as a professional illustrator, on this first try, he gets an offer for a job that he didn't even know existed five minutes ago but that he now thinks think that's both his dream job and one that he's terribly underqualified for.

Mark calls his parents to share the news. His father, he now learns---and this was the third and final lucky break of the weekend---has just bought a personal computer.

#+begin_export html
<br/><br/>
#+end_export


"What are you doing with this thing, anyway?", asks Mark. His sitting in front of the computer, skimming the manual. The cover reads Commodore Amiga.
"The school made a deal for us to get'em half price, they say we should be computer-literate if we want to have a job in five years". The voice comes into the room before the rest of his father, who then appears at the doorway, leaning on the frame. "I figured I could use it for writing, but they have a different brand at school, so I can't print my files. And I'm not buying a printer. You can take it if you want".

<"Let's see if I get the job, first. It says here there's a drawing program in this, let's try it out".

<maybe: amiga details, open a program, dpaint II? try it intuitively. TODO: read amiga book chapter

Mark secludes himself in his high school bedroom for the next few evenings, getting familiar with this computer thing and its paint program. The little mouse forces his hand into a claw. Whenever he begins to feel that he's gotten used to it, that he can forget about the tool and focus on the task, whenever his eyes seem to spark a connection between the image on the screen and the image on his brain, his hand jumps from the mouse to grip a pencil that's not there, like a phantom limb.

He teaches himself to draw a single picture, a little African hut that he repeats over and over until he memorizes the procedure, which he will repeat a few days later to survive his interview.

[TODO hut image]

#+begin_export html
<br/><br/>
#+end_export


<title: digital background artist
the same gary winnick shows him around, helps him setup his computer, deluxe paint and maniac mansion
for a couple of days they just let him play the maniac mansion game, to get a feel of the kind of thing they are trying to build
<imposter syndrome, everybody knows he's not a computer person, but also everybody is trying to figure out what it means to tell a story in this medium, in this genre, no one is an expert in that. and they value his artistic point of view

<drives out of the underground garage
place that looks as otherworldly as one of his fantasy landscapes, as a shot from Star Wars or a scene from that adventure game the company has just published.
<a <valley>, a lake, green hills, this old victorian house, with a theater and a huge library with a spiral staircase
<cattle, farm animals
he will be driving in this underground garage for the next three years, but he'll make a point of never taking this for granted, no matter how shitty the job gets

[TODO mansion image]
#+begin_export html
<br/><br/>
#+end_export

ironically, lucasfilm games didn't have the license to make star wars games. there were some /Indiana Jones/ projects on the works, but the games division were expected to come up with original ideas for the games. this was both a blessing and a curse, as he'd learn.

<lunch across the room from george lucas, stephen spielberg, leonard nimoy, the rolling stones
david lynch screening at the art deco theater of the main house
<same room but worlds apart
they don't seem much of the big guy, they may catch a glimpse of him at lunch, or when browsing the library, as he climbs the spiral staircase up to his office in the roof---which is off-limits.

truth is Lucas doesn't care for video games, the existence of the division a sort of accident from a different era of the company, his survival now <off of his hands.
this group of people, mostly computer hackers, had nothing to do with film making---any possible connection disappeared when pixar was sold to steve jobs---, and an <unstated rule> was to be as invisible as possible to lucas, not to tempt them to get rid of the division
a kind o intruders

<to make up for his absence, the executives throw around the single piece of advice they managed to get from the owner: “Stay small, be the best, don’t lose any money.”

the only part of this that affected him, Mark thought, was /be the best/, and that was how he intended to operate anyway, he didn't need a manager to tell him. he left to the suits, though, to figure out how his work and that of his teammates was supposed to be connected to the money making.

#+begin_export html
<br/><br/>
#+end_export

<he joins a team working on the follow-up adventure game

The programmers don't seem to care that he's a computer and video game neophyte. They invite him to join the brainstorming sessions, they ask for his input on design decisions, his water cooler jokes make it to the dialog of the game. They give him freedom to figure out the game backgrounds, handing him a short list of requirements for each one---items and doors that will be necessary for the gameplay of the scene, what they call /hotspots/---and as long as he meets them he can do whatever he wants.

it doesn't take him too long to become productive. that is, to work out a usable background fast enough to meet the developers expectations, which were lower than his own.
his goal was to produce art and get paid for it, so he give as little thought as possible to the needs of the project and the business.
it's convenient that they don't expect much from him, because not only he isn't satisfied with his production and it doesn't come close to art, he still feels he has a long way to go to tame the computer, the mouse, the pixels, the palette, and the drawing program.
he develops some 'coping mechanisms': he first makes sketches, plotting the pixel greed in a ruled notebook, to try options before moving to the computer screen where nothing seems to flow, where everything feels clumsy and rigid, like lego building, and it's hard to tell whether something's going to look good before it's done.

the most frustrating is encoding the pictures in those suffocating 16 colors, always the same palette for anything he may need to represent---black, dark gray, light gray, white, dark blue, light blue, cyan, yellow, mustard brown, dark red, poppy red, peach, magenta, acid-hot pink, grass green, and acid-chartreuse.
this is another thing where he needs to plan ahead, carefully measuring what colors he gets to spend, a decision he needs to make early on and that informs---constraints--- all the rest of his choices: the scene composition, the mood, what's shown, what's hinted.
<There's little room for the sort of creativity that stems from impulse and experimentation (but much from constraints, pushing the boundaries, happy accidents that lead to innovation
it gets better as /he/ gets better, more familiar with the tools; once he grasps what are his materials and what their capabilities and limitations, he can start using them to his advantage---work around and step on the constraints and push himself to be creative as with any art and any material, just like does with pencil and paper.

#+begin_export html
<br/><br/>
#+end_export

The mouse, the pixels, the 16-color palette, the hotspots, are the constraints he needs to work with and around. The programmers, too, with their arcane knowledge, can become another layer of constraints, a kind of the extension of the computers.
TODO: maybe use an example requirements for a particular zak scenario for this section. (that would require killing the paragraph above

One trick---a /hack/, as programmers would call it---he discovered early on was that if he formed a checkerboard pattern of pixel in his drawings, when he zoomed out the image pixels would blend and bleed in the screen, producing shades beyond the boring old 16 colors of the EGA palette.

This was one of those happy accidents, but since he found it he's been thinking how to use it to his advantage, and this background could be the perfect excuse.
<todo describe how he draws it, where he uses dither
<this was obviously not art, not yet, but it was better that anything he did before and anything he saw in the previous game; most importantly it was progress, it was a hint of path they could explore to get closer to his goal.
he sends it/takes it to the programmer, goes over to his desk to see their reaction and get some praise, we're taking the art on this game to a new level folks
<TODO dialog


*** Sources
- The Art of point & click
- mixnmojo #4 https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-4-Loom/5
- mixnmojo #5 https://mixnmojo.com/features/sitefeatures/LucasArts-Secret-History-The-Secret-of-Monkey-Island/7
- The Making of Monkey Island - Behind The Scenes https://youtu.be/ri4_3P2Oh14?feature=shared
- The Effect of CRTs on Pixel Art https://datagubbe.se/crt/
- The tar pit
- Why A.I. Isn’t Going to Make Art https://www.newyorker.com/culture/the-weekend-essay/why-ai-isnt-going-to-make-art
- Day of the Tentacle Remastered (developer commentary)
- Lucasfilm EGA adventures https://www.superrune.com/tutorials/lucasfilm_ega.php
- https://mixnmojo.com/features/sitefeatures/Monkey-Island-From-EGA-to-VGA/
- https://scientificgamer.com/lucasarts-time-machine-the-secret-of-monkey-island/
- antiquarian

*** material

he assumed things went well enough, as projects were still lined up and while they were staying smallish, as far as he could tell they didn't seem to be getting smaller

Lucas didn't care for games, but Spielberg certainly did, and he took any chance he had when working in the Ranch to visit the office and see what the games folks where up to.
game designers would get weekend calls for hints at tackling puzzles
it was a matter of time for spielberg to get involved in game, likely an Indiana Jones one, when the license <restrain> was over

https://web.archive.org/web/20030503162101fw_/http://lucasfans.mixnmojo.com/features/interview_stevepurcell_2.html
Working there was like going away to summer camp. We'd hike through the hills after lunch, toss a softball around in the field out back, go to screenings in George Lucas's amazing art deco theatre. We'd end up working late every night to make up for the time we spent getting distracted.

not only first illustrator job, first steady job.
(previously worked in all sorts of temporary jobs)
felt underqualified but was given freedom
worked in a dream place and earned much more than his father

for loom or for monkey: the scumm engine now could scale the character sprites to represent different distances, this meant that he could move away from the horizontal axis and add perspective to his scenes


https://www.arcadeattack.co.uk/brian-moriarty/
