#+OPTIONS: toc:nil num:nil ^:{}
#+LANGUAGE: es
#+BEGIN_EXPORT html
---
layout: post
title: "Derivas del bazar"
date: 2023-11-05 13:25:02
tags: [software]
---
#+END_EXPORT

Si pudiera salvar dos cosas del fuego de internet, serían Linux y Wikipedia. Linux y Wikipedia me parecen los mayores logros recientes de la humanidad, por razones mejor expresadas en las /Leyes de Linus/.

La primera Ley de Linus fue formulada por Eric Raymond en su ensayo /The Cathedral and the Bazaar/:

#+begin_quote
Given a large enough beta-tester and co-developer base, almost every problem will be characterized quickly and the fix obvious to someone.
#+end_quote

O, menos formalmente:

#+begin_quote
Given enough eyeballs, all bugs are shallow.
#+end_quote

Aunque se refiera explcíticamente al debugging, la ley habla de todo el proceso de desarrollo: el modelo aparentemente caótico del open source, semejante al tumulto del bazar, no solo puede producir software funcional sino que de hecho produce /mejor/ software que el modelo cerrado de la ceremoniosa catedral. Prueba de esto es que, después de Linux y Wikipedia, a nadie se le ocurriría comprar pagar por una licencia de Encarta o deployar un servidor con Windows.

La segunda de ley de Linus fue desarrollada por el propio Torvalds en su prólogo al libro /The Hacker Ethic/ de Pekka Himanen:

#+begin_quote
Linus’s Law says that all of our motivations fall into three basic categories. The categories, in order, are “survival”, “social life”, and “entertainment”. Entertainment may sound like a strange choice, but I mean by entertainment more than just playing games on your Nintendo. It’s chess. It’s painting. It’s the mental gymnastics involved in trying to explain the universe. Einstein wasn’t motivated by survival when he was thinking about physics. Nor was it probably very social. It was entertainment to him. Entertainment is something intrinsically interesting and challenging.

A “hacker” is a person who has gone past using his computer for survival to the next two stages. That is how something like Linux comes about. You don’t worry about making that much money. The reason that Linux hackers do something is that they find it to be very interesting, and they like to share this interesting thing with others. Suddenly, you get both entertainment from the fact that you are doing something interesting, and you also get the social part. This is how you have this fundamental Linux networking effect where you have a lot of hackers working together because they enjoy what they do. Hackers believe that there is no higher stage of motivation than that.
#+end_quote

Torvalds dice lo que sabe cualquier programador, pero también cualquier investigador, cualquier docente o artista[fn:1]: satisfechas las necesidades básicas (la supervivencia), los trabajadores creativos buscan realizar su vocación antes que maximizar sus ganancias. (Desde ya, esta elección la tienen solo los privilegiados que disponen de seguridad económica y tiempo libre, un detalle al que voy a volver más adelante).

El "entretenimiento" del que habla Torvalds explica por qué los programadores de open source trabajan en proyectos de su interés sin pretensiones de ganancia económica. La "vida social" explica la motivación para compartir ese trabajo, para formar comunidades y colaborar en otras tareas (como el debugging o la documentación), que son menos interesantes. Raymond y Himanen traducen esa motivación social en la búsqueda del prestigio y el reconocimiento entre pares. Apelando a cierta antropología inchequeable, algunos autores proponen que, en contextos de abundancia[fn:2], en lugar de una economía de mercado las comunidades se inclinan hacia una "cultura del regalo", en la que el estatus social deriva no de lo que se posee si no de lo que se da a los demás.

Si combinamos las dos leyes de Linus vemos que, por lo menos en algunos contextos, las personas están dispuestas a trabajar sin incentivos económicos y que de su trabajo resultan bienes de mejor calidad que los que produce el trabajo asalariado. Linux y Wikipedia demostraron, durante lo que posiblemente haya sido el período de mayor hegemonía del individualismo liberal, que la mayor innovación y riqueza no surge de la competencia en el mercado sino de la colaboración voluntaria entre individuos apasionados por su trabajo y despreocupados por su supervivencia.

#+BEGIN_CENTER
\ast{} \ast{} \ast{}
#+END_CENTER

A principios del siglo 21, la superioridad moral y técnica de Linux y Wikipedia parecían anunciar que la web traería un cambio paradigma en la producción intelectual. Volvamos al presente y preguntémonos qué fue del bazar. ¿Son la producción comunitaria y la inteligencia colectiva la norma en la era de la información? Después de que internet se globalizara y se masificara y permeara todos los aspectos de la vida, ¿hubo otros Linux y Wikipedia? ¿Podría volver a haberlos?

- así como el concierto de voluntades que produjo y mantiene wikipedia cerró para siempre la posibilidad de crear un negocio alrededor de restringir el acceso a información enciclopédica, hoy resulta impensable la idea de volver a organizar un número semejante de voluntades sin un negocio de por medio.
  - A simple vista parecería la vocación colaborativa de la web temprana se disipó, pero si prestamos atención
  más bien fue cooptado por empresas privadas.
  - todavía hay gente que dedica incontables horas de trabajo voluntario solamente por el valor de crear comunidad y ganar prestigio, pero ahora lo hacen en el jardín cerrado de empresas con fines de lucro. El caso paradigmático es el de Reddit, que no solo aprovecha el contenido de los usuarios sino que depende largamente del esfuerzo de moderación decentralizado. Otros casos parecidos son el de StackOverflow y Goodreads.
  - En su charla /How markets coopted free software’s most powerful weapon/, Benjamin Mako Hill llama /apertura estratégica/ el método con que las empresas incorporaron los beneficios de la producción comunitaria demostrada por wikipedia, linux y el software open-source, manteniendo <suficientes partes cerradas como para poder montar un negocio alrededor del trabajo de los usuarios>. Pone como ejemplo paradigmático a airbnb, como variante capitalista de couchsurfing
  - aquel prestigio intangible que motorizaba el ciclo virtuoso del open source y de wikipedia, se comoditizó en la forma seguidores, reproducciones y likes <que se pueden convertir a dólares.>
  - aunque los mecanismos tecnológicos y los incentivos de los usuarios sean parecidos, una vez introducido el negocio privados la cultura del regalo se desmorona, y lo que antes era trabajo comunitario y voluntario pasa a ser trabajo no pago, explotación,

- el economista griego Yanis Varoufakis va más lejos y propone que en la actualidad las relaciones capitalistas pasaron a un segundo plano y que el sistema moderno es una especie de feudalismo tecnológico, todos los usuarios de software de una u otra manera somos "siervos" que pagamos rentas a los dueños de la nube. de eso se tratan las redes sociales en las que pagaos con nuestra atención, los servicios de contenidos que pagamos con suscripciones, el ecommerce y las appstores en los que las plataformas monopólicas recogen un porcentaje de todas las transacciones que en ellas se realizan

#+BEGIN_CENTER
\ast{} \ast{} \ast{}
#+END_CENTER

Lo anterior sugiere que ya no habrá más Wikipedias, pero ¿qué pasa con el software Open Source? Daría la impresión de que hoy está más vivo que nunca, con la mayoría de los dispositivos del mundo y casi todos los servidores usando Linux, con la mayoría de los sistemas de software usando en mayor o menor medida software abierto.
Pero si estudiamos quién hace el trabajo y quién recoge los beneficios, o si simplemente googleamos "open source maintainers", resulta obvio que el software libre y abierto atraviesa una crisis de identidad y de sustentabilidad.

  - los principales beneficiarios del open source son las big tech que montan sus productos alrededor del software "regalado" (en una absoluta desproporción con la financiación que hagan de su desarrollo y el software que las propias corporaciones provean a la facultad --strategic openness---)
  - que a su vez tienen los recursos para esquivar las zonas grises legales reimplementando las partes que no pueden usar directamente
  - la cantidad promedio de mantenedores de un proyecto open source es 1. la producción de software open source pasó de ser un motivo de entretenimiento a una forma de autopromoción, una presión externa de crear un portfolio público con el que volverse más competitivo en el mercado laboral. (ya no hay bazaares, ahora hay kiosquitos).
  - como ahora hay personas y empresa que /dependen/ de software open source para sus proyectos, para sus trabajos o sus negocios, es fácil que los mantenedores asuman inconscientemente un sentido de obligación a satisfacer las necesidades de los usuarios o, en el peor de los casos, que los usuarios perciban que tienen derecho a exigirla.
  - el éxito técnico y de público de un proyecto open source está tan disociado de su sostenibilidad y de la remuneración a sus mantenedores que de hecho productos <neurálgicos> como openssl sobrevive precariamente por un par de trabajadores voluntarios
  - quienes pretenden vivir del software libre que producen, aún si este muestra ser útil y necesario, lo tienen que hacer eligiendo la inseguridad económica, la precariedad laboral, y hasta recurriendo a la caridad
  - quienes pretenden montar un negocio, vender servicios o montar empresas alrededor de un producto oss, tienen que someterse a reglas de competencia capitalista en las que llevan las de perder con las corporaciones que están mejor aceitadas para proveer servicios convenientes y que no tienen ataduras a una comunidad o una forma específica de relación con sus usuarios
    - más allá de los problemas de sustentabilidad, todo esto implica que open source en tanto modelo de desarrollo decentralizado (por fuera de las corporaciones), ya no puede realizar la superioridad técnica que tenía hacia fines de los 90.
    - daría la impresión de que Linux, en tanto proyecto de desarrollo colaborativo, fue menos un punto de partida que la culminación de la cultura Hacker de las décadas anteriores.

- será este el problema que había pronosticado el movimiento de software libre? la traición a la causa que fue la alternativa business-friendly del open source? se hubiera prevenido aferrandose al copyleft, se puede solucionar reviviendolo?
  - me parece que no. el software libre tenía sus propios problemas, que explican su subsecuente retroceso frente al open source.
  - surgió en una época en que usuario era aproximadamente lo mismo que programador, una época previa a la computación personal, al software como bien de consumo, ni que hablar a la masificación de la vida personal.
  - para la mayoría de los usuarios de software, sean programadores o no, no importa el acceso al código fuente o su modificación (y si importa es solo subsidiariamente, porque esa accesibilidad potencialmente implica más seguridad o privacidad). para el grueso de los usuarios la pelea ética por la libertad de código es intrascendente
  - no se implica en otras libertades, las de los usuarios de no ser explotados, espiados, etc. es decir que en el contexto mayor de los usuarios de software es una lucha elitista. <la libertad de codigo es invisible a los ojos del usuario
  - en contraposición del pragmatismo de oss, el software libre era ante todo una postura ética o ideológica, una forma intransigente de activismo que sin embargo se quedaba corto, no llevaba sus argumentos hasta sus últimas consecuencias: la abolición por completo de la propiedad intelectual y de la escasez artificial, mucho más allá del software. es decir, no se admitió como la ideología anticapitalista que era en el fondo
  - incluso los ejemplos de software libre más exitoso, linux el más paradigmático, lo son porque esas libertades no se contraponen con su uso comercial y privado. linux, de hecho, pese a haber elegido una licencia de software libre. Es que nada impide usar Linux (o Emacs, o las herramientas de GNU) para producir software comercial y cerrado; nada impide desplegar una plataforma privada y explotadora en servidores que corren Linux. Y haber elegido licencias más estrictas, que prohibieran esos usos, probablemente no hubieran resultado en más libertad sino en que la gente evitara usarlos, tal como evita usar las liberarías con licencias GPL.
  - es curioso que la filosofía más "lavada"del open source, que de hecho no se proponía una instancia ideológica, un activismo rupturista, terminó presentando de hecho una mayor oposición al mercado por su ubicuidad y por ofrecer resultados de mejor calidad que las alternativas privadas.

- desde mi punto de vista, el problema de fondo es que tanto el software libre como el open source planteaban formas de producción y subsitencia alternativas al mercado capitalista (raymond y otros (?) llaman gift economy).
  - (esto no necesariamente implica que sean proyectos explícitamente anti capitalistas sino que obedecen a incentivos diferentes).
  - y como suele ser el caso con todo lo no-capitalista en un medio capitalista, el sistema tiende a absorberlo o extinguirlo
  - se aferró intransigentemente a unas reglas que no eran adaptables al capitalismo pero tampoco lo desafiaban abiertamente, no se constituía como un proyecto alternativo. Ante todo, no tenían incentivos fuertes para sostenerse como sí tenía el OSS. así, se condenó al aislamiento y a la irrelevancia.
- el oss, por su parte, pero terminó siendo absorbido y en última instancia desactivado por el capitalismo, acaso porque su business-friendliness se convirtió en una intención de que el oss se convierta en si mismo un negocio o una forma de ganarse la vida en el mercado capitalista, subvirtiendo la lógica de gift economy del que surgió

- así como el deseo de colaboración, el sistema de incentivos de prestigio, la libertad de modificar, extender y contribuir código explican por qué el OSS fue adoptado por muchos desarrolladores y produjo software de calidad, sospecho que su ulterior propagación tiene menos que ver con sus contribuidores que con sus usuarios (aunque estos sean también programadores)
  - la propagación depende más de los usuarios que de los mantenedores/programadores (TODO: conectar con el tema de qué libertades son las que se respetan)
  - y me animo a decir que desde la perspectiva de los usuarios, nada es más importante que el hecho de que el software sea gratuito.
  - contrario a lo que decía fsf de free as in freedom, not beer, y la voluntad de negocio de oss, la gratuidad es el mejor selling point del software open source.
  - la gratuidad esquiva la escasez artificial, devuelve el software a su orden natural: si ya existe, se puede reproducir infinitamente sin costo, por lo que es natural no pretender pagar por él.
  - intuyo que la crisis actual del open source deriva de la pretensión (o la fuerza de gravedad (?)) de querer convertirlo en un negocio, a mayor o menor escala. de querer abandonar la dinámica de gift economy y trasladarlo a la del mercado, abandonando los incentivos que lo habían permitido y empujándolo a una competencia donde tiene menos chances de sobrevivir.
    - para convertirlo en negocio es necesario reinstalar formas de escasez artificial
    - similar a como los artistas tienen que someter su obra a la escasez artificial, antes de las discográficas o editoras ahora de las plataformas de distribución y streaming. o convencer a suficiente gente de ejercer el mecenazgo (crear un sistema de incentivos sociales como había sido la gift economy para el desarrollo oss)

# separator?

¿Qué caminos le quedan a los creadores de software? ¿Cuáles son las posibles derivas del bazar?
  1. aceptar las reglas del mercado capitalista. tratar de que les paguen por hacer, en alguna medida, lo que les gusta bajo sus propias reglas. Esto implica no ser dogmáticos en cuanto a las libertades del código, ajustarse a lo que pida el público o lo que le puedan convencer de que compre.
  2. tratar de preservar la lógica de la economía de regalo en el contexto del capitalismo. continuar produciendo por la satisfacción misma de la producción o por el prestigio que permite obtener.

     a. exponiéndose a que otros se beneficien del trabajo gratuito, como pasa con OSS.
     b. protegiendo el trabajo con recursos legales, al riesgo de que pierda audiencia y el autor pierda acceso a aquel prestigio. Este sería el caso del software libre

    En ambos casos, al existir embebido en la lógica capitalista, perpetúa el status quo: solo podrán permitirse la actividad creativa los que dispongan de tiempo libre y tengan sus necesidades básicas garantizadas
  3. tratar de cambiar el status quo por otro más justo, en el que quien contribuya software útil para la sociedad y especialmente software que pueda ser explotado económicamene, reciba suficiente rédito para subsistir y continuar ejerciendo esa actividad. desde luego que esto implica adentrarse en el terreno del idealismo y del activismo, de la política, en fin, en proporciones mucho más ambiciosas de lo que lo había hecho el movimiento del software libre. Implica involucrarse en un problema que excede (y precede) a la producción de software, el mismo que tienen la producción artística y científica, un problema no técnico sino socioeconómico que, como tal, no puede ser resuelto "endogámicamene", encerrados en el mundo del software, con trucos legales.

Un método de producción de software, por sí mismo, no puede cambiar la realidad. En el mejor de los casos puede constituirse, como el conocimiento colectivo de Wikipedia y el desarrollo colaborativo de Linux, en ejemplo, en un núcleo más de resistencia que necesitará de otros para representar una verdadera amenaza al statu quo.

# FIXME no embutir las ideas de la libre elección en el último párrafo, introducirlas antes por separado, aunque sea en el anteúltimo párrafo

Pero ya entrados en cambiar la realidad socieconómica, es interesante volver al ejemplo de las artes y las ciencias y al mundo que nos dejaba entrever el primer auge del Open Source. Porque el mundo ideal, no sería aquel en que los usos y las costumbres hayan cambiado para incentivar el mecenazgo o la remuneración de la producción de software. Ni tampoco uno en que los gobiernos lo subsidiaran o existieran mecanismos legales para obligar a las corporaciones a retribuirlo. El mundo ideal, aquel que maximizara no solo la innovación sino la gratificación de los individuos y las comunidades, aquel en el que florecerían dos, tres, muchos Linux y Wikipedias, es uno en el que las necesidades básicas estén garantizadas para todo el mundo, incondicionalmente. Para que cualquiera pueda entregarse no al trabajo que otros consideren útil o necesario, el que más venda, el que exija un comité o el que alguien esté dispuesto a financiar, sino al trabajo que a cada uno le plazca. <falta punch>

* fuentes

** cathedral and the bazaar
** the hacker ethic
** homesteading the noosphere
** https://firstmonday.org/ojs/index.php/fm/article/download/631/552?inline=1
** https://mako.cc/copyrighteous/libreplanet-2018-keynote
** varoufakis
** https://www.boringcactus.com/2020/08/13/post-open-source.html
** https://dev.to/zkat/a-system-for-sustainable-foss-11k9
** https://increment.com/open-source/the-rise-of-few-maintainer-projects/
** https://stratechery.com/2019/aws-mongodb-and-the-economic-realities-of-open-source/
** https://logicmag.io/failure/freedom-isnt-free/
** https://notesfrombelow.org/article/open-source-is-not-enough
** how to be an anticapitalist in the 21st century
** los caminos de la libertad
** https://jacobin.com/2015/03/socialism-innovation-capitalism-smith/

* tareas
** TODO pasar en limpio fuentes
** TODO thumbnail
** TODO first draft

* Notas sueltas

en algun lado mencionar que los métodos del open source son parecidos a los de la academia / investigadores (socializan resultados y colaboran en la construcción de conocimiento sin retribución económica sin mediación de privados, sí por prestigio / reputación)

- fs vs oss: había más gente queriendo crear y compartir que queriendo luchar por impedir el código cerrado

- ni aunque los estados lo reconocieran como bien común o se impusiera la práctica de las donaciones o cambiara la mentalidad para que aceptemos pagar por todo el software que usamos, se resolvería del todo la cuestión.
  - el mantainer que tiene que ajustarse a lo que paga el usuario, tiene que dedicarse como segundo trabajo a convertir su producto en atractivo para sus albaceas, dedicarse al marketing antes que al trabajo creativo.
  - siempre va a haber una cantidad de trabajo que surge de la motivación personal y que puede no serle útil a los demás, o no parecerlo hasta mucho después, y eso no significa que no deba ser hecho, porque esa es una manera de truncar la innovación

  - visto que el bazaar era una manera /seria/ de producir software, que el resultado era valioso y desafiaba en calidad a la competencia propietaria, que había gente que dependía y estaba dispuesta a pagar por software libre o abierto, era natural que los desarrolladores buscaran alguna manera de ganarse la vida escribiendo ese software o, mejor dicho: que encontraran una forma de subsistencia que (material y legalmente) los habilitara a seguir haciendo lo que querían (uno o más de los siguientes): programar y compartir sus creaciones, colaborar con sus pares, crear comunidad, producir software interesante, útil o desafiante, divertirse. (en el caso de free soft: asegurar y expandir las libertades del software)
  - de ahí surgieron las formas conocidas de vivir del open source: vender servicios de administración, soporte o extensión del software que se liberaba; cobrar por su distribución o por alguna garantía; usarlo como portfolio para conseguir trabajo privado, para dictar clases o vender libros; donaciones.

- nos acostumbramos a que todo lo digital sea gratis
- mismo problema con sostenimiento de servicios alternativos (eg costos de servidores, trabajo voluntario de moderadores)
- la caridad no resuelve, no es un modelo alternativo porque requiere que haya gente extrayendo plata "de afuera" para inyectar en la economía alternativa

github es la catedral y está cerrada

después crecimos y nos fuimos del barrio
el software libre resultó complicado

los artistas generan lo mejor de su obra antes de poder mantenerse con su arte, y lo ahcen como un sacrificio no esperando convertirlo en un negocio. en arg os escritores trabajan de otra cosa. bukowski.

* Footnotes

[fn:2] <La abundancia se puede interpretar de dos formas. Por un lado, en el "mundo real", como la ausencia de presiones económicas de subsistencia que supone Torvalds. Por otro, en el mundo digital considerado como espacio separado, como el libre acceso a la información en la web temprana y el libre acceso al software en el medio hacker de los años 70 y 80. Fue forzando la escasez artificial, mediante licencias y plataformas cerradas, que se introdujo la lógica de mercado en esos ambientes.>

[fn:1] Himanen cita a Steve Wozniak, que expresa una filosofía de vida equivalente a la ley de Linus (/H = F^{3}, Happiness equals food, fun and friends/) y vincula a los dos con la [[https://es.wikipedia.org/wiki/Pir%C3%A1mide_de_Maslow][jerarquía de las necesidades humanas de Maslow]].
