#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es
#+BEGIN_EXPORT html
---
layout: post
title: "El año en que volví a jugar"
date: 2023-12-27 12:12:31
tags: [videojuegos, memorias]
---
#+END_EXPORT

#+begin_export html
<div class="org-center"><h2>1</h2></div>
#+end_export


En mi memoria las fiestas, en particular la semana entre Noche Buena y Año nuevo, están asociadas a los videojuegos. No solo porque oficializaban el fin del año escolar y el comienzo de las vacaciones ---ese vasto territorio del ocio--- sino porque era común que me regalaran algún juego en Navidad y que yo le dedicara esos días en que había poco más que hacer que comer sobras y flotar en la pelopincho. Pienso en un 25 al mediodía, en 2001 o 2002, jugando al /Diablo II/.

#+BEGIN_EXPORT html
<br/>
<div></div>
#+END_EXPORT

Este blog denuncia el tiempo que paso [[file:../2020-09-29-memoria-videojueguistica/][recordando]], [[file:../2023-06-16-del-videojuego-como-puzzle][estudiando]], [[file:../2022-08-09-llegando-los-monos][investigando]], [[file:../2023-09-18-literatura-videojueguistica-vol-2][leyendo]] y [[file:../2023-11-01-notas-sobre-obra-dinn][escribiendo]]  sobre videojuegos; ocasionalmente [[https://github.com/facundoolano/rpg-cli][diseñándolos]] y [[https://github.com/facundoolano/house-taken-over][programándolos]]. Una cantidad exagerada de tiempo, considerando cuánto le dedico todavía a /jugarlos/.

#+BEGIN_EXPORT html
<br/>
<div></div>
#+END_EXPORT


Si hay un territorio del ocio, mi paso por la Universidad fue un destierro. Cuando empecé a estudiar y, después, a trabajar, le perdí el rastro a los videojuegos. En parte por falta de tiempo, en parte por cambios de intereses, en parte porque la programación parecía estimular la misma parte de mi cerebro. Al terminar mis estudios era un jugador /casual/, de Linux y Mac, de emuladores, de juegos /retro/.

#+BEGIN_EXPORT html
<br/>
<div></div>
#+END_EXPORT


Acaso siempre jugué un poco a contramano, con máquinas inoportunas o mirando para atrás. Acaso siempre hubo tanto de juego como de añoranza.

#+BEGIN_EXPORT html
<br/>
<div></div>
#+END_EXPORT

Este año me propuse reconquistar el ocio, me compré una computadora, volví a jugar.


#+begin_export html
<div class="org-center"><h2>2</h2></div>
#+end_export

- perfect tides
- aventuras descartadas: norco, unavowed++barrow

- hotline miami

- trails in the sky (+ trails 2)
- shadow tactics
- hyperlight drifter

- Zelda
- la noire

- obra dinn (link)
- signalis

#+begin_export html
<div class="org-center"><h2>3</h2></div>
#+end_export


difícilmente logre desarrollar una sensibilidad que me permita disfrutar lo que llamaría juegos "modernos"
   no por el hardware sino por el tamaño y el énfasis de la experiencia que proponen, algo de lo que más o menos llegué a entrever al escribir del videojuego como puzzle:
   prefiero la experiencia de juegos simples, que apelen a la creatividad, al potencial de descubrimiento a partir de pocos elementos, que a las experiencias grandiosas e inagotables


pendientes: psychonauts, firewatch, disco elysium,  octopath 2, roadwarden, golden idol (?), chrono cross (?, legend of mana
ace attorney
(completar con cosas de las que agregué en steam)
into the breach?
ahí quedan juntando polvo el skyrim y el witcher, y lo mismo podría pasar con el elden ring (ff x y algun otro que tengo instalado en steam o en el wishlist)
