#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es
#+BEGIN_EXPORT html
---
layout: post
title: "Borges cautivo"
date: 2024-01-12
tags: [literatura, libros]
---
#+END_EXPORT

/Al igual que todos los hombres, Rudyard Kipling fue muchos hombres/. Borges aplicó esa fórmula también a Shakespeare, a Ascasubi. Pero de él, de Borges, dice que fue alguien que se dedicó más a leer que a vivir. Nos propone un hombre unidimensional, un resumen, un rasgo: uno de sus personajes. Borges fue un hombre de letras.

Vale, pero, en todo caso, Borges fue /muchos hombres de letras/. Hubo uno antes y otro después de Norah Lange ---que explica su abandono momentáneo de la poesía---, uno antes y otro después del accidente en 1938 ---que lo obligó a la convalecencia que reprodujo en /El Sur/ y a la que él atribuye su vuelco a la ficción---, uno antes y otro después de la ceguera. Además de esos, célebres, hay un Borges marginal, colaborador de la revista /El Hogar/, el Borges de los /Textos cautivos/.

#+BEGIN_CENTER
\ast{} \ast{} \ast{}
#+END_CENTER

Entre 1936 y 1939 Borges firmó la sección de literatura extranjera de /El Hogar/, revista  "familiar" que solía incluir notas de moda, cocina y economía doméstica dirigidas a la "señora de la casa", algo así como la /Utilísima/ de aquella época. Las reseñas de libros y biografías sintéticas de Borges venían acompañadas de extraños retratos de los autores y rodeadas por publicidades de crema Hinds y Ovomaltina.

Cabe preguntarse qué interés podrían tener el público de esa revista en el peculiar surtido de clásicos universales, filósofos rebuscados, compiladores de antologías detectivescas y precursores de la ciencia ficción que Borges proponía cada semana, qué clase de ama de casa querría saltar de las instrucciones de bordado a /Las Palmeras Salvajes/ de Faulkner. Más interesante (y menos problemática) es la otra pregunta: ¿Qué hacía Borges publicando en esa revista?

En vez de buscar certezas biográficas, prefiero especular. Acaso Borges escribía esas columnas por la plata, porque de algo tiene que vivir el hombre de letras. Acaso se había impuesto cumplir una misión de divulgación literaria, sin importarle dónde y cuándo hacía sus intervenciones. Acaso escribía para una posteridad, para nosotros, para los perros de sus migajas literarias. Acaso esas notas eran desprendimientos necesarios de sus lecturas, borradores de los ensayos intergalácticos que después publicaba en /Sur/ y que recogió en /Discusión/ y /Otras Inquisiciones/.

#+BEGIN_CENTER
\ast{} \ast{} \ast{}
#+END_CENTER

Comparado con el resto de la obra de Borges, /Textos cautivos/ es un libro lleno de rarezas.

(se distingue de otras de sus misceláneas, (libros tardíos), como sus colecciones de prólogos que se vuelven necesariamente monótonas en la forma y que habla a veces hasta con reverencia de autores casi siempre muertos)

Nos muestra a Borges leyendo libros contemporáneos.  Libros que no le gustan, autores que no respeta.
y hasta películas
que lamenta el crepúsculo de sus ídolos
lejos del viejo ciego de la falsa humildad, que se ríe finje demencia cuando le preguntan por sus contemporáneos este es un borges irónico, cínico, inimputable
distinto del mitológico viejo ciego que recorre con su bastón los pasillos de una laberíntica biblioteca de marfil.

elegancia y el humor que usa para destrozar una obra o un autor o una escuela de pensamiento o un oficio <que vienen a ablandar la milanesa>.

me interesa es el tono que adopta Borges, los temas que elige y la concisión que el formato le impone

Nos muestra 200 veces seguidas cómo Borges elegía abordar un comentario, cómo construía la primera frase de 200 comentarios.
Nos enteramos furtivamente en qué momento del día leía Borges y cuánto tardaba en terminar un libro si le gustaba.

<entrenamiento para esas ficciones disfrazadas de ensayo como /Pierre Menard,/ para sus reseñas de libros que no existen

#+BEGIN_CENTER
\ast{} \ast{} \ast{}
#+END_CENTER

- la editorial haynes tenía un edificio en Río de Janeiro y Bogotá, no muy lejos de mi casa
una zona residencial, de calles cortas de adoquines
cuesta imaginarse aquellas oficinas
aquel edificio lujoso
fue derrumbado y reconstruido en un estilo parecido; quedan vestigios si uno mira bien, si uno sabe lo que busca y levanta la cabeza; queda un principio de torre, oculta por la vidriera de una panadería de barrio.

- Borges iba hasta el edificio dos veces al mes a dejar su página, a recibir sus 30 pesos. visitaba a algunos amigos en la redacción, salían a comer y caminar por Buenos Aires.

- <Roberto Arlt escribía sus aguafuertes para el diario /El Mundo/ de la misma editorial, tal vez en ese mismo edificio.
  Lo imagino golpeando la máquina de escribir, con un cigarrillo colgándole del labio reseco, viendo pasar al gordito Borges que viene a dejar su página de literatura extranjera para señoras, con el mismo desdén que tendría Iorio para el guitarrista de Rata Blanca.
